/* GENERATED by tools/gen_probe_ctx.c from src/codegen_c/probe_ctx_schema.h.
 * Do not edit. Regenerate with `make -C src/codegen_c probe-ctx`.
 *
 * The probe context contract, in the one numbering every side uses: the
 * M-core dispatcher that fills the frame, the runtime helper that reads it,
 * the capability table that publishes it, and the Linux installer that
 * checks a manifest against it. */
#ifndef SPNL_PROBE_CTX_GEN_H
#define SPNL_PROBE_CTX_GEN_H

#include <stdint.h>

#define PROBE_CTX_FORMAT_VERSION 1u
#define PROBE_CTX_N_FIELDS 3u
#define PROBE_CTX_N_ATTACH 1u
#define PROBE_CTX_BITMAP_WORDS 4u

/* Field ids. 1-based: 0 is reserved for "invalid", which is what an
 * out-of-range ctx_field() argument decays to. Burned into every blob that
 * calls ctx_field, hence append-only. */
enum probe_ctx_field {
  PROBE_CTX_FIELD_INVALID = 0,
  PROBE_CTX_FIELD_THREAD_CURRENT_ID            = 1,   /* uint32_t */
  PROBE_CTX_FIELD_THREAD_CURRENT_PRIORITY      = 2,   /* int8_t */
  PROBE_CTX_FIELD_TIMESTAMP_CYCLES             = 3,   /* uint64_t */
};

/* Attach ids. Ranges: 0x0001-0x0FFF RTOS-provided, 0x1000-0x1FFF
 * application-declared, 0xF000+ experimental (never published). */
enum probe_attach_id {
  PROBE_ATTACH_INVALID = 0,
  PROBE_ATTACH_THREAD_SWITCHED_IN           = 0x0001u,
};

/* Execution class of an attach point. Read by the cycle-budget policy and
 * by the fault policy; not documentation. */
enum probe_exec_class {
  PROBE_EXEC_THREAD       = 0,  /* preemptible thread context */
  PROBE_EXEC_SCHED_LOCKED = 1,  /* scheduler or irq lock held */
  PROBE_EXEC_ISR          = 2,  /* interrupt context */
};

/* Slot lifecycle. */
enum probe_slot_state {
  PROBE_SLOT_EMPTY          = 0,   /* no blob; IVARS and code slot are zeroed */
  PROBE_SLOT_STAGED         = 1,   /* blob written to staging, nothing validated yet */
  PROBE_SLOT_READY          = 2,   /* manifest, capability binding and cost admitted */
  PROBE_SLOT_ACTIVE         = 3,   /* dispatcher may call it */
  PROBE_SLOT_QUIESCING      = 4,   /* dispatcher will not call it; calls already entered may run */
  PROBE_SLOT_DETACHED       = 5,   /* active_calls == 0 */
  PROBE_SLOT_RECLAIMABLE    = 6,   /* ring drained and acknowledged; nothing left to read */
};

/* Drop classes. One counter cannot be diagnosed: "the consumer
 * is slow" and "the probe re-entered" call for opposite responses. */
enum probe_drop_class {
  PROBE_DROP_RING_FULL              = 0,
  PROBE_DROP_REENTRANT              = 1,
  PROBE_DROP_DISABLED_OR_FAULTED    = 2,
  PROBE_DROP_CYCLE_ADMISSION_REJECT = 3,
  PROBE_DROP_N                      = 4,
};

/* The frame the dispatcher fills and ctx_field() reads.
 *
 * Indexed by field id, so slot 0 is unused and reads of it are the invalid
 * case. `provided` says which slots this event actually filled: a probe
 * admitted against a capability cannot ask for anything else, so a miss
 * here means a bug rather than a user error, and the runtime counts it
 * instead of returning a silent zero. */
struct probe_ctx_frame {
  uint64_t v[PROBE_CTX_N_FIELDS + 1];
  uint64_t provided[PROBE_CTX_BITMAP_WORDS];
};

/* One published attach point. Fixed layout: another core reads this out of
 * shared memory, so no flexible array members and no implicit padding
 * assumptions -- the asserts below pin it. */
struct probe_attach_capability {
  uint32_t attach_id;
  uint32_t exec_class;
  uint32_t max_cycle_budget;
  uint32_t field_bitmap_words;
  uint64_t field_bitmap[PROBE_CTX_BITMAP_WORDS];
};

_Static_assert(sizeof(struct probe_attach_capability) == 16 + 8 * PROBE_CTX_BITMAP_WORDS,
               "probe_attach_capability has implicit padding; the two cores would disagree");

/* Per-attach provided-field bitmaps, generated from the schema so the
 * published capability and the dispatcher's filler cannot drift apart. */
#define PROBE_ATTACH_THREAD_SWITCHED_IN_BITMAP { 0x000000000000000eULL, 0x0000000000000000ULL, 0x0000000000000000ULL, 0x0000000000000000ULL }

/* The table the firmware publishes. Gated per attach point by the Kconfig
 * symbol the schema names: Zephyr's hook inventory is not this firmware's
 * exported attach set, so a point that was not built
 * in must not appear here. */
#define PROBE_CAPABILITY_TABLE_INIT \
  /* thread.switched_in */ \
  IF_ENABLED(CONFIG_OBS_ATTACH_THREAD_SWITCHED_IN, ( \
    { .attach_id = PROBE_ATTACH_THREAD_SWITCHED_IN, \
      .exec_class = PROBE_EXEC_SCHED_LOCKED, \
      .max_cycle_budget = 500u, \
      .field_bitmap_words = PROBE_CTX_BITMAP_WORDS, \
      .field_bitmap = PROBE_ATTACH_THREAD_SWITCHED_IN_BITMAP }, )) \


/* Names. The M-core does not need these to run, but the installer's
 * rejection message does, and a firmware built with diagnostics can say
 * which field a probe asked for. */
#ifdef PROBE_CTX_WANT_NAMES
static const char *const probe_ctx_field_names[PROBE_CTX_N_FIELDS + 1] = {
  "(invalid)",
  "thread.current.id",
  "thread.current.priority",
  "timestamp.cycles",
};
static const char *const probe_attach_names[PROBE_CTX_N_ATTACH] = {
  "thread.switched_in",
};
#endif /* PROBE_CTX_WANT_NAMES */

/* Sizes the dispatcher's filler and the reader must agree about. */
#define PROBE_CTX_FIELD_THREAD_CURRENT_ID_SIZE 4u
#define PROBE_CTX_FIELD_THREAD_CURRENT_ID_SIGNED 0u
#define PROBE_CTX_FIELD_THREAD_CURRENT_PRIORITY_SIZE 1u
#define PROBE_CTX_FIELD_THREAD_CURRENT_PRIORITY_SIGNED 1u
#define PROBE_CTX_FIELD_TIMESTAMP_CYCLES_SIZE 8u
#define PROBE_CTX_FIELD_TIMESTAMP_CYCLES_SIGNED 0u

#endif /* SPNL_PROBE_CTX_GEN_H */
