#!/usr/bin/env bash
#
# build-amp-blob.sh -- the older 2-pass build that runs a Ruby probe on the M7.
#
# Superseded by the fixed-ABI staging flow (see README); kept for reference.
#
#   pass 1: build firmware with a placeholder blob -> read amp_emit / amp_ivars
#           addresses from the ELF (nm).
#   AOT   : Ruby probe -> amp-m7 bytecode (SPNL_AMP_IVARS_BASE = &amp_ivars)
#           -> micro-bpf host JIT (AMP_HELPER_1 = &amp_emit) -> Thumb blob.
#   embed : blob bytes -> src/amp_blob.inc (installed=1).
#   pass 2: rebuild firmware with the real blob; verify amp_emit / amp_ivars
#           addresses are UNCHANGED (else the baked addresses would be wrong).
#
# usage: build-amp-blob.sh <probe.rb>     (default: examples/observability/amp/hb_hw.rb)
set -uo pipefail   # no -e: west/pipe steps can return non-zero benignly; check explicitly

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
APP="$REPO/examples/amp_m7_firmware"
PROBE="${1:-$REPO/examples/observability/amp/hb_hw.rb}"
PROBE_BASE="$(basename "$PROBE" .rb)"

Z=~/sdk/zephyrproject
SDK=~/sdk/zephyr-sdk-1.0.1
NM="$SDK/arm-zephyr-eabi/bin/arm-zephyr-eabi-nm"
WEST=~/miniforge3/envs/vector_search_env/bin/west
DRV="${AOT_DRIVER:-}"
[ -x "$DRV" ] || { echo "error: set AOT_DRIVER to the micro-bpf aot-driver binary (scratchpad/aot-driver)"; exit 2; }
CONTAINER="${CONTAINER:-spnlbuild}"

zbuild() {  # $1 = build dir
  ( cd "$Z" && source .venv/bin/activate 2>/dev/null
    export ZEPHYR_BASE="$Z/zephyr" ZEPHYR_TOOLCHAIN_VARIANT=zephyr ZEPHYR_SDK_INSTALL_DIR="$SDK"
    "$WEST" build -p always -b imx95_evk/mimx9596/m7 "$APP" -d "$1" > "$1.buildlog" 2>&1 )
  local rc=$?
  [ $rc -eq 0 ] || { echo "[s4] west build failed (rc=$rc); tail of $1.buildlog:"; tail -15 "$1.buildlog"; }
  return $rc
}
elf_of() { ls "$1"/zephyr/*.elf | grep -v pre | head -1; }
addr_of() { "$NM" "$1" | awk -v s="$2" '$3==s{print "0x"$1}'; }

echo "[s4] pass 1: placeholder-blob firmware"
cat > "$APP/src/amp_blob.inc" <<'EOF'
#define AMP_BLOB_MAX 512
static const unsigned char amp_blob[AMP_BLOB_MAX] __attribute__((aligned(8))) = { 0 };
static const volatile int amp_blob_installed = 0;
EOF
zbuild /tmp/amp-m7-p1 || exit 1
E1="$(elf_of /tmp/amp-m7-p1)"
EMIT="$(addr_of "$E1" amp_emit)"
IVARS="$(addr_of "$E1" amp_ivars)"
echo "     amp_emit=$EMIT  amp_ivars=$IVARS"
[ -n "$EMIT" ] && [ -n "$IVARS" ] || { echo "[s4] FAIL: could not read symbols"; exit 1; }

echo "[s4] AOT: $PROBE_BASE.rb -> amp-m7 bytecode -> Thumb blob (ivars=$IVARS, emit=$EMIT)"
REL="${PROBE#"$REPO"/}"   # repo-relative path (macOS realpath lacks --relative-to)
container exec "$CONTAINER" sh -c "cd /work && SPNL_AMP_M7=1 build/codegen_c/spinel-ebpf-cc '$REL' $PROBE_BASE > /tmp/$PROBE_BASE.bpf.c 2>/dev/null && clang -O2 -target bpf -DSPNL_AMP_IVARS_BASE=${IVARS}u -c /tmp/$PROBE_BASE.bpf.c -o /tmp/$PROBE_BASE.bpf.o && cp /tmp/$PROBE_BASE.bpf.o /work/examples/amp_m7_firmware/$PROBE_BASE.bpf.o"
AMP_HELPER_1="$EMIT" "$DRV" "$APP/$PROBE_BASE.bpf.o" "$APP/blob.bin" | sed 's/^/     /'
[ -s "$APP/blob.bin" ] || { echo "[s4] AOT produced no blob"; exit 1; }
rm -f "$APP/$PROBE_BASE.bpf.o"

echo "[s4] embed blob -> src/amp_blob.inc"
python3 - "$APP/blob.bin" > "$APP/src/amp_blob.inc" <<'PY'
import sys
data = open(sys.argv[1],'rb').read()
MAX = 512
assert len(data) <= MAX, f"blob {len(data)} > {MAX}"
print("/* generated by build-amp-blob.sh — AOT'd Ruby probe (Thumb, ARMv7E-M). */")
print(f"#define AMP_BLOB_MAX {MAX}")
print(f"static const unsigned char amp_blob[AMP_BLOB_MAX] __attribute__((aligned(8))) = {{")
body = list(data) + [0]*(MAX-len(data))
for i in range(0,MAX,12):
    print("  " + "".join(f"0x{b:02x}," for b in body[i:i+12]))
print("};")
print("static const volatile int amp_blob_installed = 1;")
print(f"/* blob = {len(data)} bytes */", file=sys.stderr)
PY
rm -f "$APP/blob.bin"

echo "[s4] pass 2: real-blob firmware"
zbuild /tmp/amp-m7 || exit 1
E2="$(elf_of /tmp/amp-m7)"
EMIT2="$(addr_of "$E2" amp_emit)"
IVARS2="$(addr_of "$E2" amp_ivars)"
echo "     amp_emit=$EMIT2  amp_ivars=$IVARS2"
if [ "$EMIT" != "$EMIT2" ] || [ "$IVARS" != "$IVARS2" ]; then
  echo "[s4] FAIL: address drift between passes (baked addresses would be wrong)"; exit 1
fi
echo "[s4] OK: addresses stable across passes. firmware = $E2"
