/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OPENTELEMETRY_PROTO_COLLECTOR_LOGS_V1_OPENTELEMETRY_PROTO_COLLECTOR_LOGS_V1_LOGS_SERVICE_PB_H_INCLUDED
#define PB_OPENTELEMETRY_PROTO_COLLECTOR_LOGS_V1_OPENTELEMETRY_PROTO_COLLECTOR_LOGS_V1_LOGS_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "opentelemetry/proto/logs/v1/logs.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest {
    /* An array of ResourceLogs.
 For data coming from a single resource this array will typically contain one
 element. Intermediary nodes (such as OpenTelemetry Collector) that receive
 data from multiple origins typically batch the data before forwarding further and
 in that case this array will contain multiple elements. */
    pb_callback_t resource_logs;
} opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest;

typedef struct _opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess {
    /* The number of rejected log records.

 A `rejected_<signal>` field holding a `0` value indicates that the
 request was fully accepted. */
    int64_t rejected_log_records;
    /* A developer-facing human-readable message in English. It should be used
 either to explain why the server rejected parts of the data during a partial
 success or to convey warnings/suggestions during a full success. The message
 should offer guidance on how users can address such issues.

 error_message is an optional field. An error_message with an empty value
 is equivalent to it not being set. */
    pb_callback_t error_message;
} opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess;

typedef struct _opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse {
    /* The details of a partially successful export request.

 If the request is only partially accepted
 (i.e. when the server accepts only parts of the data and rejects the rest)
 the server MUST initialize the `partial_success` field and MUST
 set the `rejected_<signal>` with the number of items it rejected.

 Servers MAY also make use of the `partial_success` field to convey
 warnings/suggestions to senders even when the request was fully accepted.
 In such cases, the `rejected_<signal>` MUST have a value of `0` and
 the `error_message` MUST be non-empty.

 A `partial_success` message with an empty value (rejected_<signal> = 0 and
 `error_message` = "") is equivalent to it not being set/present. Senders
 SHOULD interpret it the same way as in the full success case. */
    bool has_partial_success;
    opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess partial_success;
} opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_init_default {{{NULL}, NULL}}
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_init_default {false, opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_init_default}
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_init_default {0, {{NULL}, NULL}}
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_init_zero {{{NULL}, NULL}}
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_init_zero {false, opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_init_zero}
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_init_zero {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_resource_logs_tag 1
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_rejected_log_records_tag 1
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_error_message_tag 2
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_partial_success_tag 1

/* Struct field encoding specification for nanopb */
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  resource_logs,     1)
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_CALLBACK pb_default_field_callback
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_DEFAULT NULL
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_resource_logs_MSGTYPE opentelemetry_proto_logs_v1_ResourceLogs

#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  partial_success,   1)
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_CALLBACK NULL
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_DEFAULT NULL
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_partial_success_MSGTYPE opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess

#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    rejected_log_records,   1) \
X(a, CALLBACK, SINGULAR, STRING,   error_message,     2)
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_CALLBACK pb_default_field_callback
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_DEFAULT NULL

extern const pb_msgdesc_t opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_msg;
extern const pb_msgdesc_t opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_msg;
extern const pb_msgdesc_t opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_fields &opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_msg
#define opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_fields &opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_msg
#define opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_fields &opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_msg

/* Maximum encoded size of messages (where known) */
/* opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest_size depends on runtime parameters */
/* opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse_size depends on runtime parameters */
/* opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
