/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "opentelemetry/proto/collector/logs/v1/logs_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest, opentelemetry_proto_collector_logs_v1_ExportLogsServiceRequest, AUTO)


PB_BIND(opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse, opentelemetry_proto_collector_logs_v1_ExportLogsServiceResponse, AUTO)


PB_BIND(opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess, opentelemetry_proto_collector_logs_v1_ExportLogsPartialSuccess, AUTO)



