# Auto kernel-cache — per-response partition demo (Phase 1: runtime populate).
#
# No hand-written eBPF at all. Declaring `kernel_cache "/ping", body` is enough
# for spinel-ebpf to synthesize a "pure-XDP TCP slice" via partition, so HTTP
# requests to /ping are answered entirely inside the kernel (SYN/data/FIN handled
# in XDP, no userspace listen socket, no accept/read/write = zero FFI marshalling).
#
# Phase 1: the response body is BUILT AT RUNTIME and pushed into a BPF map
# (bpf_kc_resp) via sp_kc_set. So instead of a fixed string baked into the .bpf.c
# at compile time, a value computed at startup can become the kernel cache entry.
#
# Run:
#   spinel-ebpf compile examples/http_server/kernel_cache_demo/ping.rb --build -o build/kc
#   SPNL_XDP_IFACE=lo ./build/kc/ping &
#   curl http://127.0.0.1:8080/ping        # -> kernel returns the body built at runtime

module KCache
  # glue (generated by bin/spinel-ebpf): push the body into the slot for `path`.
  ffi_func :sp_kc_set, [:str, :str], :int
end

# `kernel_cache` directive: at compile time the path becomes an XDP match;
# at runtime (path, body) is pushed into the kernel's response cache.
def kernel_cache(path, body)
  KCache.sp_kc_set(path, body)
end

# The body is built at runtime (not a compile-time constant).
body = "PONG " + "(served from a runtime-populated kernel map)\n"
kernel_cache "/ping", body

puts "[kc] /ping is served from the kernel (pure-XDP, runtime-populated map)."
puts "[kc] curl http://127.0.0.1:8080/ping   (sleeping 120s so XDP stays attached)"
sleep 120
