# Auto kernel-cache -- partitioning at the granularity of a single response,
# with the body populated at runtime.
#
# No hand-written eBPF at all. Just declaring `kernel_cache "/ping", body` makes
# spinel-ebpf synthesize a "pure-XDP TCP slice" during partitioning, so an HTTP
# request for /ping is **answered entirely inside the kernel** (SYN/data/FIN are
# all handled in XDP; there is no userspace listen socket and no accept/read/write,
# so there is zero FFI marshalling).
#
# The response body is **built at runtime** and pushed into a BPF map
# (bpf_kc_resp) via sp_kc_set. So it is not a fixed string baked into the .bpf.c
# at compile time: a value computed at startup can become the kernel cache entry.
#
# Running it:
#   spinel-ebpf compile examples/http_server/kernel_cache_demo/ping.rb --build -o build/kc
#   SPNL_XDP_IFACE=lo ./build/kc/ping &
#   curl http://127.0.0.1:8080/ping        # -> the kernel returns the body built at runtime

module KCache
  # glue (generated by bin/spinel-ebpf): push a body into the slot for this path.
  ffi_func :sp_kc_set, [:str, :str], :int
end

# The `kernel_cache` directive: at compile time the path is used for the XDP
# match, and at runtime (path, body) is pushed into the kernel's response cache.
def kernel_cache(path, body)
  KCache.sp_kc_set(path, body)
end

# The body is built at runtime (i.e. it is not a compile-time constant).
body = "PONG " + "(served from a runtime-populated kernel map)\n"
kernel_cache "/ping", body

puts "[kc] /ping is served from the kernel (pure-XDP, runtime-populated map)."
puts "[kc] curl http://127.0.0.1:8080/ping   (sleeping 120s so XDP stays attached)"
sleep 120
