# frozen_string_literal: true
#
# GENERATED by tools/gen_loader_contract.c from src/codegen_c/loader_contract.h.
# Do not edit by hand -- edit the declaration and re-run
#   make -C src/codegen_c loader-contract
# then commit this file. tools/loader_gate.rb fails when it is stale.
#
# These constants are the LOADER's half of the codegen seam. They exist
# so that bin/spinel-ebpf's glue heredoc contains no map-name literal, no
# hand-typed strncmp length and no hand-typed record width: the four drifts
# measured against this seam are not writable through this interface.

module SpinelEbpf
  module LoaderContract
    PROG_ARRAY_SLOT_BASE = 0

    # token constants -- interpolated into the glue
    MAP_PROG_ARRAY         = "spnl_prog_array"
    MAP_BLOCKLIST          = "bpf_blocklist"
    MAP_CIDR_BLOCK         = "bpf_cidr_block"
    MAP_USER_CMDS          = "bpf_user_cmds"
    MAP_WORKER_SOCKS       = "bpf_worker_socks"
    MAP_STACKS             = "bpf_stacks"
    MAP_HIST_KEYED         = "bpf_hist_keyed"
    SUFFIX_EMIT_INT        = "_events"
    SUFFIX_EMIT_STR        = "_str_events"
    SUFFIX_EMIT_PAIR       = "_pair_events"
    SUFFIX_EMIT3           = "_emit3_events"
    SUFFIX_EMIT4           = "_emit4_events"
    SUFFIX_LOST            = "_lost"
    SUFFIX_DNS             = "_dns_events"
    SUFFIX_CONN            = "_conn_events"
    SUFFIX_L7              = "_l7_events"
    SUFFIX_HTTP            = "_http_events"
    SUFFIX_REDIS           = "_redis_events"
    SUFFIX_OFFCPU          = "_offcpu_events"
    SUFFIX_L7STREAM        = "_l7stream_events"
    PREFIX_XDP_TAIL        = "xdp_tail__"
    PREFIX_UPROBE          = "uprobe__"
    PREFIX_URETPROBE       = "uretprobe__"
    PREFIX_USDT            = "usdt__"
    PREFIX_TIMER_ARM       = "spnl_timer_arm_"
    SEPARATOR_USDT         = "__"
    SEC_UPROBE             = "uprobe"
    SEC_URETPROBE          = "uretprobe"
    SEC_USDT               = "usdt"
    SEC_PERF_EVENT         = "perf_event"
    SEC_KPROBE_MULTI       = "kprobe.multi"
    PREFIX_RODATA_PARAM    = "spnl_param_"
    PREFIX_RODATA_FILTER   = "spnl_filter_"

    # strncmp/strstr lengths, computed from the token so they cannot disagree
    SUFFIX_EMIT_INT_LEN = 7
    SUFFIX_EMIT_STR_LEN = 11
    SUFFIX_EMIT_PAIR_LEN = 12
    SUFFIX_EMIT3_LEN = 13
    SUFFIX_EMIT4_LEN = 13
    SUFFIX_LOST_LEN = 5
    SUFFIX_DNS_LEN = 11
    SUFFIX_CONN_LEN = 12
    SUFFIX_L7_LEN = 10
    SUFFIX_HTTP_LEN = 12
    SUFFIX_REDIS_LEN = 13
    SUFFIX_OFFCPU_LEN = 14
    SUFFIX_L7STREAM_LEN = 16
    PREFIX_XDP_TAIL_LEN = 10
    PREFIX_UPROBE_LEN = 8
    PREFIX_URETPROBE_LEN = 11
    PREFIX_USDT_LEN = 6
    PREFIX_TIMER_ARM_LEN = 15

    # widths the loader moves, in bytes (0 = it moves no fixed record)
    MAP_PROG_ARRAY_BYTES = 4
    MAP_BLOCKLIST_BYTES = 1
    MAP_CIDR_BLOCK_BYTES = 1
    MAP_USER_CMDS_BYTES = 8
    MAP_WORKER_SOCKS_BYTES = 8
    PREFIX_RODATA_PARAM_BYTES = 8
    PREFIX_RODATA_FILTER_BYTES = 8

    # the whole table, for `describe` and for the unit tests
    ENTRIES = [
      { token: "spnl_prog_array", const: "MAP_PROG_ARRAY", kind: :map_name, authority: :golden, witness: "142_tail_call_dispatch", map_type: "PROG_ARRAY", key_ctype: "__u32", value_ctype: "__u32", value_bytes: 4, alloc: "declaration order of `def xdp_tail__<name>`, base LC_PROG_ARRAY_SLOT_BASE", encoding: "the value is written as a program fd; the kernel stores the program", encoding_measured: "Round-tripped: wrote fd 3 into a PROG_ARRAY and read the value back as 138189, which is exactly bpf_prog_get_info_by_fd(fd).id -- not the fd.", note: "A jump into an unpopulated slot FALLS THROUGH silently, so an off-by-one here is not an error, it is a different program running." }.freeze,
      { token: "bpf_blocklist", const: "MAP_BLOCKLIST", kind: :map_name, authority: :golden, witness: "31_tc_blocklist", map_type: "HASH", key_ctype: "__u32", value_ctype: "__u8", value_bytes: 1, alloc: nil, encoding: "key is an IPv4 address in HOST order (the BPF side converts, not the loader)", encoding_measured: "Round-tripped: the shipped loader stored sp_bpf_blocklist_add(0x7F000001) as the key 2130706433 verbatim (bpftool dump of the running probe), and that key matched a wire frame whose saddr bytes are 7f 00 00 01 under BPF_PROG_TEST_RUN; the byte-swapped key 16777343 did NOT match.", note: "sp_bpf_blocklist_add/del." }.freeze,
      { token: "bpf_cidr_block", const: "MAP_CIDR_BLOCK", kind: :map_name, authority: :golden, witness: "57_cidr_blocklist", map_type: "LPM_TRIE", key_ctype: "struct spnl_cidr_key", value_ctype: "__u8", value_bytes: 1, alloc: nil, encoding: "key.data[0..3] is the IPv4 address most-significant byte first, which is NOT the host order the same loader passes to bpf_blocklist", encoding_measured: "Round-tripped: the SAME binary in the SAME run stored 127.0.0.0/8 here as data=[127,0,0,0] while storing 127.0.0.1 in bpf_blocklist as the host-order integer 2130706433 -- the two byte orders side by side. MSB-first matched a real 127.0.0.1 frame; the host-order bytes [0,0,0,127] did not.", note: "LPM_TRIE keys are a prefixlen plus big-endian bytes by kernel rule." }.freeze,
      { token: "bpf_user_cmds", const: "MAP_USER_CMDS", kind: :map_name, authority: :golden, witness: "143_user_ringbuf_channel", map_type: "USER_RINGBUF", key_ctype: nil, value_ctype: "__s64", value_bytes: 8, alloc: nil, encoding: "one record is exactly one __s64, FIFO; a short record makes bpf_dynptr_read return -E2BIG and the callback observe zero", encoding_measured: "Round-tripped: the width first (8 -> the value arrives; 4 -> rc=-7 = -E2BIG and the value is 0; 16 -> the first 8 bytes), then the word FIFO, which nothing had measured: 11, 22, 33 pushed and one drain saw 11, 22, 33.", note: "Reserving 4 here is silent at run time -- the callback fires, the count is right, and only the value is 0." }.freeze,
      { token: "bpf_worker_socks", const: "MAP_WORKER_SOCKS", kind: :map_name, authority: :golden, witness: "168_reuseport_select", map_type: "REUSEPORT_SOCKARRAY", key_ctype: "__u32", value_ctype: "__u64", value_bytes: 8, alloc: "worker index chosen by the forking userspace, not by the codegen", encoding: "the value is written as a listen fd; the kernel stores the socket it names", encoding_measured: "Round-tripped: wrote listen fd 4 (as __u64, which is part of the encoding) and read the value back as 4097 = the socket's SO_COOKIE; an unbound socket was refused with EINVAL.", note: "sp_bpf_reuseport_register." }.freeze,
      { token: "bpf_stacks", const: "MAP_STACKS", kind: :map_name, authority: :golden, witness: "48_stack_trace", map_type: "STACK_TRACE", key_ctype: "__u32", value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "value_ctype is deliberately NULL: the producer spells the value `127 * sizeof(__u64)` and the loader never reads it -- only the NAME travels, runtime (spnl_dump_stack, the offcpu drain, the request-tree push)." }.freeze,
      { token: "bpf_hist_keyed", const: "MAP_HIST_KEYED", kind: :map_name, authority: :golden, witness: "42_keyed_hist", map_type: "HASH", key_ctype: "__u64", value_ctype: "struct spnl_hist_struct", value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Same as bpf_stacks: the name travels to the runtime as an argument." }.freeze,
      { token: "_events", const: "SUFFIX_EMIT_INT", kind: :map_suffix, authority: :golden, witness: "103_emit_parent_path", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The `spnl_emit` channel, and also the loose end of every other suffix: the loader's ringbuf sweep tests it LAST and only after excluding the specific ones." }.freeze,
      { token: "_str_events", const: "SUFFIX_EMIT_STR", kind: :map_suffix, authority: :golden, witness: "103_emit_parent_path", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The `spnl_emit_str` channel." }.freeze,
      { token: "_pair_events", const: "SUFFIX_EMIT_PAIR", kind: :map_suffix, authority: :golden, witness: "137_sock_accessors", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The `spnl_emit_pair` channel." }.freeze,
      { token: "_emit3_events", const: "SUFFIX_EMIT3", kind: :map_suffix, authority: :golden, witness: "36_emit_n_tuple", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The `spnl_emit3` channel." }.freeze,
      { token: "_emit4_events", const: "SUFFIX_EMIT4", kind: :map_suffix, authority: :golden, witness: "137_sock_accessors", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The `spnl_emit4` channel." }.freeze,
      { token: "_lost", const: "SUFFIX_LOST", kind: :map_suffix, authority: :golden, witness: "105_emit_dns", map_type: "PERCPU_ARRAY", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-channel ring-full counter. Matched at the END of the name (`_mn + _ml - 5`), not anywhere in it, so the length 5 is part of the contract and is generated from the token." }.freeze,
      { token: "_dns_events", const: "SUFFIX_DNS", kind: :map_suffix, authority: :record_schema, witness: "dns", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit DNS-event channel." }.freeze,
      { token: "_conn_events", const: "SUFFIX_CONN", kind: :map_suffix, authority: :record_schema, witness: "conn", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit connect-event channel." }.freeze,
      { token: "_l7_events", const: "SUFFIX_L7", kind: :map_suffix, authority: :record_schema, witness: "l7", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit L7 latency-event channel." }.freeze,
      { token: "_http_events", const: "SUFFIX_HTTP", kind: :map_suffix, authority: :record_schema, witness: "http", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit HTTP L7 RED channel." }.freeze,
      { token: "_redis_events", const: "SUFFIX_REDIS", kind: :map_suffix, authority: :record_schema, witness: "redis", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit Redis L7 RED channel." }.freeze,
      { token: "_offcpu_events", const: "SUFFIX_OFFCPU", kind: :map_suffix, authority: :record_schema, witness: "offcpu", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit off-CPU L7 correlation channel." }.freeze,
      { token: "_l7stream_events", const: "SUFFIX_L7STREAM", kind: :map_suffix, authority: :record_schema, witness: "l7stream", map_type: "RINGBUF", key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The per-unit sock-keyed L7 stream channel, and the one channel the loader reads with its own C text rather than the runtime's mirror (record_schema.h calls that out as outside its scope)." }.freeze,
      { token: "xdp_tail__", const: "PREFIX_XDP_TAIL", kind: :prog_prefix, authority: :golden, witness: "142_tail_call_dispatch", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Used for OPPOSITE decisions in two places: skip auto-attach, and populate the PROG_ARRAY. A prefix that matched only one of the two would attach tail-call targets to the interface." }.freeze,
      { token: "uprobe__", const: "PREFIX_UPROBE", kind: :prog_prefix, authority: :golden, witness: "109_ssl_http_l7", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Program-name prefix for uprobe handlers." }.freeze,
      { token: "uretprobe__", const: "PREFIX_URETPROBE", kind: :prog_prefix, authority: :golden, witness: "109_ssl_http_l7", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Program-name prefix for uretprobe handlers." }.freeze,
      { token: "usdt__", const: "PREFIX_USDT", kind: :prog_prefix, authority: :golden, witness: "39_usdt_basic", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The loader splits the REST of the name on `__` into provider/probe, so the prefix length also fixes where that split starts." }.freeze,
      { token: "spnl_timer_arm_", const: "PREFIX_TIMER_ARM", kind: :prog_prefix, authority: :golden, witness: "145_timer_event_loop", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "The loader runs these once with bpf_prog_test_run to arm the timer; missing them means the probe loads and never ticks." }.freeze,
      { token: "__", const: "SEPARATOR_USDT", kind: :prog_separator, authority: :golden, witness: "39_usdt_basic", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "`usdt__<provider>__<probe>`: the loader takes the FIRST `__` after the prefix, so a provider containing `__` is not representable -- which is why the loader carries an explicit 'malformed USDT prog name' diagnostic." }.freeze,
      { token: "uprobe", const: "SEC_UPROBE", kind: :sec_name, authority: :attach_kinds, witness: "uprobe", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Section name for uprobe attach." }.freeze,
      { token: "uretprobe", const: "SEC_URETPROBE", kind: :sec_name, authority: :attach_kinds, witness: "uretprobe", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Section name for uretprobe attach." }.freeze,
      { token: "usdt", const: "SEC_USDT", kind: :sec_name, authority: :attach_kinds, witness: "usdt", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Section name for USDT attach." }.freeze,
      { token: "perf_event", const: "SEC_PERF_EVENT", kind: :sec_name, authority: :attach_kinds, witness: "perf_event", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Section name for perf_event attach." }.freeze,
      { token: "kprobe.multi", const: "SEC_KPROBE_MULTI", kind: :sec_name, authority: :attach_kinds, witness: "kprobe_multi", map_type: nil, key_ctype: nil, value_ctype: nil, value_bytes: 0, alloc: nil, encoding: nil, encoding_measured: nil, note: "Section name for multi-symbol kprobe attach." }.freeze,
      { token: "spnl_param_", const: "PREFIX_RODATA_PARAM", kind: :rodata_prefix, authority: :codegen_c, witness: "126_runtime_param", map_type: nil, key_ctype: nil, value_ctype: "volatile const __s64", value_bytes: 8, alloc: nil, encoding: nil, encoding_measured: nil, note: "One symbol per declared runtime parameter. Frozen by BPF_MAP_FREEZE at load; the assignment must land in the gap between __open() and __load()." }.freeze,
      { token: "spnl_filter_", const: "PREFIX_RODATA_FILTER", kind: :rodata_prefix, authority: :codegen_c, witness: "129_common_filter", map_type: nil, key_ctype: nil, value_ctype: "volatile const __s64", value_bytes: 8, alloc: nil, encoding: "unset means 0 for pid/tid/cgroup_id but -1 for uid/gid, so that uid 0 stays selectable -- a shape-identical value with a different meaning", encoding_measured: "Round-tripped: one probe declaring `filter_by :pid, :uid` emits `spnl_filter_pid = 0` guarded by `!= 0` and `spnl_filter_uid = -1` guarded by `>= 0` -- same type, same width, different meaning. At run time, unset saw both a uid-1000 and a uid-0 workload (3/3), SPNL_FILTER_UID=0 saw only root (0/3), =1000 only the other (3/0). Had the sentinel been 0, unset would be indistinguishable from =0.", note: "One symbol per declared in-kernel common filter key." }.freeze,
    ].freeze

    def self.[](const_name)
      ENTRIES.find { |e| e[:const] == const_name.to_s } or
        raise KeyError, "loader contract has no #{const_name}; declared: " \
                        "#{ENTRIES.map { |e| e[:const] }.join(' ')}"
    end
  end
end
