// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 03_fib_recursion.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* ctx for fib — userspace fills before bpf_prog_test_run */
struct fib_ctx {
    __s64 n;
};

/* impl: fib : int  params: n: int */
static __noinline __s64 fib_inner(__s64 n)
{
    __s64 _if1 = 0;
    if (n < 2) {
        _if1 = n;
    } else {
        _if1 = fib_inner(n - 1) + fib_inner(n - 2);
    }
    return _if1;
}

/* entry wrapper: fib */
SEC("syscall")
int fib(struct fib_ctx *ctx)
{
    return (int)fib_inner(ctx->n);
}
