// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 04_class_with_ivars.rb
// ebpf-eligible methods: 3, classes touched: 1

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* class Counter ivar @count : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} counter_at_count SEC(".maps");

/* impl: Counter#initialize : void */
static __noinline void counter_initialize_inner(void)
{
    __u32 _k1 = 0;
    __s64 _v2 = 0;
    bpf_map_update_elem(&counter_at_count, &_k1, &_v2, BPF_ANY);
}

/* entry wrapper: Counter#initialize */
SEC("syscall")
int counter_initialize(void *ctx)
{
    counter_initialize_inner();
    return 0;
}

/* impl: Counter#incr : int */
static __noinline __s64 counter_incr_inner(void)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&counter_at_count, &_k1);
    __s64 _v3 = (_p2 ? *_p2 : 0) + (1);
    bpf_map_update_elem(&counter_at_count, &_k1, &_v3, BPF_ANY);
    return _v3;
}

/* entry wrapper: Counter#incr */
SEC("syscall")
int counter_incr(void *ctx)
{
    return (int)counter_incr_inner();
}

/* impl: Counter#value : int */
static __noinline __s64 counter_value_inner(void)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&counter_at_count, &_k1);
    return (_p2 ? *_p2 : 0);
}

/* entry wrapper: Counter#value */
SEC("syscall")
int counter_value(void *ctx)
{
    return (int)counter_value_inner();
}
