// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 102_parent_path_eq.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @denied : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_102_parent_path_eq_top_denied SEC(".maps");

/* ctx for fmod_ret__security_file_open — userspace fills before bpf_prog_test_run */
struct fmod_ret__security_file_open_ctx {
    __s64 file;
    __s64 ret;
};

/* impl: fmod_ret__security_file_open : int  params: file: int, ret: int */
static __noinline __s64 fmod_ret__security_file_open_inner(__s64 file, __s64 ret)
{
    struct task_struct *_pt1 = bpf_get_current_task_btf();
    char _pb2[24] = {0};
    __s64 _pr2 = bpf_d_path(&_pt1->real_parent->mm->exe_file->f_path, _pb2, sizeof(_pb2));
    __s64 _pm2 = (_pr2 == 17);
    _pm2 = _pm2 && (_pb2[0] == 47);
    _pm2 = _pm2 && (_pb2[1] == 117);
    _pm2 = _pm2 && (_pb2[2] == 115);
    _pm2 = _pm2 && (_pb2[3] == 114);
    _pm2 = _pm2 && (_pb2[4] == 47);
    _pm2 = _pm2 && (_pb2[5] == 98);
    _pm2 = _pm2 && (_pb2[6] == 105);
    _pm2 = _pm2 && (_pb2[7] == 110);
    _pm2 = _pm2 && (_pb2[8] == 47);
    _pm2 = _pm2 && (_pb2[9] == 115);
    _pm2 = _pm2 && (_pb2[10] == 112);
    _pm2 = _pm2 && (_pb2[11] == 110);
    _pm2 = _pm2 && (_pb2[12] == 108);
    _pm2 = _pm2 && (_pb2[13] == 98);
    _pm2 = _pm2 && (_pb2[14] == 97);
    _pm2 = _pm2 && (_pb2[15] == 100);
    char _pb3[24] = {0};
    __s64 _pr3 = bpf_d_path(&((struct file *)(unsigned long)(file))->f_path, _pb3, sizeof(_pb3));
    __s64 _pm3 = (_pr3 == 22);
    _pm3 = _pm3 && (_pb3[0] == 47);
    _pm3 = _pm3 && (_pb3[1] == 101);
    _pm3 = _pm3 && (_pb3[2] == 116);
    _pm3 = _pm3 && (_pb3[3] == 99);
    _pm3 = _pm3 && (_pb3[4] == 47);
    _pm3 = _pm3 && (_pb3[5] == 115);
    _pm3 = _pm3 && (_pb3[6] == 112);
    _pm3 = _pm3 && (_pb3[7] == 110);
    _pm3 = _pm3 && (_pb3[8] == 108);
    _pm3 = _pm3 && (_pb3[9] == 95);
    _pm3 = _pm3 && (_pb3[10] == 112);
    _pm3 = _pm3 && (_pb3[11] == 97);
    _pm3 = _pm3 && (_pb3[12] == 114);
    _pm3 = _pm3 && (_pb3[13] == 101);
    _pm3 = _pm3 && (_pb3[14] == 110);
    _pm3 = _pm3 && (_pb3[15] == 116);
    _pm3 = _pm3 && (_pb3[16] == 95);
    _pm3 = _pm3 && (_pb3[17] == 102);
    _pm3 = _pm3 && (_pb3[18] == 105);
    _pm3 = _pm3 && (_pb3[19] == 108);
    _pm3 = _pm3 && (_pb3[20] == 101);
    __s64 _if4 = 0;
    if ((_pm2) && (_pm3)) {
        __u32 _k5 = 0;
        __s64 *_p6 = bpf_map_lookup_elem(&u_102_parent_path_eq_top_denied, &_k5);
        __u32 _k7 = 0;
        __s64 _v8 = (_p6 ? *_p6 : 0) + 1;
        bpf_map_update_elem(&u_102_parent_path_eq_top_denied, &_k7, &_v8, BPF_ANY);
        _if4 = -1;
    } else {
        _if4 = ret;
    }
    return _if4;
}

/* entry wrapper: fmod_ret__security_file_open [fmod_ret -> fmod_ret/security_file_open] */
SEC("fmod_ret/security_file_open")
int fmod_ret__security_file_open(__u64 *ctx)
{
    (void)ctx;
    return (int)fmod_ret__security_file_open_inner((__s64)ctx[0], (__s64)ctx[1]);
}
