// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 104_emit_connect.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit connect-event channel === */
struct u_104_emit_connect_conn_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    __u32 daddr;
    __u16 dport;
    __u16 family;
    __s64 srtt_us;
    __u64 cgid;
    __u32 oldstate;
    __u64 daddr6_hi;
    __u64 daddr6_lo;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_104_emit_connect_conn_events SEC(".maps");

/* ctx for tracepoint__sock__inet_sock_set_state — userspace fills before bpf_prog_test_run */
struct tracepoint__sock__inet_sock_set_state_ctx {
    __s64 skaddr;
    __s64 daddr;
    __s64 dport;
    __s64 family;
    __s64 oldstate;
    __s64 newstate;
    __s64 daddr6_hi;
    __s64 daddr6_lo;
};

/* impl: tracepoint__sock__inet_sock_set_state : int  params: skaddr: int, daddr: int, dport: int, family: int, oldstate: int, newstate: int, daddr6_hi: int, daddr6_lo: int */
struct tracepoint__sock__inet_sock_set_state_args {
    __s64 p0;
    __s64 p1;
    __s64 p2;
    __s64 p3;
    __s64 p4;
    __s64 p5;
    __s64 p6;
    __s64 p7;
};
static __noinline __s64 tracepoint__sock__inet_sock_set_state_inner(struct tracepoint__sock__inet_sock_set_state_args *__a)
{
    __s64 skaddr = __a->p0;
    __s64 daddr = __a->p1;
    __s64 dport = __a->p2;
    __s64 family = __a->p3;
    __s64 oldstate = __a->p4;
    __s64 newstate = __a->p5;
    __s64 daddr6_hi = __a->p6;
    __s64 daddr6_lo = __a->p7;
    __s64 _if1 = 0;
    if (newstate == 1) {
        {
            struct u_104_emit_connect_conn_event *_ce2 = bpf_ringbuf_reserve(&u_104_emit_connect_conn_events, sizeof(*_ce2), 0);
            if (_ce2) {
                _ce2->hdr.type = SPNL_EVT_USER_BASE;
                _ce2->hdr.version = SPNL_EVENT_HDR_VERSION;
                _ce2->hdr.reserved = 0;
                _ce2->hdr.timestamp = bpf_ktime_get_ns();
                _ce2->pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
                bpf_get_current_comm(_ce2->comm, sizeof(_ce2->comm));
                _ce2->cgid = bpf_get_current_cgroup_id();   /* k8s pod attribution (default; owner overrides below) */
                _ce2->daddr = (__u32)(daddr);
                _ce2->dport = (__u16)(dport);
                _ce2->family = (__u16)(family);
                _ce2->srtt_us = (__s64)BPF_CORE_READ((struct tcp_sock *)(unsigned long)(skaddr), srtt_us);
                _ce2->oldstate = (__u32)(oldstate);   /* direction (active/passive) derived in userspace from the old TCP state */
                _ce2->daddr6_hi = (__u64)(daddr6_hi);   /* IPv6 daddr hi/lo (used when family==AF_INET6) */
                _ce2->daddr6_lo = (__u64)(daddr6_lo);
                bpf_ringbuf_submit(_ce2, 0);
            }
        }
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: tracepoint__sock__inet_sock_set_state [tracepoint -> tracepoint/sock/inet_sock_set_state] */
SEC("tracepoint/sock/inet_sock_set_state")
int tracepoint__sock__inet_sock_set_state(void *ctx)
{
    (void)ctx;
    struct tracepoint__sock__inet_sock_set_state_args __a = {};
    __a.p0 = (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->skaddr;
    __a.p1 = (__s64)(*(__u32 *)(((struct trace_event_raw_inet_sock_set_state *)ctx)->daddr));
    __a.p2 = (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->dport;
    __a.p3 = (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->family;
    __a.p4 = (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->oldstate;
    __a.p5 = (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->newstate;
    __a.p6 = (__s64)({ __u8 _d6[16] = {}; bpf_probe_read_kernel(_d6, 16, ((struct trace_event_raw_inet_sock_set_state *)ctx)->daddr_v6); *(__u64 *)_d6; });
    __a.p7 = (__s64)({ __u8 _d6[16] = {}; bpf_probe_read_kernel(_d6, 16, ((struct trace_event_raw_inet_sock_set_state *)ctx)->daddr_v6); *(__u64 *)(_d6 + 8); });
    (void)tracepoint__sock__inet_sock_set_state_inner(&__a);
    return 0;
}
