// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 105_emit_dns.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit DNS-event channel === */
struct u_105_emit_dns_dns_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    unsigned char raw[64];
    __u64 cgid;
    __u64 duration_ns;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_105_emit_dns_dns_events SEC(".maps");

/* ctx for kprobe__udp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__udp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 len;
};

/* impl: kprobe__udp_sendmsg : int  params: sk: int, msg: int, len: int */
static __noinline __s64 kprobe__udp_sendmsg_inner(__s64 sk, __s64 msg, __s64 len)
{
    __s64 _if1 = 0;
    if (((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_dport)) == 13568) {
        {
            struct u_105_emit_dns_dns_event *_de2 = bpf_ringbuf_reserve(&u_105_emit_dns_dns_events, sizeof(*_de2), 0);
            if (_de2) {
                _de2->hdr.type = SPNL_EVT_USER_BASE;
                _de2->hdr.version = SPNL_EVENT_HDR_VERSION;
                _de2->hdr.reserved = 0;
                _de2->hdr.timestamp = bpf_ktime_get_ns();
                _de2->pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
                bpf_get_current_comm(_de2->comm, sizeof(_de2->comm));
                _de2->cgid = bpf_get_current_cgroup_id();
                _de2->duration_ns = 0;
                __builtin_memset(_de2->raw, 0, sizeof(_de2->raw));
                void *_db2 = BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
                if (_db2) (void)bpf_probe_read_user(_de2->raw, sizeof(_de2->raw), _db2);
                bpf_ringbuf_submit(_de2, 0);
            }
        }
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: kprobe__udp_sendmsg [kprobe -> kprobe/udp_sendmsg] */
SEC("kprobe/udp_sendmsg")
int kprobe__udp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__udp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
