// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 105_emit_dns.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_105_emit_dns_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_105_emit_dns_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit DNS-event channel === */
struct u_105_emit_dns_dns_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    unsigned char raw[64];
    __u64 cgid;
    __u64 duration_ns;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_105_emit_dns_dns_events SEC(".maps");

/* ctx for kprobe__udp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__udp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 len;
};

/* impl: kprobe__udp_sendmsg : int  params: sk: int, msg: int, len: int */
static __noinline __s64 kprobe__udp_sendmsg_inner(__s64 sk, __s64 msg, __s64 len)
{
    __s64 _if1 = 0;
    if (((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_dport)) == 13568) {
        {
            struct u_105_emit_dns_dns_event *_de2 = bpf_ringbuf_reserve(&u_105_emit_dns_dns_events, sizeof(*_de2), 0);
            if (_de2) {
                _de2->hdr.type = SPNL_EVT_USER_BASE;
                _de2->hdr.version = SPNL_EVENT_HDR_VERSION;
                _de2->hdr.reserved = 0;
                _de2->hdr.timestamp = bpf_ktime_get_ns();
                _de2->pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
                bpf_get_current_comm(_de2->comm, sizeof(_de2->comm));
                _de2->cgid = bpf_get_current_cgroup_id();
                _de2->duration_ns = 0;
                __builtin_memset(_de2->raw, 0, sizeof(_de2->raw));
                void *_db2 = BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
                if (_db2) (void)bpf_probe_read_user(_de2->raw, sizeof(_de2->raw), _db2);
                bpf_ringbuf_submit(_de2, 0);
            } else spnl_lost_inc();   /* ring full -> account the dropped record */
        }
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: kprobe__udp_sendmsg [kprobe -> kprobe/udp_sendmsg] */
SEC("kprobe/udp_sendmsg")
int kprobe__udp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__udp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
