// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 107_emit_l7.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_endian.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit L7 send->recv correlation === */
struct u_107_emit_l7_req_state {
    __u64 start_ns;
    __u32 pid;
    char comm[16];
    __u64 cgid;
    __u32 outstanding;
    __u32 mux;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 65536);
    __type(key, __u64);
    __type(value, struct u_107_emit_l7_req_state);
} u_107_emit_l7_req_start SEC(".maps");

/* === per-unit L7 latency-event channel === */
struct u_107_emit_l7_l7_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    __u32 daddr;
    __u16 dport;
    __u16 family;
    __u64 start_ktime;
    __u64 duration_ns;
    __u64 cgid;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_107_emit_l7_l7_events SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* ctx for kprobe__tcp_cleanup_rbuf — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_cleanup_rbuf_ctx {
    __s64 sk;
    __s64 copied;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        __u64 _rsk1 = (__u64)(unsigned long)(sk);
        struct u_107_emit_l7_req_state *_rex1 = bpf_map_lookup_elem(&u_107_emit_l7_req_start, &_rsk1);
        if (_rex1) {
            _rex1->outstanding += 1;
            _rex1->mux = 1;
        } else {
            struct u_107_emit_l7_req_state _rst1 = {};
            _rst1.start_ns = bpf_ktime_get_ns();
            _rst1.pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
            bpf_get_current_comm(_rst1.comm, sizeof(_rst1.comm));
            _rst1.cgid = bpf_get_current_cgroup_id();
            _rst1.outstanding = 1;
            bpf_map_update_elem(&u_107_emit_l7_req_start, &_rsk1, &_rst1, BPF_ANY);
        }
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}

/* impl: kprobe__tcp_cleanup_rbuf : int  params: sk: int, copied: int */
static __noinline __s64 kprobe__tcp_cleanup_rbuf_inner(__s64 sk, __s64 copied)
{
    __s64 _if1 = 0;
    if (((__s64)(__s32)(copied)) > 0) {
        {
            __u64 _lsk2 = (__u64)(unsigned long)(sk);
            struct u_107_emit_l7_req_state *_lst2 = bpf_map_lookup_elem(&u_107_emit_l7_req_start, &_lsk2);
            if (_lst2) {
                if (_lst2->mux) {
                    if (_lst2->outstanding > 0) _lst2->outstanding -= 1;
                } else {
                    struct u_107_emit_l7_l7_event *_le2 = bpf_ringbuf_reserve(&u_107_emit_l7_l7_events, sizeof(*_le2), 0);
                    if (_le2) {
                        _le2->hdr.type = SPNL_EVT_USER_BASE;
                        _le2->hdr.version = SPNL_EVENT_HDR_VERSION;
                        _le2->hdr.reserved = 0;
                        _le2->hdr.timestamp = bpf_ktime_get_ns();
                        _le2->pid = _lst2->pid;
                        __builtin_memcpy(_le2->comm, _lst2->comm, sizeof(_le2->comm));
                        _le2->cgid = _lst2->cgid;
                        _le2->daddr = BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_daddr);
                        _le2->dport = bpf_ntohs(BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_dport));
                        _le2->family = (__u16)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_family);
                        _le2->start_ktime = _lst2->start_ns;
                        _le2->duration_ns = bpf_ktime_get_ns() - _lst2->start_ns;
                        bpf_ringbuf_submit(_le2, 0);
                    }
                    bpf_map_delete_elem(&u_107_emit_l7_req_start, &_lsk2);
                }
            }
        }
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_cleanup_rbuf [kprobe -> kprobe/tcp_cleanup_rbuf] */
SEC("kprobe/tcp_cleanup_rbuf")
int kprobe__tcp_cleanup_rbuf(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_cleanup_rbuf_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}
