// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 108_http_l7.rb
// ebpf-eligible methods: 3, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_endian.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_108_http_l7_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_108_http_l7_lost, &_z);
    if (_l) *_l += 1;
}

/* === msghdr -> user buffer, and the datagram's real destination === */

/* Every builtin that reads the bytes of a send or a receive starts from a
 * `struct msghdr *` and has to answer one question: where in user memory are
 * the bytes? All eleven of them used to answer it the same wrong way --
 *
 *     BPF_CORE_READ(msg, msg_iter.__ubuf_iovec.iov_base)
 *
 * -- which is only the answer for ITER_UBUF. `msg_iter` is a tagged union and
 * that member is one of the tags; for ITER_IOVEC the same 8 bytes hold `__iov`,
 * a pointer to the KERNEL's copy of the caller's iovec array (import_iovec
 * copies it in), so the read above hands a kernel address to
 * bpf_probe_read_user, which fails. Measured on a 2-iovec sendmsg: iov_base
 * reported 0xffff80008714bc88 while the payload the process actually sent was
 * at 0xffffe6f60fb8.
 *
 * A single-entry iovec array is NOT affected: the kernel normalises nr_segs==1
 * to ITER_UBUF, which is why writev-style sends of one segment worked and why
 * the bug survived every fixture -- all of them send one buffer.
 *
 * The resolution lives in ONE function on purpose. Eleven call sites each
 * carrying their own union discipline is exactly how a second, disagreeing
 * table gets written.
 */

/* raw_status when the helper below could not name a user buffer at all. Distinct
 * from any errno bpf_probe_read_user can return, so a reader never has to guess
 * which of the two happened. */
#define SPNL_RAW_NO_USER_BUFFER (-1)

static __noinline void *spnl_msg_ubuf(struct msghdr *msg)
{
    if (!msg) return (void *)0;
    /* The enumerator values are read out of the running kernel's BTF rather
     * than baked in, so a renumbered enum cannot silently reclassify a send. */
    __u8 it = BPF_CORE_READ(msg, msg_iter.iter_type);
    void *base = (void *)0;
    if (it == bpf_core_enum_value(enum iter_type, ITER_UBUF)) {
        base = BPF_CORE_READ(msg, msg_iter.__ubuf_iovec.iov_base);
    } else if (it == bpf_core_enum_value(enum iter_type, ITER_IOVEC)) {
        /* __iov always points at the iterator's CURRENT segment (iov_iter_advance
         * walks the pointer forward), so the first entry is the right one at any
         * position, not just at entry. */
        const struct iovec *iov = BPF_CORE_READ(msg, msg_iter.__iov);
        if (iov) base = BPF_CORE_READ(iov, iov_base);
    }
    /* ITER_BVEC / ITER_KVEC / ITER_XARRAY / ITER_DISCARD describe pages or kernel
     * memory: there is no user buffer to read, and saying so is the point --
     * returning a plausible pointer is what produced the zero-filled records. */
    if (!base) return (void *)0;
    /* iov_offset is how far into the current segment the iterator already is.
     * Zero at every capture point this codegen attaches to (all of them are
     * function entries), but reading it makes the contract "the bytes the
     * iterator is about to consume" true wherever the helper is called. */
    return (void *)((__u8 *)base + (unsigned long)BPF_CORE_READ(msg, msg_iter.iov_offset));
}

/* === per-unit HTTP L7 RED === */
static __always_inline int spnl_is_http_req(const unsigned char *h) {
    if (h[0]=='G'&&h[1]=='E'&&h[2]=='T'&&h[3]==' ') return 1;
    if (h[0]=='P'&&h[1]=='O'&&h[2]=='S'&&h[3]=='T') return 1;
    if (h[0]=='P'&&h[1]=='U'&&h[2]=='T'&&h[3]==' ') return 1;
    if (h[0]=='H'&&h[1]=='E'&&h[2]=='A'&&h[3]=='D') return 1;
    if (h[0]=='D'&&h[1]=='E'&&h[2]=='L'&&h[3]=='E') return 1;
    if (h[0]=='O'&&h[1]=='P'&&h[2]=='T'&&h[3]=='I') return 1;
    if (h[0]=='P'&&h[1]=='A'&&h[2]=='T'&&h[3]=='C') return 1;
    return 0;
}

struct u_108_http_l7_http_pending_st {
    __u64 start_ns;
    __u32 pid;
    char comm[16];
    unsigned char req[64];
    __u64 cgid;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 65536);
    __type(key, __u64);
    __type(value, struct u_108_http_l7_http_pending_st);
} u_108_http_l7_http_pending SEC(".maps");

struct u_108_http_l7_http_stash_st {
    __u64 sk;
    __u64 buf;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 4096);
    __type(key, __u32);
    __type(value, struct u_108_http_l7_http_stash_st);
} u_108_http_l7_http_recv_stash SEC(".maps");

struct u_108_http_l7_http_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    __u32 daddr;
    __u16 dport;
    __u16 family;
    __u64 start_ktime;
    __u64 duration_ns;
    unsigned char req[64];
    unsigned char resp[16];
    __u64 cgid;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_108_http_l7_http_events SEC(".maps");

/* Publishes the layout above to .BTF so a reader in another language does not
 * have to copy it by hand. A RINGBUF map declares no value type and the struct
 * is only ever a local pointer in a static function, so nothing else in this
 * object names it. Never loaded: .spnl_records is not a section libbpf maps. */
const struct u_108_http_l7_http_event *_spnl_rec_http_event SEC(".spnl_records");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* ctx for kprobe__tcp_recvmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_recvmsg_ctx {
    __s64 sk;
    __s64 msg;
};

/* ctx for kretprobe__tcp_recvmsg — userspace fills before bpf_prog_test_run */
struct kretprobe__tcp_recvmsg_ctx {
    __s64 ret;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        __u64 _hk1 = (__u64)(unsigned long)(sk);
        void *_hb1 = spnl_msg_ubuf((struct msghdr *)(unsigned long)(msg));
        if (_hb1 && !bpf_map_lookup_elem(&u_108_http_l7_http_pending, &_hk1)) {
            struct u_108_http_l7_http_pending_st _hp1 = {};
            if (bpf_probe_read_user(_hp1.req, sizeof(_hp1.req), _hb1) == 0 && spnl_is_http_req(_hp1.req)) {
                _hp1.start_ns = bpf_ktime_get_ns();
                _hp1.pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
                bpf_get_current_comm(_hp1.comm, sizeof(_hp1.comm));
                _hp1.cgid = bpf_get_current_cgroup_id();
                bpf_map_update_elem(&u_108_http_l7_http_pending, &_hk1, &_hp1, BPF_ANY);
            }
        }
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}

/* impl: kprobe__tcp_recvmsg : int  params: sk: int, msg: int */
static __noinline __s64 kprobe__tcp_recvmsg_inner(__s64 sk, __s64 msg)
{
    {
        __u32 _rt1 = (__u32)bpf_get_current_pid_tgid();
        struct u_108_http_l7_http_stash_st _rs1 = {};
        _rs1.sk = (__u64)(unsigned long)(sk);
        _rs1.buf = (__u64)(unsigned long)spnl_msg_ubuf((struct msghdr *)(unsigned long)(msg));
        bpf_map_update_elem(&u_108_http_l7_http_recv_stash, &_rt1, &_rs1, BPF_ANY);
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_recvmsg [kprobe -> kprobe/tcp_recvmsg] */
SEC("kprobe/tcp_recvmsg")
int kprobe__tcp_recvmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_recvmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}

/* impl: kretprobe__tcp_recvmsg : int  params: ret: int */
static __noinline __s64 kretprobe__tcp_recvmsg_inner(__s64 ret)
{
    {
        __u32 _et1 = (__u32)bpf_get_current_pid_tgid();
        struct u_108_http_l7_http_stash_st *_es1 = bpf_map_lookup_elem(&u_108_http_l7_http_recv_stash, &_et1);
        if (_es1) {
            __u64 _esk1 = _es1->sk, _ebuf1 = _es1->buf;
            bpf_map_delete_elem(&u_108_http_l7_http_recv_stash, &_et1);
            if (((__s64)(__s32)(ret)) > 0 && _ebuf1) {
                struct u_108_http_l7_http_pending_st *_ep1 = bpf_map_lookup_elem(&u_108_http_l7_http_pending, &_esk1);
                if (_ep1) {
                    unsigned char _resp1[16] = {};
                    if (bpf_probe_read_user(_resp1, sizeof(_resp1), (void *)(unsigned long)_ebuf1) == 0 &&
                        _resp1[0]=='H' && _resp1[1]=='T' && _resp1[2]=='T' && _resp1[3]=='P') {
                        struct u_108_http_l7_http_event *_he1 = bpf_ringbuf_reserve(&u_108_http_l7_http_events, sizeof(*_he1), 0);
                        if (_he1) {
                            _he1->hdr.type = SPNL_EVT_USER_BASE;
                            _he1->hdr.version = SPNL_EVENT_HDR_VERSION;
                            _he1->hdr.reserved = 0;
                            _he1->hdr.timestamp = bpf_ktime_get_ns();
                            _he1->pid = _ep1->pid;
                            __builtin_memcpy(_he1->comm, _ep1->comm, sizeof(_he1->comm));
                            _he1->cgid = _ep1->cgid;
                            _he1->daddr = BPF_CORE_READ((struct sock *)(unsigned long)_esk1, __sk_common.skc_daddr);
                            _he1->dport = bpf_ntohs(BPF_CORE_READ((struct sock *)(unsigned long)_esk1, __sk_common.skc_dport));
                            _he1->family = (__u16)BPF_CORE_READ((struct sock *)(unsigned long)_esk1, __sk_common.skc_family);
                            _he1->start_ktime = _ep1->start_ns;
                            _he1->duration_ns = bpf_ktime_get_ns() - _ep1->start_ns;
                            __builtin_memcpy(_he1->req, _ep1->req, sizeof(_he1->req));
                            __builtin_memcpy(_he1->resp, _resp1, sizeof(_he1->resp));
                            bpf_ringbuf_submit(_he1, 0);
                        } else spnl_lost_inc();   /* ring full -> account the dropped record */
                        bpf_map_delete_elem(&u_108_http_l7_http_pending, &_esk1);
                    }
                }
            }
        }
    }
    return 0;
}

/* entry wrapper: kretprobe__tcp_recvmsg [kretprobe -> kretprobe/tcp_recvmsg] */
SEC("kretprobe/tcp_recvmsg")
int kretprobe__tcp_recvmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kretprobe__tcp_recvmsg_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
