// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 108_http_l7.rb
// ebpf-eligible methods: 3, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_endian.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit HTTP L7 RED === */
static __always_inline int spnl_is_http_req(const unsigned char *h) {
    if (h[0]=='G'&&h[1]=='E'&&h[2]=='T'&&h[3]==' ') return 1;
    if (h[0]=='P'&&h[1]=='O'&&h[2]=='S'&&h[3]=='T') return 1;
    if (h[0]=='P'&&h[1]=='U'&&h[2]=='T'&&h[3]==' ') return 1;
    if (h[0]=='H'&&h[1]=='E'&&h[2]=='A'&&h[3]=='D') return 1;
    if (h[0]=='D'&&h[1]=='E'&&h[2]=='L'&&h[3]=='E') return 1;
    if (h[0]=='O'&&h[1]=='P'&&h[2]=='T'&&h[3]=='I') return 1;
    if (h[0]=='P'&&h[1]=='A'&&h[2]=='T'&&h[3]=='C') return 1;
    return 0;
}

struct u_108_http_l7_http_pending_st {
    __u64 start_ns;
    __u32 pid;
    char comm[16];
    unsigned char req[64];
    __u64 cgid;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 65536);
    __type(key, __u64);
    __type(value, struct u_108_http_l7_http_pending_st);
} u_108_http_l7_http_pending SEC(".maps");

struct u_108_http_l7_http_stash_st {
    __u64 sk;
    __u64 buf;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 4096);
    __type(key, __u32);
    __type(value, struct u_108_http_l7_http_stash_st);
} u_108_http_l7_http_recv_stash SEC(".maps");

struct u_108_http_l7_http_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    __u32 daddr;
    __u16 dport;
    __u16 family;
    __u64 start_ktime;
    __u64 duration_ns;
    unsigned char req[64];
    unsigned char resp[16];
    __u64 cgid;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_108_http_l7_http_events SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* ctx for kprobe__tcp_recvmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_recvmsg_ctx {
    __s64 sk;
    __s64 msg;
};

/* ctx for kretprobe__tcp_recvmsg — userspace fills before bpf_prog_test_run */
struct kretprobe__tcp_recvmsg_ctx {
    __s64 ret;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        __u64 _hk1 = (__u64)(unsigned long)(sk);
        void *_hb1 = BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
        if (_hb1 && !bpf_map_lookup_elem(&u_108_http_l7_http_pending, &_hk1)) {
            struct u_108_http_l7_http_pending_st _hp1 = {};
            if (bpf_probe_read_user(_hp1.req, sizeof(_hp1.req), _hb1) == 0 && spnl_is_http_req(_hp1.req)) {
                _hp1.start_ns = bpf_ktime_get_ns();
                _hp1.pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
                bpf_get_current_comm(_hp1.comm, sizeof(_hp1.comm));
                _hp1.cgid = bpf_get_current_cgroup_id();
                bpf_map_update_elem(&u_108_http_l7_http_pending, &_hk1, &_hp1, BPF_ANY);
            }
        }
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}

/* impl: kprobe__tcp_recvmsg : int  params: sk: int, msg: int */
static __noinline __s64 kprobe__tcp_recvmsg_inner(__s64 sk, __s64 msg)
{
    {
        __u32 _rt1 = (__u32)bpf_get_current_pid_tgid();
        struct u_108_http_l7_http_stash_st _rs1 = {};
        _rs1.sk = (__u64)(unsigned long)(sk);
        _rs1.buf = (__u64)(unsigned long)BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
        bpf_map_update_elem(&u_108_http_l7_http_recv_stash, &_rt1, &_rs1, BPF_ANY);
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_recvmsg [kprobe -> kprobe/tcp_recvmsg] */
SEC("kprobe/tcp_recvmsg")
int kprobe__tcp_recvmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_recvmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}

/* impl: kretprobe__tcp_recvmsg : int  params: ret: int */
static __noinline __s64 kretprobe__tcp_recvmsg_inner(__s64 ret)
{
    {
        __u32 _et1 = (__u32)bpf_get_current_pid_tgid();
        struct u_108_http_l7_http_stash_st *_es1 = bpf_map_lookup_elem(&u_108_http_l7_http_recv_stash, &_et1);
        if (_es1) {
            __u64 _esk1 = _es1->sk, _ebuf1 = _es1->buf;
            bpf_map_delete_elem(&u_108_http_l7_http_recv_stash, &_et1);
            if (((__s64)(__s32)(ret)) > 0 && _ebuf1) {
                struct u_108_http_l7_http_pending_st *_ep1 = bpf_map_lookup_elem(&u_108_http_l7_http_pending, &_esk1);
                if (_ep1) {
                    unsigned char _resp1[16] = {};
                    if (bpf_probe_read_user(_resp1, sizeof(_resp1), (void *)(unsigned long)_ebuf1) == 0 &&
                        _resp1[0]=='H' && _resp1[1]=='T' && _resp1[2]=='T' && _resp1[3]=='P') {
                        struct u_108_http_l7_http_event *_he1 = bpf_ringbuf_reserve(&u_108_http_l7_http_events, sizeof(*_he1), 0);
                        if (_he1) {
                            _he1->hdr.type = SPNL_EVT_USER_BASE;
                            _he1->hdr.version = SPNL_EVENT_HDR_VERSION;
                            _he1->hdr.reserved = 0;
                            _he1->hdr.timestamp = bpf_ktime_get_ns();
                            _he1->pid = _ep1->pid;
                            __builtin_memcpy(_he1->comm, _ep1->comm, sizeof(_he1->comm));
                            _he1->cgid = _ep1->cgid;
                            _he1->daddr = BPF_CORE_READ((struct sock *)(unsigned long)_esk1, __sk_common.skc_daddr);
                            _he1->dport = bpf_ntohs(BPF_CORE_READ((struct sock *)(unsigned long)_esk1, __sk_common.skc_dport));
                            _he1->family = (__u16)BPF_CORE_READ((struct sock *)(unsigned long)_esk1, __sk_common.skc_family);
                            _he1->start_ktime = _ep1->start_ns;
                            _he1->duration_ns = bpf_ktime_get_ns() - _ep1->start_ns;
                            __builtin_memcpy(_he1->req, _ep1->req, sizeof(_he1->req));
                            __builtin_memcpy(_he1->resp, _resp1, sizeof(_he1->resp));
                            bpf_ringbuf_submit(_he1, 0);
                        }
                        bpf_map_delete_elem(&u_108_http_l7_http_pending, &_esk1);
                    }
                }
            }
        }
    }
    return 0;
}

/* entry wrapper: kretprobe__tcp_recvmsg [kretprobe -> kretprobe/tcp_recvmsg] */
SEC("kretprobe/tcp_recvmsg")
int kretprobe__tcp_recvmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kretprobe__tcp_recvmsg_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
