// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 10_polymorphic.rb
// ebpf-eligible methods: 5, classes touched: 3

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* class Square ivar @side : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} square_at_side SEC(".maps");

/* class Triangle ivar @b : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} triangle_at_b SEC(".maps");

/* class Triangle ivar @h : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} triangle_at_h SEC(".maps");

/* ctx for Square#initialize — userspace fills before bpf_prog_test_run */
struct square_initialize_ctx {
    __s64 s;
};

/* ctx for Triangle#initialize — userspace fills before bpf_prog_test_run */
struct triangle_initialize_ctx {
    __s64 b;
    __s64 h;
};

/* impl: Shape#area : int */
static __noinline __s64 shape_area_inner(void)
{
    return 0;
}

/* entry wrapper: Shape#area */
SEC("syscall")
int shape_area(void *ctx)
{
    return (int)shape_area_inner();
}

/* impl: Square#initialize : void  params: s: int */
static __noinline void square_initialize_inner(__s64 s)
{
    __u32 _k1 = 0;
    __s64 _v2 = s;
    bpf_map_update_elem(&square_at_side, &_k1, &_v2, BPF_ANY);
}

/* entry wrapper: Square#initialize */
SEC("syscall")
int square_initialize(struct square_initialize_ctx *ctx)
{
    square_initialize_inner(ctx->s);
    return 0;
}

/* impl: Square#area : int */
static __noinline __s64 square_area_inner(void)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&square_at_side, &_k1);
    __u32 _k3 = 0;
    __s64 *_p4 = bpf_map_lookup_elem(&square_at_side, &_k3);
    return (_p2 ? *_p2 : 0) * (_p4 ? *_p4 : 0);
}

/* entry wrapper: Square#area */
SEC("syscall")
int square_area(void *ctx)
{
    return (int)square_area_inner();
}

/* impl: Triangle#initialize : void  params: b: int, h: int */
static __noinline void triangle_initialize_inner(__s64 b, __s64 h)
{
    __u32 _k1 = 0;
    __s64 _v2 = b;
    bpf_map_update_elem(&triangle_at_b, &_k1, &_v2, BPF_ANY);
    __u32 _k3 = 0;
    __s64 _v4 = h;
    bpf_map_update_elem(&triangle_at_h, &_k3, &_v4, BPF_ANY);
}

/* entry wrapper: Triangle#initialize */
SEC("syscall")
int triangle_initialize(struct triangle_initialize_ctx *ctx)
{
    triangle_initialize_inner(ctx->b, ctx->h);
    return 0;
}

/* impl: Triangle#area : int */
static __noinline __s64 triangle_area_inner(void)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&triangle_at_b, &_k1);
    __u32 _k3 = 0;
    __s64 *_p4 = bpf_map_lookup_elem(&triangle_at_h, &_k3);
    return (_p2 ? *_p2 : 0) * (_p4 ? *_p4 : 0) / 2;
}

/* entry wrapper: Triangle#area */
SEC("syscall")
int triangle_area(void *ctx)
{
    return (int)triangle_area_inner();
}
