// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 110_offcpu_l7.rb
// ebpf-eligible methods: 4, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_110_offcpu_l7_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_110_offcpu_l7_lost, &_z);
    if (_l) *_l += 1;
}

/* === msghdr -> user buffer, and the datagram's real destination === */

/* Every builtin that reads the bytes of a send or a receive starts from a
 * `struct msghdr *` and has to answer one question: where in user memory are
 * the bytes? All eleven of them used to answer it the same wrong way --
 *
 *     BPF_CORE_READ(msg, msg_iter.__ubuf_iovec.iov_base)
 *
 * -- which is only the answer for ITER_UBUF. `msg_iter` is a tagged union and
 * that member is one of the tags; for ITER_IOVEC the same 8 bytes hold `__iov`,
 * a pointer to the KERNEL's copy of the caller's iovec array (import_iovec
 * copies it in), so the read above hands a kernel address to
 * bpf_probe_read_user, which fails. Measured on a 2-iovec sendmsg: iov_base
 * reported 0xffff80008714bc88 while the payload the process actually sent was
 * at 0xffffe6f60fb8.
 *
 * A single-entry iovec array is NOT affected: the kernel normalises nr_segs==1
 * to ITER_UBUF, which is why writev-style sends of one segment worked and why
 * the bug survived every fixture -- all of them send one buffer.
 *
 * The resolution lives in ONE function on purpose. Eleven call sites each
 * carrying their own union discipline is exactly how a second, disagreeing
 * table gets written.
 */

/* raw_status when the helper below could not name a user buffer at all. Distinct
 * from any errno bpf_probe_read_user can return, so a reader never has to guess
 * which of the two happened. */
#define SPNL_RAW_NO_USER_BUFFER (-1)

static __noinline void *spnl_msg_ubuf(struct msghdr *msg)
{
    if (!msg) return (void *)0;
    /* The enumerator values are read out of the running kernel's BTF rather
     * than baked in, so a renumbered enum cannot silently reclassify a send. */
    __u8 it = BPF_CORE_READ(msg, msg_iter.iter_type);
    void *base = (void *)0;
    if (it == bpf_core_enum_value(enum iter_type, ITER_UBUF)) {
        base = BPF_CORE_READ(msg, msg_iter.__ubuf_iovec.iov_base);
    } else if (it == bpf_core_enum_value(enum iter_type, ITER_IOVEC)) {
        /* __iov always points at the iterator's CURRENT segment (iov_iter_advance
         * walks the pointer forward), so the first entry is the right one at any
         * position, not just at entry. */
        const struct iovec *iov = BPF_CORE_READ(msg, msg_iter.__iov);
        if (iov) base = BPF_CORE_READ(iov, iov_base);
    }
    /* ITER_BVEC / ITER_KVEC / ITER_XARRAY / ITER_DISCARD describe pages or kernel
     * memory: there is no user buffer to read, and saying so is the point --
     * returning a plausible pointer is what produced the zero-filled records. */
    if (!base) return (void *)0;
    /* iov_offset is how far into the current segment the iterator already is.
     * Zero at every capture point this codegen attaches to (all of them are
     * function entries), but reading it makes the contract "the bytes the
     * iterator is about to consume" true wherever the helper is called. */
    return (void *)((__u8 *)base + (unsigned long)BPF_CORE_READ(msg, msg_iter.iov_offset));
}

/* === per-unit off-CPU L7 correlation === */
static __always_inline int spnl_is_http_req(const unsigned char *h) {
    if (h[0]=='G'&&h[1]=='E'&&h[2]=='T'&&h[3]==' ') return 1;
    if (h[0]=='P'&&h[1]=='O'&&h[2]=='S'&&h[3]=='T') return 1;
    if (h[0]=='P'&&h[1]=='U'&&h[2]=='T'&&h[3]==' ') return 1;
    if (h[0]=='H'&&h[1]=='E'&&h[2]=='A'&&h[3]=='D') return 1;
    if (h[0]=='D'&&h[1]=='E'&&h[2]=='L'&&h[3]=='E') return 1;
    if (h[0]=='O'&&h[1]=='P'&&h[2]=='T'&&h[3]=='I') return 1;
    if (h[0]=='P'&&h[1]=='A'&&h[2]=='T'&&h[3]=='C') return 1;
    return 0;
}

struct u_110_offcpu_l7_offcpu_stash_st {
    __u64 buf;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 4096);
    __type(key, __u32);
    __type(value, struct u_110_offcpu_l7_offcpu_stash_st);
} u_110_offcpu_l7_offcpu_stash SEC(".maps");

struct u_110_offcpu_l7_offcpu_win {
    __u64 start_ns;
    __u64 offcpu_ns;
    __u64 sleep_ts;
    __s32 wait_stack;
    unsigned char req[64];
    unsigned char hdr_ext[128];
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 4096);
    __type(key, __u32);
    __type(value, struct u_110_offcpu_l7_offcpu_win);
} u_110_offcpu_l7_offcpu_win SEC(".maps");

struct u_110_offcpu_l7_offcpu_event {
    struct spnl_event_hdr hdr;
    __u32 pid;
    char comm[16];
    __u64 duration_ns;
    __u64 offcpu_ns;
    __s32 wait_stack;
    unsigned char req[64];
    unsigned char resp[16];
    __u64 cgid;
    __u64 start_ktime;
    unsigned char hdr_ext[128];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_110_offcpu_l7_offcpu_events SEC(".maps");

/* per-unit stack-trace map (16384 unique stacks * 127 frames each).
 * stack_id() returns the kernel stack id, user_stack_id() returns the
 * userspace one. Host code reads the map by stack id to get the PCs. */
struct {
    __uint(type, BPF_MAP_TYPE_STACK_TRACE);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, 127 * sizeof(__u64));
    __uint(max_entries, 16384);
} bpf_stacks SEC(".maps");

/* ctx for kprobe__tcp_recvmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_recvmsg_ctx {
    __s64 sk;
    __s64 msg;
};

/* ctx for kretprobe__tcp_recvmsg — userspace fills before bpf_prog_test_run */
struct kretprobe__tcp_recvmsg_ctx {
    __s64 ret;
};

/* ctx for tracepoint__sched__sched_switch — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_switch_ctx {
    __s64 prev_pid;
    __s64 prev_state;
    __s64 next_pid;
};

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
};

/* impl: kprobe__tcp_recvmsg : int  params: sk: int, msg: int */
static __noinline __s64 kprobe__tcp_recvmsg_inner(struct pt_regs *ctx, __s64 sk, __s64 msg)
{
    {
        __u32 _ot1 = (__u32)bpf_get_current_pid_tgid();
        struct u_110_offcpu_l7_offcpu_stash_st _os1 = {};
        _os1.buf = (__u64)(unsigned long)spnl_msg_ubuf((struct msghdr *)(unsigned long)(msg));
        bpf_map_update_elem(&u_110_offcpu_l7_offcpu_stash, &_ot1, &_os1, BPF_ANY);
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_recvmsg [kprobe -> kprobe/tcp_recvmsg] */
SEC("kprobe/tcp_recvmsg")
int kprobe__tcp_recvmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_recvmsg_inner(ctx, (__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}

/* impl: kretprobe__tcp_recvmsg : int  params: ret: int */
static __noinline __s64 kretprobe__tcp_recvmsg_inner(struct pt_regs *ctx, __s64 ret)
{
    {
        __u32 _ot1 = (__u32)bpf_get_current_pid_tgid();
        struct u_110_offcpu_l7_offcpu_stash_st *_os1 = bpf_map_lookup_elem(&u_110_offcpu_l7_offcpu_stash, &_ot1);
        if (_os1) {
            __u64 _obuf1 = _os1->buf;
            bpf_map_delete_elem(&u_110_offcpu_l7_offcpu_stash, &_ot1);
            if (((__s64)(__s32)(ret)) > 0 && _obuf1) {
                struct u_110_offcpu_l7_offcpu_win _ow1 = {};
                if (bpf_probe_read_user(_ow1.req, sizeof(_ow1.req), (void *)(unsigned long)_obuf1) == 0 && spnl_is_http_req(_ow1.req)) {
                    bpf_probe_read_user(_ow1.hdr_ext, sizeof(_ow1.hdr_ext), (void *)(unsigned long)_obuf1);
                    _ow1.start_ns = bpf_ktime_get_ns();
                    _ow1.wait_stack = -1;
                    bpf_map_update_elem(&u_110_offcpu_l7_offcpu_win, &_ot1, &_ow1, BPF_ANY);
                }
            }
        }
    }
    return 0;
}

/* entry wrapper: kretprobe__tcp_recvmsg [kretprobe -> kretprobe/tcp_recvmsg] */
SEC("kretprobe/tcp_recvmsg")
int kretprobe__tcp_recvmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kretprobe__tcp_recvmsg_inner(ctx, (__s64)PT_REGS_PARM1(ctx));
    return 0;
}

/* impl: tracepoint__sched__sched_switch : int  params: prev_pid: int, prev_state: int, next_pid: int */
static __noinline __s64 tracepoint__sched__sched_switch_inner(void *ctx, __s64 prev_pid, __s64 prev_state, __s64 next_pid)
{
    {
        __u64 _onow1 = bpf_ktime_get_ns();
        __u32 _oprev1 = (__u32)(prev_pid);
        __u32 _onext1 = (__u32)(next_pid);
        struct u_110_offcpu_l7_offcpu_win *_opw1 = bpf_map_lookup_elem(&u_110_offcpu_l7_offcpu_win, &_oprev1);
        if (_opw1 && ((__s64)(prev_state)) != 0) {
            _opw1->sleep_ts = _onow1;
            _opw1->wait_stack = bpf_get_stackid(ctx, &bpf_stacks, 0);
        }
        struct u_110_offcpu_l7_offcpu_win *_onw1 = bpf_map_lookup_elem(&u_110_offcpu_l7_offcpu_win, &_onext1);
        if (_onw1 && _onw1->sleep_ts) {
            _onw1->offcpu_ns += _onow1 - _onw1->sleep_ts;
            _onw1->sleep_ts = 0;
        }
    }
    return 0;
}

/* entry wrapper: tracepoint__sched__sched_switch [tracepoint -> tracepoint/sched/sched_switch] */
SEC("tracepoint/sched/sched_switch")
int tracepoint__sched__sched_switch(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_switch_inner(ctx, (__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_pid, (__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_state, (__s64)((struct trace_event_raw_sched_switch *)ctx)->next_pid);
    return 0;
}

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(struct pt_regs *ctx, __s64 sk, __s64 msg)
{
    {
        __u32 _ot1 = (__u32)bpf_get_current_pid_tgid();
        struct u_110_offcpu_l7_offcpu_win *_ow1 = bpf_map_lookup_elem(&u_110_offcpu_l7_offcpu_win, &_ot1);
        if (_ow1) {
            void *_obuf1 = spnl_msg_ubuf((struct msghdr *)(unsigned long)(msg));
            unsigned char _oresp1[16] = {};
            if (_obuf1 && bpf_probe_read_user(_oresp1, sizeof(_oresp1), _obuf1) == 0 &&
                _oresp1[0]=='H' && _oresp1[1]=='T' && _oresp1[2]=='T' && _oresp1[3]=='P') {
                struct u_110_offcpu_l7_offcpu_event *_oe1 = bpf_ringbuf_reserve(&u_110_offcpu_l7_offcpu_events, sizeof(*_oe1), 0);
                if (_oe1) {
                    _oe1->hdr.type = SPNL_EVT_USER_BASE;
                    _oe1->hdr.version = SPNL_EVENT_HDR_VERSION;
                    _oe1->hdr.reserved = 0;
                    _oe1->hdr.timestamp = bpf_ktime_get_ns();
                    _oe1->pid = (__u32)(bpf_get_current_pid_tgid() >> 32);
                    bpf_get_current_comm(_oe1->comm, sizeof(_oe1->comm));
                    _oe1->cgid = bpf_get_current_cgroup_id();
                    _oe1->duration_ns = bpf_ktime_get_ns() - _ow1->start_ns;
                    _oe1->start_ktime = _ow1->start_ns;
                    __builtin_memcpy(_oe1->hdr_ext, _ow1->hdr_ext, sizeof(_oe1->hdr_ext));
                    _oe1->offcpu_ns = _ow1->offcpu_ns;
                    _oe1->wait_stack = _ow1->wait_stack;
                    __builtin_memcpy(_oe1->req, _ow1->req, sizeof(_oe1->req));
                    __builtin_memcpy(_oe1->resp, _oresp1, sizeof(_oe1->resp));
                    bpf_ringbuf_submit(_oe1, 0);
                } else spnl_lost_inc();   /* ring full -> account the dropped record */
                bpf_map_delete_elem(&u_110_offcpu_l7_offcpu_win, &_ot1);
            }
        }
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner(ctx, (__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}
