// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 114_tcp_cc_reno.rb
// ebpf-eligible methods: 5, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* ctx for tcp_cc__init — userspace fills before bpf_prog_test_run */
struct tcp_cc__init_ctx {
    __s64 sk;
};

/* ctx for tcp_cc__ssthresh — userspace fills before bpf_prog_test_run */
struct tcp_cc__ssthresh_ctx {
    __s64 sk;
};

/* ctx for tcp_cc__undo_cwnd — userspace fills before bpf_prog_test_run */
struct tcp_cc__undo_cwnd_ctx {
    __s64 sk;
};

/* ctx for tcp_cc__cong_avoid — userspace fills before bpf_prog_test_run */
struct tcp_cc__cong_avoid_ctx {
    __s64 sk;
    __s64 ack;
    __s64 acked;
};

/* ctx for tcp_cc__set_state — userspace fills before bpf_prog_test_run */
struct tcp_cc__set_state_ctx {
    __s64 sk;
    __s64 new_state;
};

/* impl: tcp_cc__init */
static __noinline __s64 tcp_cc__init_inner(__s64 sk)
{
    return 0;
}

/* entry: SEC("struct_ops/init") for tcp_congestion_ops */
SEC("struct_ops/init")
void BPF_PROG(tcp_cc__init, struct sock *sk)
{
    (void)tcp_cc__init_inner((__s64)(unsigned long)sk);
}

/* impl: tcp_cc__ssthresh */
static __noinline __s64 tcp_cc__ssthresh_inner(__s64 sk)
{
    __s64 half = 0;
    half = ((__s64)((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd) / 2;
    __s64 _if1 = 0;
    if (half < 2) {
        _if1 = 2;
    } else {
        _if1 = half;
    }
    return _if1;
}

/* entry: SEC("struct_ops/ssthresh") for tcp_congestion_ops */
SEC("struct_ops/ssthresh")
__u32 BPF_PROG(tcp_cc__ssthresh, struct sock *sk)
{
    return (__u32)tcp_cc__ssthresh_inner((__s64)(unsigned long)sk);
}

/* impl: tcp_cc__undo_cwnd */
static __noinline __s64 tcp_cc__undo_cwnd_inner(__s64 sk)
{
    return ((__s64)((struct tcp_sock *)(unsigned long)(sk))->prior_cwnd);
}

/* entry: SEC("struct_ops/undo_cwnd") for tcp_congestion_ops */
SEC("struct_ops/undo_cwnd")
__u32 BPF_PROG(tcp_cc__undo_cwnd, struct sock *sk)
{
    return (__u32)tcp_cc__undo_cwnd_inner((__s64)(unsigned long)sk);
}

/* impl: tcp_cc__cong_avoid */
static __noinline __s64 tcp_cc__cong_avoid_inner(__s64 sk, __s64 ack, __s64 acked)
{
    __s64 cnt = 0;
    __s64 _if1 = 0;
    if (((__s64)((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd) < ((__s64)((struct tcp_sock *)(unsigned long)(sk))->snd_ssthresh)) {
        ((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd += (__u32)(acked);
        _if1 = 0;
    } else {
        cnt = ((__s64)((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd_cnt) + acked;
        __s64 _if2 = 0;
        if (cnt >= ((__s64)((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd)) {
            ((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd += (__u32)(1);
            ((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd_cnt = (__u32)(0);
            _if2 = 0;
        } else {
            ((struct tcp_sock *)(unsigned long)(sk))->snd_cwnd_cnt = (__u32)(cnt);
            _if2 = 0;
        }
        _if1 = _if2;
    }
    return _if1;
}

/* entry: SEC("struct_ops/cong_avoid") for tcp_congestion_ops */
SEC("struct_ops/cong_avoid")
void BPF_PROG(tcp_cc__cong_avoid, struct sock *sk, __u32 ack, __u32 acked)
{
    (void)tcp_cc__cong_avoid_inner((__s64)(unsigned long)sk, (__s64)(unsigned long)ack, (__s64)(unsigned long)acked);
}

/* impl: tcp_cc__set_state */
static __noinline __s64 tcp_cc__set_state_inner(__s64 sk, __s64 new_state)
{
    return 0;
}

/* entry: SEC("struct_ops/set_state") for tcp_congestion_ops */
SEC("struct_ops/set_state")
void BPF_PROG(tcp_cc__set_state, struct sock *sk, __u8 new_state)
{
    (void)tcp_cc__set_state_inner((__s64)(unsigned long)sk, (__s64)(unsigned long)new_state);
}

/* struct_ops registration for tcp_congestion_ops. */
SEC(".struct_ops")
struct tcp_congestion_ops spnl_tcp_cc_ops = {
    .init = (void *)tcp_cc__init,
    .ssthresh = (void *)tcp_cc__ssthresh,
    .undo_cwnd = (void *)tcp_cc__undo_cwnd,
    .cong_avoid = (void *)tcp_cc__cong_avoid,
    .set_state = (void *)tcp_cc__set_state,
    .name = "spnl_cc",
};
