// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 115_path_starts_with.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @allowed : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_115_path_starts_with_top_allowed SEC(".maps");

/* top-level ivar @denied : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_115_path_starts_with_top_denied SEC(".maps");

/* === per-unit d_path scratch buffer (path_starts_with) === */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, char[4096]);
} u_115_path_starts_with_path_scratch SEC(".maps");

/* ctx for fmod_ret__security_file_open — userspace fills before bpf_prog_test_run */
struct fmod_ret__security_file_open_ctx {
    __s64 file;
    __s64 ret;
};

/* impl: fmod_ret__security_file_open : int  params: file: int, ret: int */
static __noinline __s64 fmod_ret__security_file_open_inner(__s64 file, __s64 ret)
{
    __s64 _pm1 = 0;
    __u32 _pz1 = 0;
    char *_pbuf1 = bpf_map_lookup_elem(&u_115_path_starts_with_path_scratch, &_pz1);
    if (_pbuf1) {
        __s64 _pr1 = bpf_d_path(&((struct file *)(unsigned long)(file))->f_path, _pbuf1, 4096);
        _pm1 = (_pr1 >= 16);
        _pm1 = _pm1 && (_pbuf1[0] == 47);
        _pm1 = _pm1 && (_pbuf1[1] == 101);
        _pm1 = _pm1 && (_pbuf1[2] == 116);
        _pm1 = _pm1 && (_pbuf1[3] == 99);
        _pm1 = _pm1 && (_pbuf1[4] == 47);
        _pm1 = _pm1 && (_pbuf1[5] == 115);
        _pm1 = _pm1 && (_pbuf1[6] == 112);
        _pm1 = _pm1 && (_pbuf1[7] == 110);
        _pm1 = _pm1 && (_pbuf1[8] == 108);
        _pm1 = _pm1 && (_pbuf1[9] == 95);
        _pm1 = _pm1 && (_pbuf1[10] == 97);
        _pm1 = _pm1 && (_pbuf1[11] == 114);
        _pm1 = _pm1 && (_pbuf1[12] == 101);
        _pm1 = _pm1 && (_pbuf1[13] == 97);
        _pm1 = _pm1 && (_pbuf1[14] == 47);
    }
    __s64 _if2 = 0;
    if ((_pm1)) {
        __u32 _k3 = 0;
        __s64 *_p4 = bpf_map_lookup_elem(&u_115_path_starts_with_top_denied, &_k3);
        __u32 _k5 = 0;
        __s64 _v6 = (_p4 ? *_p4 : 0) + 1;
        bpf_map_update_elem(&u_115_path_starts_with_top_denied, &_k5, &_v6, BPF_ANY);
        _if2 = -1;
    } else {
        __u32 _k7 = 0;
        __s64 *_p8 = bpf_map_lookup_elem(&u_115_path_starts_with_top_allowed, &_k7);
        __u32 _k9 = 0;
        __s64 _v10 = (_p8 ? *_p8 : 0) + 1;
        bpf_map_update_elem(&u_115_path_starts_with_top_allowed, &_k9, &_v10, BPF_ANY);
        _if2 = ret;
    }
    return _if2;
}

/* entry wrapper: fmod_ret__security_file_open [fmod_ret -> fmod_ret/security_file_open] */
SEC("fmod_ret/security_file_open")
int fmod_ret__security_file_open(__u64 *ctx)
{
    (void)ctx;
    return (int)fmod_ret__security_file_open_inner((__s64)ctx[0], (__s64)ctx[1]);
}
