// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 117_emit_tcp_payload.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit string-event channel === */
struct u_117_emit_tcp_payload_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_117_emit_tcp_payload_str_events SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        struct u_117_emit_tcp_payload_str_event *_tp1 = bpf_ringbuf_reserve(&u_117_emit_tcp_payload_str_events, sizeof(*_tp1), 0);
        if (_tp1) {
            _tp1->hdr.type = SPNL_EVT_USER_BASE;
            _tp1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _tp1->hdr.reserved = 0;
            _tp1->hdr.timestamp = bpf_ktime_get_ns();
            __builtin_memset(_tp1->str, 0, sizeof(_tp1->str));
            void *_tpb1 = BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
            if (_tpb1) (void)bpf_probe_read_user(_tp1->str, 128, _tpb1);
            bpf_ringbuf_submit(_tp1, 0);
        }
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
