// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 118_emit_tcp_stream.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_118_emit_tcp_stream_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_118_emit_tcp_stream_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit sock-keyed L7 stream channel === */
struct u_118_emit_tcp_stream_l7stream_event {
    struct spnl_event_hdr hdr;
    __u64 sock;
    __u32 len;
    char raw[128];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_118_emit_tcp_stream_l7stream_events SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        struct u_118_emit_tcp_stream_l7stream_event *_ls1 = bpf_ringbuf_reserve(&u_118_emit_tcp_stream_l7stream_events, sizeof(*_ls1), 0);
        if (_ls1) {
            _ls1->hdr.type = SPNL_EVT_USER_BASE;
            _ls1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _ls1->hdr.reserved = 0;
            _ls1->hdr.timestamp = bpf_ktime_get_ns();
            _ls1->sock = (__u64)(unsigned long)(sk);
            __u64 _ln1 = (__u64)(size);
            if (_ln1 > 128) _ln1 = 128;   /* cap: proven [0,128] bound for bpf_probe_read_user (dst = raw[128]) */
            _ls1->len = (__u32)_ln1;
            __builtin_memset(_ls1->raw, 0, sizeof(_ls1->raw));
            void *_lb1 = BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
            if (_lb1 && _ln1) (void)bpf_probe_read_user(_ls1->raw, _ln1, _lb1);   /* len == bytes copied, byte-exact up to 128 */
            bpf_ringbuf_submit(_ls1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
