// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 118_emit_tcp_stream.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit sock-keyed L7 stream channel === */
struct u_118_emit_tcp_stream_l7stream_event {
    struct spnl_event_hdr hdr;
    __u64 sock;
    __u32 len;
    char raw[128];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_118_emit_tcp_stream_l7stream_events SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        struct u_118_emit_tcp_stream_l7stream_event *_ls1 = bpf_ringbuf_reserve(&u_118_emit_tcp_stream_l7stream_events, sizeof(*_ls1), 0);
        if (_ls1) {
            _ls1->hdr.type = SPNL_EVT_USER_BASE;
            _ls1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _ls1->hdr.reserved = 0;
            _ls1->hdr.timestamp = bpf_ktime_get_ns();
            _ls1->sock = (__u64)(unsigned long)(sk);
            __u64 _ln1 = (__u64)(size);
            if (_ln1 > 128) _ln1 = 128;   /* cap: proven [0,128] bound for bpf_probe_read_user (dst = raw[128]) */
            _ls1->len = (__u32)_ln1;
            __builtin_memset(_ls1->raw, 0, sizeof(_ls1->raw));
            void *_lb1 = BPF_CORE_READ((struct msghdr *)(unsigned long)(msg), msg_iter.__ubuf_iovec.iov_base);
            if (_lb1 && _ln1) (void)bpf_probe_read_user(_ls1->raw, _ln1, _lb1);   /* len == bytes copied, byte-exact up to 128 */
            bpf_ringbuf_submit(_ls1, 0);
        }
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
