// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 118_emit_tcp_stream.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_118_emit_tcp_stream_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_118_emit_tcp_stream_lost, &_z);
    if (_l) *_l += 1;
}

/* === msghdr -> user buffer, and the datagram's real destination === */

/* Every builtin that reads the bytes of a send or a receive starts from a
 * `struct msghdr *` and has to answer one question: where in user memory are
 * the bytes? All eleven of them used to answer it the same wrong way --
 *
 *     BPF_CORE_READ(msg, msg_iter.__ubuf_iovec.iov_base)
 *
 * -- which is only the answer for ITER_UBUF. `msg_iter` is a tagged union and
 * that member is one of the tags; for ITER_IOVEC the same 8 bytes hold `__iov`,
 * a pointer to the KERNEL's copy of the caller's iovec array (import_iovec
 * copies it in), so the read above hands a kernel address to
 * bpf_probe_read_user, which fails. Measured on a 2-iovec sendmsg: iov_base
 * reported 0xffff80008714bc88 while the payload the process actually sent was
 * at 0xffffe6f60fb8.
 *
 * A single-entry iovec array is NOT affected: the kernel normalises nr_segs==1
 * to ITER_UBUF, which is why writev-style sends of one segment worked and why
 * the bug survived every fixture -- all of them send one buffer.
 *
 * The resolution lives in ONE function on purpose. Eleven call sites each
 * carrying their own union discipline is exactly how a second, disagreeing
 * table gets written.
 */

/* raw_status when the helper below could not name a user buffer at all. Distinct
 * from any errno bpf_probe_read_user can return, so a reader never has to guess
 * which of the two happened. */
#define SPNL_RAW_NO_USER_BUFFER (-1)

static __noinline void *spnl_msg_ubuf(struct msghdr *msg)
{
    if (!msg) return (void *)0;
    /* The enumerator values are read out of the running kernel's BTF rather
     * than baked in, so a renumbered enum cannot silently reclassify a send. */
    __u8 it = BPF_CORE_READ(msg, msg_iter.iter_type);
    void *base = (void *)0;
    if (it == bpf_core_enum_value(enum iter_type, ITER_UBUF)) {
        base = BPF_CORE_READ(msg, msg_iter.__ubuf_iovec.iov_base);
    } else if (it == bpf_core_enum_value(enum iter_type, ITER_IOVEC)) {
        /* __iov always points at the iterator's CURRENT segment (iov_iter_advance
         * walks the pointer forward), so the first entry is the right one at any
         * position, not just at entry. */
        const struct iovec *iov = BPF_CORE_READ(msg, msg_iter.__iov);
        if (iov) base = BPF_CORE_READ(iov, iov_base);
    }
    /* ITER_BVEC / ITER_KVEC / ITER_XARRAY / ITER_DISCARD describe pages or kernel
     * memory: there is no user buffer to read, and saying so is the point --
     * returning a plausible pointer is what produced the zero-filled records. */
    if (!base) return (void *)0;
    /* iov_offset is how far into the current segment the iterator already is.
     * Zero at every capture point this codegen attaches to (all of them are
     * function entries), but reading it makes the contract "the bytes the
     * iterator is about to consume" true wherever the helper is called. */
    return (void *)((__u8 *)base + (unsigned long)BPF_CORE_READ(msg, msg_iter.iov_offset));
}

/* === per-unit sock-keyed L7 stream channel === */
struct u_118_emit_tcp_stream_l7stream_event {
    struct spnl_event_hdr hdr;
    __u64 sock;
    __u32 len;
    char raw[128];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_118_emit_tcp_stream_l7stream_events SEC(".maps");

/* Publishes the layout above to .BTF so a reader in another language does not
 * have to copy it by hand. A RINGBUF map declares no value type and the struct
 * is only ever a local pointer in a static function, so nothing else in this
 * object names it. Never loaded: .spnl_records is not a section libbpf maps. */
const struct u_118_emit_tcp_stream_l7stream_event *_spnl_rec_l7stream_event SEC(".spnl_records");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int, msg: int, size: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    {
        struct u_118_emit_tcp_stream_l7stream_event *_ls1 = bpf_ringbuf_reserve(&u_118_emit_tcp_stream_l7stream_events, sizeof(*_ls1), 0);
        if (_ls1) {
            _ls1->hdr.type = SPNL_EVT_USER_BASE;
            _ls1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _ls1->hdr.reserved = 0;
            _ls1->hdr.timestamp = bpf_ktime_get_ns();
            _ls1->sock = (__u64)(unsigned long)(sk);
            __u64 _ln1 = (__u64)(size);
            if (_ln1 > 128) _ln1 = 128;   /* cap: proven [0,128] bound for bpf_probe_read_user (dst = raw[128]) */
            _ls1->len = (__u32)_ln1;
            __builtin_memset(_ls1->raw, 0, sizeof(_ls1->raw));
            void *_lb1 = spnl_msg_ubuf((struct msghdr *)(unsigned long)(msg));
            if (_lb1 && _ln1) (void)bpf_probe_read_user(_ls1->raw, _ln1, _lb1);   /* len == bytes copied, byte-exact up to 128 */
            bpf_ringbuf_submit(_ls1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
