// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 11_max_if.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* ctx for max — userspace fills before bpf_prog_test_run */
struct max_ctx {
    __s64 a;
    __s64 b;
};

/* ctx for sign — userspace fills before bpf_prog_test_run */
struct sign_ctx {
    __s64 x;
};

/* impl: max : int  params: a: int, b: int */
static __noinline __s64 max_inner(__s64 a, __s64 b)
{
    __s64 _if1 = 0;
    if (a > b) {
        _if1 = a;
    } else {
        _if1 = b;
    }
    return _if1;
}

/* entry wrapper: max */
SEC("syscall")
int max(struct max_ctx *ctx)
{
    return (int)max_inner(ctx->a, ctx->b);
}

/* impl: sign : int  params: x: int */
static __noinline __s64 sign_inner(__s64 x)
{
    __s64 _if1 = 0;
    if (x > 0) {
        _if1 = 1;
    } else {
        __s64 _if2 = 0;
        if (x < 0) {
            _if2 = -1;
        } else {
            _if2 = 0;
        }
        _if1 = _if2;
    }
    return _if1;
}

/* entry wrapper: sign */
SEC("syscall")
int sign(struct sign_ctx *ctx)
{
    return (int)sign_inner(ctx->x);
}
