// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 124_bprm_exec_path.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_124_bprm_exec_path_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_124_bprm_exec_path_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit string-event channel === */
struct u_124_bprm_exec_path_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_124_bprm_exec_path_str_events SEC(".maps");

/* top-level ivar @denied : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_124_bprm_exec_path_top_denied SEC(".maps");

/* ctx for lsm__bprm_check_security — userspace fills before bpf_prog_test_run */
struct lsm__bprm_check_security_ctx {
    __s64 bprm;
};

/* impl: lsm__bprm_check_security : int  params: bprm: int */
static __noinline __s64 lsm__bprm_check_security_inner(__s64 bprm)
{
    {
        struct linux_binprm *_pq2 = (struct linux_binprm *)(unsigned long)(bprm);
        struct file *_pg2 = _pq2 ? _pq2->file : 0;
        struct u_124_bprm_exec_path_str_event *_pe1 = bpf_ringbuf_reserve(&u_124_bprm_exec_path_str_events, sizeof(*_pe1), 0);
        if (_pe1) {
            _pe1->hdr.type = SPNL_EVT_USER_BASE;
            _pe1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _pe1->hdr.reserved = 0;
            _pe1->hdr.timestamp = bpf_ktime_get_ns();
            __builtin_memset(_pe1->str, 0, sizeof(_pe1->str));
            if (_pg2) bpf_d_path(&_pg2->f_path, _pe1->str, sizeof(_pe1->str));
            bpf_ringbuf_submit(_pe1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    struct linux_binprm *_pq3 = (struct linux_binprm *)(unsigned long)(bprm);
    struct file *_pg3 = _pq3 ? _pq3->file : 0;
    char _pb4[32] = {0};
    __s64 _pr4 = _pg3 ? bpf_d_path(&_pg3->f_path, _pb4, sizeof(_pb4)) : -1;
    __s64 _pm4 = (_pr4 == 26);
    _pm4 = _pm4 && (_pb4[0] == 47);
    _pm4 = _pm4 && (_pb4[1] == 117);
    _pm4 = _pm4 && (_pb4[2] == 115);
    _pm4 = _pm4 && (_pb4[3] == 114);
    _pm4 = _pm4 && (_pb4[4] == 47);
    _pm4 = _pm4 && (_pb4[5] == 98);
    _pm4 = _pm4 && (_pb4[6] == 105);
    _pm4 = _pm4 && (_pb4[7] == 110);
    _pm4 = _pm4 && (_pb4[8] == 47);
    _pm4 = _pm4 && (_pb4[9] == 115);
    _pm4 = _pm4 && (_pb4[10] == 112);
    _pm4 = _pm4 && (_pb4[11] == 110);
    _pm4 = _pm4 && (_pb4[12] == 108);
    _pm4 = _pm4 && (_pb4[13] == 95);
    _pm4 = _pm4 && (_pb4[14] == 100);
    _pm4 = _pm4 && (_pb4[15] == 101);
    _pm4 = _pm4 && (_pb4[16] == 110);
    _pm4 = _pm4 && (_pb4[17] == 105);
    _pm4 = _pm4 && (_pb4[18] == 101);
    _pm4 = _pm4 && (_pb4[19] == 100);
    _pm4 = _pm4 && (_pb4[20] == 95);
    _pm4 = _pm4 && (_pb4[21] == 101);
    _pm4 = _pm4 && (_pb4[22] == 120);
    _pm4 = _pm4 && (_pb4[23] == 101);
    _pm4 = _pm4 && (_pb4[24] == 99);
    __s64 _if5 = 0;
    if ((_pm4)) {
        __u32 _k6 = 0;
        __s64 *_p7 = bpf_map_lookup_elem(&u_124_bprm_exec_path_top_denied, &_k6);
        __u32 _k8 = 0;
        __s64 _v9 = (_p7 ? *_p7 : 0) + 1;
        bpf_map_update_elem(&u_124_bprm_exec_path_top_denied, &_k8, &_v9, BPF_ANY);
        _if5 = -1;
    } else {
        _if5 = 0;
    }
    return _if5;
}

/* entry wrapper: lsm__bprm_check_security [lsm -> lsm/bprm_check_security] */
SEC("lsm/bprm_check_security")
int lsm__bprm_check_security(__u64 *ctx)
{
    (void)ctx;
    return (int)lsm__bprm_check_security_inner((__s64)ctx[0]);
}
