// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 126_runtime_param.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === runtime parameters ===
 * Patched by the loader between skeleton __open() and __load(); frozen
 * thereafter. Unset means the declared default, and a default of 0 is what
 * makes a guard on it disappear from the verified program entirely. */
volatile const __s64 spnl_param_target_pid = 0;
volatile const __s64 spnl_param_min_dfd = 0;

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_126_runtime_param_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_126_runtime_param_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_126_runtime_param_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_126_runtime_param_events SEC(".maps");

/* top-level ivar @opens : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_126_runtime_param_top_opens SEC(".maps");

/* ctx for tracepoint__syscalls__sys_enter_openat — userspace fills before bpf_prog_test_run */
struct tracepoint__syscalls__sys_enter_openat_ctx {
    __s64 dfd;
};

/* impl: tracepoint__syscalls__sys_enter_openat : int  params: dfd: int */
static __noinline __s64 tracepoint__syscalls__sys_enter_openat_inner(__s64 dfd)
{
    __s64 _if1 = 0;
    if ((spnl_param_target_pid == 0 || ((__s64)(bpf_get_current_pid_tgid() >> 32)) == spnl_param_target_pid) && dfd >= spnl_param_min_dfd) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_126_runtime_param_top_opens, &_k2);
        __s64 _v4 = (_p3 ? *_p3 : 0) + (1);
        bpf_map_update_elem(&u_126_runtime_param_top_opens, &_k2, &_v4, BPF_ANY);
        {
            struct u_126_runtime_param_event *_e5 = bpf_ringbuf_reserve(&u_126_runtime_param_events, sizeof(*_e5), 0);
            if (_e5) {
                _e5->hdr.type = SPNL_EVT_USER_BASE;
                _e5->hdr.version = SPNL_EVENT_HDR_VERSION;
                _e5->hdr.reserved = 0;
                _e5->hdr.timestamp = bpf_ktime_get_ns();
                _e5->value = dfd;
                bpf_ringbuf_submit(_e5, 0);
            } else spnl_lost_inc();   /* ring full -> account the dropped record */
        }
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: tracepoint__syscalls__sys_enter_openat [tracepoint -> tracepoint/syscalls/sys_enter_openat] */
SEC("tracepoint/syscalls/sys_enter_openat")
int tracepoint__syscalls__sys_enter_openat(void *ctx)
{
    (void)ctx;
    (void)tracepoint__syscalls__sys_enter_openat_inner((__s64)((struct trace_event_raw_sys_enter *)ctx)->args[0]);
    return 0;
}
