// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 133_kfield_str.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === kernel string fields ===
 *
 * kfield reads a kernel struct field as a SCALAR, because BPF_CORE_READ returns
 * one. A string is not a scalar, and the last hop of a string field comes in two
 * shapes that need different code:
 *
 *   inline array   task_struct->comm            char[16]
 *                  the field IS the characters -> read AT its address
 *   pointer        dentry->d_name.name          const unsigned char *
 *                  the field POINTS AT them    -> fetch the pointer, then read
 *
 * Getting that backwards does not fail: reading the pointer field "as bytes"
 * yields the eight bytes of the pointer, which the verifier is happy with and
 * which arrives as garbage (measured -- libbpf's own BPF_CORE_READ_STR_INTO does
 * exactly this if you hand it a pointer field).
 *
 * So the choice is not left to whoever writes the probe. SPNL_KSTR_IS_PTR asks
 * the C type system which shape the field has: for an array `typeof(f)` is
 * `char[N]` while `typeof(&f[0])` is `char *` (different types); for a pointer
 * the two are the same type. __builtin_choose_expr then picks the branch at
 * compile time. Both branches are type-checked by clang even though only one is
 * emitted (measured), so a field that is neither shape cannot slip through: the
 * _Static_assert at each call site requires a 1-byte element.
 */
#define SPNL_KSTR_IS_PTR(chain) \
    __builtin_types_compatible_p(__typeof__(chain), __typeof__(&(chain)[0]))

/* The call-site shape check, in two questions so that each wrong answer names the
 * call the author wrote instead of a diagnostic from inside the expansion:
 *   is it indexable at all? (an array decays for __builtin_classify_type, so both
 *     shapes land in the pointer class; an int or a struct value does not)
 *   are the things it indexes single BYTES? (this is what refuses a chain that
 *     stopped one hop short, on `struct dentry *` -- which is still "a pointer") */
#define SPNL_KSTR_CHECK(chain, msg)                                              \
    _Static_assert(__builtin_classify_type(chain) == __builtin_classify_type((char *)0), msg); \
    _Static_assert(sizeof((chain)[0]) == 1, msg)

/* Reads the string at <src>-><accessors...> into dst (sizeof(dst) bounded, always
 * NUL-terminated); evaluates to the helper's return = bytes written incl. NUL,
 * or negative on fault. `chain` is the same field path written against a null
 * base, which is what carries the type to SPNL_KSTR_IS_PTR. */
#define SPNL_KFIELD_STR(dst, chain, src, ...)                                    \
    __builtin_choose_expr(SPNL_KSTR_IS_PTR(chain),                               \
        bpf_probe_read_kernel_str((dst), sizeof(dst),                            \
            (const void *)(unsigned long)BPF_CORE_READ(src, __VA_ARGS__)),       \
        BPF_CORE_READ_STR_INTO(&(dst), src, __VA_ARGS__))

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_133_kfield_str_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_133_kfield_str_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit string-event channel === */
struct u_133_kfield_str_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_133_kfield_str_str_events SEC(".maps");

/* top-level ivar @reads : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_133_kfield_str_top_reads SEC(".maps");

/* ctx for kprobe__vfs_read — userspace fills before bpf_prog_test_run */
struct kprobe__vfs_read_ctx {
    __s64 file;
};

/* impl: kprobe__vfs_read : int  params: file: int */
static __noinline __s64 kprobe__vfs_read_inner(__s64 file)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_133_kfield_str_top_reads, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_133_kfield_str_top_reads, &_k3, &_v4, BPF_ANY);
    {
        struct u_133_kfield_str_str_event *_kse5 = bpf_ringbuf_reserve(&u_133_kfield_str_str_events, sizeof(*_kse5), 0);
        if (_kse5) {
            _kse5->hdr.type = SPNL_EVT_USER_BASE;
            _kse5->hdr.version = SPNL_EVENT_HDR_VERSION;
            _kse5->hdr.reserved = 0;
            _kse5->hdr.timestamp = bpf_ktime_get_ns();
            __builtin_memset(_kse5->str, 0, sizeof(_kse5->str));
            struct file *_ksp6 = (struct file *)(unsigned long)(file);
            SPNL_KSTR_CHECK(((struct file *)0)->f_path.dentry->d_name.name,
                "emit_kfield_str(file, \"file\", \"f_path.dentry\", \"d_name.name\"): the last field must be characters (char[N] or char *); this chain ends on something else.");
            __s64 _ksr6 = SPNL_KFIELD_STR(_kse5->str, ((struct file *)0)->f_path.dentry->d_name.name, _ksp6, f_path.dentry, d_name.name);
            (void)_ksr6;
            bpf_ringbuf_submit(_kse5, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    {
        struct u_133_kfield_str_str_event *_kse7 = bpf_ringbuf_reserve(&u_133_kfield_str_str_events, sizeof(*_kse7), 0);
        if (_kse7) {
            _kse7->hdr.type = SPNL_EVT_USER_BASE;
            _kse7->hdr.version = SPNL_EVENT_HDR_VERSION;
            _kse7->hdr.reserved = 0;
            _kse7->hdr.timestamp = bpf_ktime_get_ns();
            __builtin_memset(_kse7->str, 0, sizeof(_kse7->str));
            struct file *_ksp8 = (struct file *)(unsigned long)(file);
            SPNL_KSTR_CHECK(((struct file *)0)->f_path.dentry->d_sb->s_id,
                "emit_kfield_str(file, \"file\", \"f_path.dentry\", \"d_sb\", \"s_id\"): the last field must be characters (char[N] or char *); this chain ends on something else.");
            __s64 _ksr8 = SPNL_KFIELD_STR(_kse7->str, ((struct file *)0)->f_path.dentry->d_sb->s_id, _ksp8, f_path.dentry, d_sb, s_id);
            (void)_ksr8;
            bpf_ringbuf_submit(_kse7, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__vfs_read [kprobe -> kprobe/vfs_read] */
SEC("kprobe/vfs_read")
int kprobe__vfs_read(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__vfs_read_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
