// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 137_sock_accessors.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_endian.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_137_sock_accessors_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_137_sock_accessors_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit pair-event channel === */
struct u_137_sock_accessors_pair_event {
    struct spnl_event_hdr hdr;
    __s64 a;
    __s64 b;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_137_sock_accessors_pair_events SEC(".maps");

/* === per-unit 4-tuple-event channel === */
struct u_137_sock_accessors_emit4_event {
    struct spnl_event_hdr hdr;
    __s64 a;
    __s64 b;
    __s64 c;
    __s64 d;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_137_sock_accessors_emit4_events SEC(".maps");

/* top-level ivar @conns : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_137_sock_accessors_top_conns SEC(".maps");

/* top-level ivar @v6 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_137_sock_accessors_top_v6 SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
};

/* impl: kprobe__tcp_sendmsg : void  params: sk: int */
static __noinline void kprobe__tcp_sendmsg_inner(__s64 sk)
{
    __s64 _if1 = 0;
    if (((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), sk_protocol)) == 6 && ((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_state)) == 1) {
        __s64 _if2 = 0;
        if (((__s64)(__u16)bpf_ntohs(BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_dport))) >= 8100 && ((__s64)(__u16)bpf_ntohs(BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_dport))) <= 8199) {
            __u32 _k3 = 0;
            __s64 *_p4 = bpf_map_lookup_elem(&u_137_sock_accessors_top_conns, &_k3);
            __u32 _k5 = 0;
            __s64 _v6 = (_p4 ? *_p4 : 0) + 1;
            bpf_map_update_elem(&u_137_sock_accessors_top_conns, &_k5, &_v6, BPF_ANY);
            {
                struct u_137_sock_accessors_emit4_event *_ne7 = bpf_ringbuf_reserve(&u_137_sock_accessors_emit4_events, sizeof(*_ne7), 0);
                if (_ne7) {
                    _ne7->hdr.type = SPNL_EVT_USER_BASE;
                    _ne7->hdr.version = SPNL_EVENT_HDR_VERSION;
                    _ne7->hdr.reserved = 0;
                    _ne7->hdr.timestamp = bpf_ktime_get_ns();
                    _ne7->a = ((__s64)(__u16)bpf_ntohs(BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_dport)));
                    _ne7->b = ((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_num));
                    _ne7->c = ((__s64)(__u32)bpf_ntohl(BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_daddr)));
                    _ne7->d = ((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_family));
                    bpf_ringbuf_submit(_ne7, 0);
                } else spnl_lost_inc();   /* ring full -> account the dropped record */
            }
            __s64 _if8 = 0;
            if (((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), __sk_common.skc_family)) == 10) {
                __u32 _k9 = 0;
                __s64 *_p10 = bpf_map_lookup_elem(&u_137_sock_accessors_top_v6, &_k9);
                __u32 _k11 = 0;
                __s64 _v12 = (_p10 ? *_p10 : 0) + 1;
                bpf_map_update_elem(&u_137_sock_accessors_top_v6, &_k11, &_v12, BPF_ANY);
                {
                    struct u_137_sock_accessors_pair_event *_pe13 = bpf_ringbuf_reserve(&u_137_sock_accessors_pair_events, sizeof(*_pe13), 0);
                    if (_pe13) {
                        _pe13->hdr.type = SPNL_EVT_USER_BASE;
                        _pe13->hdr.version = SPNL_EVENT_HDR_VERSION;
                        _pe13->hdr.reserved = 0;
                        _pe13->hdr.timestamp = bpf_ktime_get_ns();
                struct sock *_skp14 = (struct sock *)(unsigned long)(sk);
                        _pe13->a = ((__s64)((((__u64)bpf_ntohl(BPF_CORE_READ(_skp14, __sk_common.skc_v6_daddr.in6_u.u6_addr32[0]))) << 32) | (__u64)bpf_ntohl(BPF_CORE_READ(_skp14, __sk_common.skc_v6_daddr.in6_u.u6_addr32[1]))));
                struct sock *_skp15 = (struct sock *)(unsigned long)(sk);
                        _pe13->b = ((__s64)((((__u64)bpf_ntohl(BPF_CORE_READ(_skp15, __sk_common.skc_v6_daddr.in6_u.u6_addr32[2]))) << 32) | (__u64)bpf_ntohl(BPF_CORE_READ(_skp15, __sk_common.skc_v6_daddr.in6_u.u6_addr32[3]))));
                        bpf_ringbuf_submit(_pe13, 0);
                    } else spnl_lost_inc();   /* ring full -> account the dropped record */
                }
                _if8 = 0;
            }
            _if2 = _if8;
        }
        _if1 = _if2;
    }
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
