// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 139_iter_task_field.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @ntasks : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_139_iter_task_field_top_ntasks SEC(".maps");

/* top-level ivar @pid_sum : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_139_iter_task_field_top_pid_sum SEC(".maps");

/* impl: iter__task__scan : int */
static __noinline __s64 iter__task__scan_inner(struct bpf_iter__task *ctx)
{
    __s64 t = 0;
    struct task_struct *_it1 = ctx->task;
    __s64 _itv1 = 0;
    if (_it1) { barrier_var(_it1); _itv1 = (__s64)(unsigned long)_it1; }
    t = _itv1;
    __u32 _k2 = 0;
    __s64 *_p3 = bpf_map_lookup_elem(&u_139_iter_task_field_top_ntasks, &_k2);
    __u32 _k4 = 0;
    __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
    bpf_map_update_elem(&u_139_iter_task_field_top_ntasks, &_k4, &_v5, BPF_ANY);
    __u32 _k6 = 0;
    __s64 *_p7 = bpf_map_lookup_elem(&u_139_iter_task_field_top_pid_sum, &_k6);
    __u32 _k8 = 0;
    __s64 _v9 = (_p7 ? *_p7 : 0) + ((__s64)BPF_CORE_READ((struct task_struct *)(unsigned long)(t), pid));
    bpf_map_update_elem(&u_139_iter_task_field_top_pid_sum, &_k8, &_v9, BPF_ANY);
    return 0;
}

/* entry wrapper: iter__task__scan [iter_task -> iter/task] */
SEC("iter/task")
int iter__task__scan(struct bpf_iter__task *ctx)
{
    (void)ctx;
    if (!ctx->task) return 0;
    (void)iter__task__scan_inner(ctx);
    return 0;
}
