// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 140_cpumap_redirect.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @rx : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_140_cpumap_redirect_top_rx SEC(".maps");

/* L4 sport (TCP or UDP, IPv4 or IPv6) in host byte order, 0 otherwise. */
static __noinline __s64 spnl_pkt_l4_sport(struct xdp_md *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        if (iph->protocol != 6 && iph->protocol != 17) return 0;
        __u32 ihl = iph->ihl * 4;
        if (ihl < sizeof(*iph)) return 0;
        char *l4 = (char *)iph + ihl;
        if (l4 + 4 > (char *)data_end) return 0;
        __be16 *p = (__be16 *)(l4 + 0);
        return (__s64)bpf_ntohs(*p);
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        if (ip6h->nexthdr != 6 && ip6h->nexthdr != 17) return 0;
        char *l4 = (char *)(ip6h + 1);
        if (l4 + 4 > (char *)data_end) return 0;
        __be16 *p = (__be16 *)(l4 + 0);
        return (__s64)bpf_ntohs(*p);
    }
    return 0;
}

/* CPUMAP for XDP per-CPU fanout. Entries are populated from
 * userspace (e.g. via bpftool map update or libbpf). Value is a
 * 64-bit `bpf_cpumap_val { __u32 qsize; __u32 prog_id; }` -- userspace
 * supplies a `qsize` (typically 192) and optionally a secondary
 * XDP prog id to run on the destination CPU. */
struct {
    __uint(type, BPF_MAP_TYPE_CPUMAP);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(struct bpf_cpumap_val));
    __uint(max_entries, 64);
} spnl_cpumap SEC(".maps");

/* impl: xdp__fanout : int */
static __noinline __s64 xdp__fanout_inner(struct xdp_md *ctx)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_140_cpumap_redirect_top_rx, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_140_cpumap_redirect_top_rx, &_k3, &_v4, BPF_ANY);
    return (__s64)bpf_redirect_map(&spnl_cpumap, (__u32)(spnl_pkt_l4_sport(ctx) % 4), 0);
}

/* entry wrapper: xdp__fanout [xdp -> xdp] */
SEC("xdp")
int xdp__fanout(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__fanout_inner(ctx);
}
