// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 142_tail_call_dispatch.rb
// ebpf-eligible methods: 3, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @other_pkts : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_142_tail_call_dispatch_top_other_pkts SEC(".maps");

/* top-level ivar @tcp_pkts : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_142_tail_call_dispatch_top_tcp_pkts SEC(".maps");

/* bpf_dynptr-backed XDP byte access. vmlinux.h (CO-RE BTF)
 * already declares bpf_dynptr_from_xdp / bpf_dynptr_slice as
 * `__weak __ksym` externs with `u64 offset`, so we don't redeclare
 * them here -- just use them.
 *
 * Read a single byte from an XDP frame at runtime offset. The
 * verifier validates the 1-byte access via the dynptr -- no manual
 * `data + off > data_end` check needed in the caller.
 *
 * Re-ported from the retired Ruby code generator, having been lost in the port
 * to C and withdrawn as unimplemented. The body below is
 * byte-for-byte the oracle's, and it was measured to load unchanged on
 * 7.1.5-ebpf / clang 19.1.7 / -mcpu=v1 -- unlike the task iterator, whose
 * oracle form the current verifier rejected. `buffer__szk` in the kfunc
 * signature means the size must be a compile-time constant, which is why
 * the 1-byte read is the whole surface. */
static __noinline __s64 spnl_pkt_dynptr_byte_at(struct xdp_md *ctx, __s64 off)
{
    if (off < 0) return -1;
    struct bpf_dynptr dp;
    if (bpf_dynptr_from_xdp(ctx, 0, &dp) < 0) return -1;
    __u8 buf;
    __u8 *p = bpf_dynptr_slice(&dp, (__u64)off, &buf, 1);
    if (!p) return -1;
    return (__s64)*p;
}

/* PROG_ARRAY for bpf_tail_call dispatch.
 *
 * Slot i holds the i-th `def xdp_tail__<name>` of this unit, in DECLARATION
 * ORDER. Nothing in this file says so: the loader does the writing
 * (_spnl_prog_array_populate), and it finds this map by the literal name
 * `spnl_prog_array` and the programs by the literal prefix `xdp_tail__`. Those
 * two names and the ordering are the whole contract between the two halves --
 * a mismatch does not fail, it jumps somewhere else.
 *
 * Re-ported from the retired Ruby code generator, having been lost in the port
 * to C; the map type was withdrawn once the audit withdrew
 * `tail_call_to` and the `xdp_tail__` attach kind). The declaration below is
 * byte-for-byte the oracle's, and the oracle's whole output was measured to
 * compile and load unchanged on 7.1.5-ebpf / clang 19.1.7 / -mcpu=v1.
 *
 * max_entries is max(<tail targets>, 32) -- the oracle's rule. Slots past the
 * declared targets stay empty, and a bpf_tail_call into an empty slot FALLS
 * THROUGH (the caller keeps running) instead of failing, which is why a literal
 * slot outside the declared range is refused at compile time rather than left
 * to be discovered as "the packet took the wrong branch". */
struct {
    __uint(type, BPF_MAP_TYPE_PROG_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
    __uint(max_entries, 32);
} spnl_prog_array SEC(".maps");

/* impl: xdp_tail__tcp_handler : int */
static __noinline __s64 xdp_tail__tcp_handler_inner(struct xdp_md *ctx)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_142_tail_call_dispatch_top_tcp_pkts, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_142_tail_call_dispatch_top_tcp_pkts, &_k3, &_v4, BPF_ANY);
    return 2;
}

/* entry wrapper: xdp_tail__tcp_handler [xdp_tail -> xdp] */
SEC("xdp")
int xdp_tail__tcp_handler(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp_tail__tcp_handler_inner(ctx);
}

/* impl: xdp_tail__other_handler : int */
static __noinline __s64 xdp_tail__other_handler_inner(struct xdp_md *ctx)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_142_tail_call_dispatch_top_other_pkts, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_142_tail_call_dispatch_top_other_pkts, &_k3, &_v4, BPF_ANY);
    return 2;
}

/* entry wrapper: xdp_tail__other_handler [xdp_tail -> xdp] */
SEC("xdp")
int xdp_tail__other_handler(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp_tail__other_handler_inner(ctx);
}

/* impl: xdp__dispatcher : int */
static __noinline __s64 xdp__dispatcher_inner(struct xdp_md *ctx)
{
    __s64 proto = 0;
    proto = spnl_pkt_dynptr_byte_at(ctx, 23);
    __s64 _if1 = 0;
    if (proto == 6) {
        bpf_tail_call(ctx, &spnl_prog_array, (__u32)(0));
        _if1 = 0;
    } else {
        bpf_tail_call(ctx, &spnl_prog_array, (__u32)(1));
        _if1 = 0;
    }
    return 2;
}

/* entry wrapper: xdp__dispatcher [xdp -> xdp] */
SEC("xdp")
int xdp__dispatcher(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__dispatcher_inner(ctx);
}
