// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 143_user_ringbuf_channel.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_143_user_ringbuf_channel_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_143_user_ringbuf_channel_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_143_user_ringbuf_channel_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_143_user_ringbuf_channel_events SEC(".maps");

/* top-level ivar @cmds_received : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_143_user_ringbuf_channel_top_cmds_received SEC(".maps");

/* top-level ivar @last_value : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_143_user_ringbuf_channel_top_last_value SEC(".maps");

/* USER_RINGBUF for the host-to-kernel command channel.
 *
 * The one direction a plain BPF ringbuf cannot go. `bpf_ringbuf_*` carries
 * kernel->host; this map carries host->kernel, in FIFO order, with the host
 * side batching through libbpf's reserve/submit (the channel exists to batch).
 *
 * Re-ported from the retired Ruby code generator, having been lost in the port
 * to C; the map type was withdrawn once the audit withdrew both
 * `user_ringbuf_drain` and the `user_ringbuf__` attach kind.
 * The declaration below is byte-for-byte the oracle's, and the oracle's whole
 * output was measured to compile and load unchanged on 7.1.5-ebpf /
 * clang 19.1.7 / -mcpu=v1.
 *
 * TWO NUMBERS LIVE IN TWO FILES HERE and nothing checks them at build time:
 *   - the map's literal name `bpf_user_cmds`, which the loader's
 *     `sp_bpf_user_cmd_push` finds by string, and
 *   - the 8-byte record, which the callback below reads with a fixed
 *     `sizeof(__s64)` and the loader reserves with a fixed `sizeof(long long)`.
 * Measured what a disagreement does: a SHORT
 * record still fires the callback and still counts, but `bpf_dynptr_read`
 * returns -E2BIG and the value stays 0 -- silently. That is why the shipped
 * pusher is the only advertised way in, and why `describe` prints the size.
 *
 * max_entries is a byte count (ring size), not a record count: 256 KB. */
struct {
    __uint(type, BPF_MAP_TYPE_USER_RINGBUF);
    __uint(max_entries, 262144);
} bpf_user_cmds SEC(".maps");

static long spnl_user_ringbuf_cb_cmd_handler(struct bpf_dynptr *dynptr, void *_uctx);

/* ctx for user_ringbuf__cmd_handler — userspace fills before bpf_prog_test_run */
struct user_ringbuf__cmd_handler_ctx {
    __s64 value;
};

/* user_ringbuf callback for user_ringbuf__cmd_handler */
static long spnl_user_ringbuf_cb_cmd_handler(struct bpf_dynptr *dynptr, void *_uctx)
{
    __s64 value = 0;
    bpf_dynptr_read(&value, sizeof(value), dynptr, 0, 0);
    (void)_uctx;
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_143_user_ringbuf_channel_top_cmds_received, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_143_user_ringbuf_channel_top_cmds_received, &_k3, &_v4, BPF_ANY);
    __u32 _k5 = 0;
    __s64 _v6 = value;
    bpf_map_update_elem(&u_143_user_ringbuf_channel_top_last_value, &_k5, &_v6, BPF_ANY);
    {
        struct u_143_user_ringbuf_channel_event *_e7 = bpf_ringbuf_reserve(&u_143_user_ringbuf_channel_events, sizeof(*_e7), 0);
        if (_e7) {
            _e7->hdr.type = SPNL_EVT_USER_BASE;
            _e7->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e7->hdr.reserved = 0;
            _e7->hdr.timestamp = bpf_ktime_get_ns();
            _e7->value = value;
            bpf_ringbuf_submit(_e7, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* impl: xdp__drain_user_ringbuf : int */
static __noinline __s64 xdp__drain_user_ringbuf_inner(struct xdp_md *ctx)
{
    (void)bpf_user_ringbuf_drain(&bpf_user_cmds, spnl_user_ringbuf_cb_cmd_handler, NULL, 0);
    return 2;
}

/* entry wrapper: xdp__drain_user_ringbuf [xdp -> xdp] */
SEC("xdp")
int xdp__drain_user_ringbuf(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__drain_user_ringbuf_inner(ctx);
}
