// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 145_timer_event_loop.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @ticks : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_145_timer_event_loop_top_ticks SEC(".maps");

/* bpf_timer-backed periodic callback. Single ARRAY slot
 * holding the timer struct. The arm prog (also emitted) is fired
 * once by userspace at load time via bpf_prog_test_run.
 * Interval: 1000000000 ns (compile-time constant). */
struct spnl_timer_value {
    struct bpf_timer t;
};

struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, struct spnl_timer_value);
} spnl_timer_map SEC(".maps");

/* forward decl for the callback so the arm prog can reference it
 * before the body is emitted (codegen emits cb after the map). */
static int spnl_timer_cb_main(void *map, int *key, struct spnl_timer_value *v);

/* bpf_timer callback for on :timer, every: 1000000000 ns.
 * The verifier requires bpf_timer callbacks to return literal 0
 * (the body's return value is ignored, which matches the Ruby
 * semantic of `on :timer do ... end` having no return value).
 *
 * Re-ported from the retired Ruby code generator, having been lost in the port
 * to C and withdrawn as unimplemented; the rule was re-measured on 7.1.5:
 * returning an unknown scalar here still fails with "At async callback
 * return the register R0 has unknown scalar value should have been in
 * [0, 0]" -- the same verdict recorded on 7.0.x. */
static int spnl_timer_cb_main(void *map, int *key, struct spnl_timer_value *v)
{
    (void)map; (void)key;
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_145_timer_event_loop_top_ticks, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_145_timer_event_loop_top_ticks, &_k3, &_v4, BPF_ANY);
    bpf_timer_start(&v->t, 1000000000ULL, 0);
    return 0;
}

/* The arming program -- fired once by userspace at load time via
 * bpf_prog_test_run (glue.c _spnl_timer_arm_all fires every program whose
 * name starts with spnl_timer_arm_).
 *
 * `__u64 *ctx` is the original shape. A plain `void *ctx` was measured to also
 * loads on 7.1.5, so that lesson has expired -- the typed pointer is kept
 * because it is what the arm program is (libbpf sizes the argument from BTF)
 * and because changing it would buy nothing. The literal 1 below has NOT
 * expired: CLOCK_MONOTONIC is still absent from vmlinux.h. */
SEC("syscall")
int spnl_timer_arm_main(__u64 *ctx)
{
    __u32 _k = 0;
    struct spnl_timer_value *_v = bpf_map_lookup_elem(&spnl_timer_map, &_k);
    if (!_v) return 0;
    bpf_timer_init(&_v->t, &spnl_timer_map, 1 /* CLOCK_MONOTONIC */);
    bpf_timer_set_callback(&_v->t, spnl_timer_cb_main);
    bpf_timer_start(&_v->t, 1000000000ULL, 0);
    (void)ctx;
    return 0;
}
