// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 148_dsl_module_xdp.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @tcp : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_148_dsl_module_xdp_top_tcp SEC(".maps");

/* L4 protocol (TCP=6, UDP=17, ICMP=1, ICMPv6=58), or 0 if not
 * IPv4 nor IPv6 / truncated.
 * For IPv6 we return ip6h->nexthdr directly - if it's an
 * extension header (Hop-by-Hop=0, Routing=43, Fragment=44, ...)
 * the caller sees that value as-is (extension header walking is
 * out of scope for this builtin). */
static __noinline __s64 spnl_pkt_l4_proto(struct xdp_md *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {  /* ETH_P_IP */
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        return (__s64)iph->protocol;
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {  /* ETH_P_IPV6 */
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        return (__s64)ip6h->nexthdr;
    }
    return 0;
}

/* impl: xdp__count : int */
static __noinline __s64 xdp__count_inner(struct xdp_md *ctx)
{
    __s64 n = 0;
    n = spnl_pkt_l4_proto(ctx);
    __s64 _if1 = 0;
    if (n == 6) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_148_dsl_module_xdp_top_tcp, &_k2);
        __u32 _k4 = 0;
        __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
        bpf_map_update_elem(&u_148_dsl_module_xdp_top_tcp, &_k4, &_v5, BPF_ANY);
        _if1 = _v5;
    }
    return 2;
}

/* entry wrapper: xdp__count [xdp -> xdp] */
SEC("xdp")
int xdp__count(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__count_inner(ctx);
}
