// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 149_pkt_dynptr_byte_at.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @icmp : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_149_pkt_dynptr_byte_at_top_icmp SEC(".maps");

/* top-level ivar @ipv4 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_149_pkt_dynptr_byte_at_top_ipv4 SEC(".maps");

/* bpf_dynptr-backed XDP byte access. vmlinux.h (CO-RE BTF)
 * already declares bpf_dynptr_from_xdp / bpf_dynptr_slice as
 * `__weak __ksym` externs with `u64 offset`, so we don't redeclare
 * them here -- just use them.
 *
 * Read a single byte from an XDP frame at runtime offset. The
 * verifier validates the 1-byte access via the dynptr -- no manual
 * `data + off > data_end` check needed in the caller.
 *
 * Re-ported from the retired Ruby code generator, having been lost in the port
 * to C and withdrawn as unimplemented. The body below is
 * byte-for-byte the oracle's, and it was measured to load unchanged on
 * 7.1.5-ebpf / clang 19.1.7 / -mcpu=v1 -- unlike the task iterator, whose
 * oracle form the current verifier rejected. `buffer__szk` in the kfunc
 * signature means the size must be a compile-time constant, which is why
 * the 1-byte read is the whole surface. */
static __noinline __s64 spnl_pkt_dynptr_byte_at(struct xdp_md *ctx, __s64 off)
{
    if (off < 0) return -1;
    struct bpf_dynptr dp;
    if (bpf_dynptr_from_xdp(ctx, 0, &dp) < 0) return -1;
    __u8 buf;
    __u8 *p = bpf_dynptr_slice(&dp, (__u64)off, &buf, 1);
    if (!p) return -1;
    return (__s64)*p;
}

/* impl: xdp__probe : int */
static __noinline __s64 xdp__probe_inner(struct xdp_md *ctx)
{
    __s64 off = 0;
    __s64 _if1 = 0;
    if (spnl_pkt_dynptr_byte_at(ctx, 14) == 69) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_149_pkt_dynptr_byte_at_top_ipv4, &_k2);
        __u32 _k4 = 0;
        __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
        bpf_map_update_elem(&u_149_pkt_dynptr_byte_at_top_ipv4, &_k4, &_v5, BPF_ANY);
        _if1 = _v5;
    }
    off = 14 + 9;
    __s64 _if6 = 0;
    if (spnl_pkt_dynptr_byte_at(ctx, off) == 1) {
        __u32 _k7 = 0;
        __s64 *_p8 = bpf_map_lookup_elem(&u_149_pkt_dynptr_byte_at_top_icmp, &_k7);
        __u32 _k9 = 0;
        __s64 _v10 = (_p8 ? *_p8 : 0) + 1;
        bpf_map_update_elem(&u_149_pkt_dynptr_byte_at_top_icmp, &_k9, &_v10, BPF_ANY);
        _if6 = _v10;
    }
    return 2;
}

/* entry wrapper: xdp__probe [xdp -> xdp] */
SEC("xdp")
int xdp__probe(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__probe_inner(ctx);
}
