// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 153_attach_multi_expand.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_153_attach_multi_expand_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_153_attach_multi_expand_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_153_attach_multi_expand_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_153_attach_multi_expand_events SEC(".maps");

/* top-level ivar @calls : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_153_attach_multi_expand_top_calls SEC(".maps");

/* top-level ivar @reads : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_153_attach_multi_expand_top_reads SEC(".maps");

/* impl: kprobe_multi__set0 : int */
static __noinline __s64 kprobe_multi__set0_inner(__s64 __spnl_sym)
{
    (void)__spnl_sym;
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_153_attach_multi_expand_top_calls, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_153_attach_multi_expand_top_calls, &_k3, &_v4, BPF_ANY);
    __s64 _if5 = 0;
    if ((__spnl_sym == 0)) {
        __u32 _k6 = 0;
        __s64 *_p7 = bpf_map_lookup_elem(&u_153_attach_multi_expand_top_reads, &_k6);
        __u32 _k8 = 0;
        __s64 _v9 = (_p7 ? *_p7 : 0) + 1;
        bpf_map_update_elem(&u_153_attach_multi_expand_top_reads, &_k8, &_v9, BPF_ANY);
        _if5 = _v9;
    }
    {
        struct u_153_attach_multi_expand_event *_e10 = bpf_ringbuf_reserve(&u_153_attach_multi_expand_events, sizeof(*_e10), 0);
        if (_e10) {
            _e10->hdr.type = SPNL_EVT_USER_BASE;
            _e10->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e10->hdr.reserved = 0;
            _e10->hdr.timestamp = bpf_ktime_get_ns();
            _e10->value = (__spnl_sym);
            bpf_ringbuf_submit(_e10, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* spnl:attach-multi kind=kprobe mode=expand n=2 prog=kprobe_multi__set0 syms=vfs_read,vfs_write */
/* entry wrapper: kprobe_multi__set0 [kprobe -> kprobe/vfs_read, index 0 of 2] */
SEC("kprobe/vfs_read")
int kprobe_multi__set0__s0(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe_multi__set0_inner(0);
    return 0;
}

/* entry wrapper: kprobe_multi__set0 [kprobe -> kprobe/vfs_write, index 1 of 2] */
SEC("kprobe/vfs_write")
int kprobe_multi__set0__s1(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe_multi__set0_inner(1);
    return 0;
}
