// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 15_times_loop.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit int-event channel === */
struct u_15_times_loop_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_15_times_loop_events SEC(".maps");

/* ctx for emit_squares — userspace fills before bpf_prog_test_run */
struct emit_squares_ctx {
    __s64 n;
};

/* ctx for emit_indices — userspace fills before bpf_prog_test_run */
struct emit_indices_ctx {
    __s64 n;
};

/* loop callback: emitted for emit_squares */
static int emit_squares_loop1_cb(__u32 _raw_index, void *_raw_ctx)
{
    __s64 i = (__s64)_raw_index;
    (void)_raw_ctx;
    {
        struct u_15_times_loop_event *_e1 = bpf_ringbuf_reserve(&u_15_times_loop_events, sizeof(*_e1), 0);
        if (_e1) {
            _e1->hdr.type = SPNL_EVT_USER_BASE;
            _e1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e1->hdr.reserved = 0;
            _e1->hdr.timestamp = bpf_ktime_get_ns();
            _e1->value = i * i;
            bpf_ringbuf_submit(_e1, 0);
        }
    }
    return 0;
}

/* loop callback: emitted for emit_indices */
static int emit_indices_loop2_cb(__u32 _raw_index, void *_raw_ctx)
{
    __s64 i = (__s64)_raw_index;
    (void)_raw_ctx;
    {
        struct u_15_times_loop_event *_e1 = bpf_ringbuf_reserve(&u_15_times_loop_events, sizeof(*_e1), 0);
        if (_e1) {
            _e1->hdr.type = SPNL_EVT_USER_BASE;
            _e1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e1->hdr.reserved = 0;
            _e1->hdr.timestamp = bpf_ktime_get_ns();
            _e1->value = i;
            bpf_ringbuf_submit(_e1, 0);
        }
    }
    return 0;
}

/* impl: emit_squares : int  params: n: int */
static __noinline __s64 emit_squares_inner(__s64 n)
{
    bpf_loop(n, &emit_squares_loop1_cb, NULL, 0);
    return 0;
}

/* entry wrapper: emit_squares */
SEC("syscall")
int emit_squares(struct emit_squares_ctx *ctx)
{
    return (int)emit_squares_inner(ctx->n);
}

/* impl: emit_indices : int  params: n: int */
static __noinline __s64 emit_indices_inner(__s64 n)
{
    bpf_loop(n, &emit_indices_loop2_cb, NULL, 0);
    return 0;
}

/* entry wrapper: emit_indices */
SEC("syscall")
int emit_indices(struct emit_indices_ctx *ctx)
{
    return (int)emit_indices_inner(ctx->n);
}
