// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 16_closure.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit int-event channel === */
struct u_16_closure_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_16_closure_events SEC(".maps");

/* ctx for sum_squares — userspace fills before bpf_prog_test_run */
struct sum_squares_ctx {
    __s64 n;
};

/* ctx for emit_running_sum — userspace fills before bpf_prog_test_run */
struct emit_running_sum_ctx {
    __s64 n;
};

/* loop captures for sum_squares */
struct sum_squares_loop1_cb_caps {
    __s64 *total;
};

/* loop callback: emitted for sum_squares */
static int sum_squares_loop1_cb(__u32 _raw_index, void *_raw_ctx)
{
    __s64 i = (__s64)_raw_index;
    struct sum_squares_loop1_cb_caps *_lc = (struct sum_squares_loop1_cb_caps *)_raw_ctx;
    *_lc->total = (*_lc->total) + i * i;
    return 0;
}

/* loop captures for emit_running_sum */
struct emit_running_sum_loop2_cb_caps {
    __s64 *acc;
};

/* loop callback: emitted for emit_running_sum */
static int emit_running_sum_loop2_cb(__u32 _raw_index, void *_raw_ctx)
{
    __s64 i = (__s64)_raw_index;
    struct emit_running_sum_loop2_cb_caps *_lc = (struct emit_running_sum_loop2_cb_caps *)_raw_ctx;
    *_lc->acc = (*_lc->acc) + i;
    {
        struct u_16_closure_event *_e1 = bpf_ringbuf_reserve(&u_16_closure_events, sizeof(*_e1), 0);
        if (_e1) {
            _e1->hdr.type = SPNL_EVT_USER_BASE;
            _e1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e1->hdr.reserved = 0;
            _e1->hdr.timestamp = bpf_ktime_get_ns();
            _e1->value = (*_lc->acc);
            bpf_ringbuf_submit(_e1, 0);
        }
    }
    return 0;
}

/* impl: sum_squares : int  params: n: int */
static __noinline __s64 sum_squares_inner(__s64 n)
{
    __s64 total = 0;
    total = 0;
    struct sum_squares_loop1_cb_caps _loop1_caps = { .total = &total };
    bpf_loop(n, &sum_squares_loop1_cb, &_loop1_caps, 0);
    return total;
}

/* entry wrapper: sum_squares */
SEC("syscall")
int sum_squares(struct sum_squares_ctx *ctx)
{
    return (int)sum_squares_inner(ctx->n);
}

/* impl: emit_running_sum : int  params: n: int */
static __noinline __s64 emit_running_sum_inner(__s64 n)
{
    __s64 acc = 0;
    acc = 0;
    struct emit_running_sum_loop2_cb_caps _loop2_caps = { .acc = &acc };
    bpf_loop(n, &emit_running_sum_loop2_cb, &_loop2_caps, 0);
    return acc;
}

/* entry wrapper: emit_running_sum */
SEC("syscall")
int emit_running_sum(struct emit_running_sum_ctx *ctx)
{
    return (int)emit_running_sum_inner(ctx->n);
}
