// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 184_if_expression_value.rb
// ebpf-eligible methods: 3, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_184_if_expression_value_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_184_if_expression_value_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_184_if_expression_value_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_184_if_expression_value_events SEC(".maps");

/* top-level ivar @last : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_184_if_expression_value_top_last SEC(".maps");

/* ctx for classify — userspace fills before bpf_prog_test_run */
struct classify_ctx {
    __s64 a;
};

/* ctx for kprobe__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct kprobe__do_sys_openat2_ctx {
    __s64 a;
};

/* ctx for sign — userspace fills before bpf_prog_test_run */
struct sign_ctx {
    __s64 a;
};

/* impl: classify : int  params: a: int */
static __noinline __s64 classify_inner(__s64 a)
{
    __s64 n = 0;
    __s64 _if1 = 0;
    if (a > 10) {
        _if1 = 2;
    } else {
        __s64 _if2 = 0;
        if (a > 0) {
            _if2 = 1;
        } else {
            _if2 = 0;
        }
        _if1 = _if2;
    }
    n = _if1;
    return n;
}

/* entry wrapper: classify */
SEC("syscall")
int classify(struct classify_ctx *ctx)
{
    return (int)classify_inner(ctx->a);
}

/* impl: kprobe__do_sys_openat2 : int  params: a: int */
static __noinline __s64 kprobe__do_sys_openat2_inner(__s64 a)
{
    __s64 _if1 = 0;
    if (a > 0) {
        _if1 = 1;
    } else {
        _if1 = 0;
    }
    __u32 _k2 = 0;
    __s64 _v3 = _if1;
    bpf_map_update_elem(&u_184_if_expression_value_top_last, &_k2, &_v3, BPF_ANY);
    __s64 _if4 = 0;
    if (a > 100) {
        _if4 = 1;
    } else {
        _if4 = 0;
    }
    {
        struct u_184_if_expression_value_event *_e5 = bpf_ringbuf_reserve(&u_184_if_expression_value_events, sizeof(*_e5), 0);
        if (_e5) {
            _e5->hdr.type = SPNL_EVT_USER_BASE;
            _e5->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e5->hdr.reserved = 0;
            _e5->hdr.timestamp = bpf_ktime_get_ns();
            _e5->value = classify_inner(a) + (_if4);
            bpf_ringbuf_submit(_e5, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__do_sys_openat2 [kprobe -> kprobe/do_sys_openat2] */
SEC("kprobe/do_sys_openat2")
int kprobe__do_sys_openat2(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__do_sys_openat2_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}

/* impl: sign : int  params: a: int */
static __noinline __s64 sign_inner(__s64 a)
{
    __s64 _if1 = 0;
    if (a > 0) {
        _if1 = 1;
    } else {
        _if1 = -1;
    }
    return _if1;
}

/* entry wrapper: sign */
SEC("syscall")
int sign(struct sign_ctx *ctx)
{
    return (int)sign_inner(ctx->a);
}
