// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 186_early_return.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @big : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_186_early_return_top_big SEC(".maps");

/* top-level ivar @small : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_186_early_return_top_small SEC(".maps");

/* ctx for kprobe__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct kprobe__do_sys_openat2_ctx {
    __s64 a;
};

/* impl: kprobe__do_sys_openat2 : int  params: a: int */
static __noinline __s64 kprobe__do_sys_openat2_inner(__s64 a)
{
    __s64 _if1 = 0;
    if (a > 100) {
        return 1;
    }
    __s64 _if2 = 0;
    if (a > 10) {
        __u32 _k3 = 0;
        __s64 *_p4 = bpf_map_lookup_elem(&u_186_early_return_top_big, &_k3);
        __s64 _v5 = (_p4 ? *_p4 : 0) + (1);
        bpf_map_update_elem(&u_186_early_return_top_big, &_k3, &_v5, BPF_ANY);
        return 2;
    }
    __u32 _k6 = 0;
    __s64 *_p7 = bpf_map_lookup_elem(&u_186_early_return_top_small, &_k6);
    __s64 _v8 = (_p7 ? *_p7 : 0) + (1);
    bpf_map_update_elem(&u_186_early_return_top_small, &_k6, &_v8, BPF_ANY);
    return 0;
}

/* entry wrapper: kprobe__do_sys_openat2 [kprobe -> kprobe/do_sys_openat2] */
SEC("kprobe/do_sys_openat2")
int kprobe__do_sys_openat2(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__do_sys_openat2_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
