// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 20_top_ivar.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_20_top_ivar_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_20_top_ivar_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_20_top_ivar_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_20_top_ivar_events SEC(".maps");

/* top-level ivar @open_count : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_20_top_ivar_top_open_count SEC(".maps");

/* ctx for tracepoint__syscalls__sys_enter_openat — userspace fills before bpf_prog_test_run */
struct tracepoint__syscalls__sys_enter_openat_ctx {
    __s64 dfd;
};

/* impl: tracepoint__syscalls__sys_enter_openat : int  params: dfd: int */
static __noinline __s64 tracepoint__syscalls__sys_enter_openat_inner(__s64 dfd)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_20_top_ivar_top_open_count, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_20_top_ivar_top_open_count, &_k3, &_v4, BPF_ANY);
    __u32 _k5 = 0;
    __s64 *_p6 = bpf_map_lookup_elem(&u_20_top_ivar_top_open_count, &_k5);
    {
        struct u_20_top_ivar_event *_e7 = bpf_ringbuf_reserve(&u_20_top_ivar_events, sizeof(*_e7), 0);
        if (_e7) {
            _e7->hdr.type = SPNL_EVT_USER_BASE;
            _e7->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e7->hdr.reserved = 0;
            _e7->hdr.timestamp = bpf_ktime_get_ns();
            _e7->value = (_p6 ? *_p6 : 0);
            bpf_ringbuf_submit(_e7, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: tracepoint__syscalls__sys_enter_openat [tracepoint -> tracepoint/syscalls/sys_enter_openat] */
SEC("tracepoint/syscalls/sys_enter_openat")
int tracepoint__syscalls__sys_enter_openat(void *ctx)
{
    (void)ctx;
    (void)tracepoint__syscalls__sys_enter_openat_inner((__s64)((struct trace_event_raw_sys_enter *)ctx)->args[0]);
    return 0;
}
