// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 21_sched.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit int-event channel === */
struct u_21_sched_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_21_sched_events SEC(".maps");

/* ctx for tracepoint__sched__sched_switch — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_switch_ctx {
    __s64 prev_pid;
    __s64 next_pid;
};

/* impl: tracepoint__sched__sched_switch : int  params: prev_pid: int, next_pid: int */
static __noinline __s64 tracepoint__sched__sched_switch_inner(__s64 prev_pid, __s64 next_pid)
{
    {
        struct u_21_sched_event *_e1 = bpf_ringbuf_reserve(&u_21_sched_events, sizeof(*_e1), 0);
        if (_e1) {
            _e1->hdr.type = SPNL_EVT_USER_BASE;
            _e1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e1->hdr.reserved = 0;
            _e1->hdr.timestamp = bpf_ktime_get_ns();
            _e1->value = prev_pid;
            bpf_ringbuf_submit(_e1, 0);
        }
    }
    return 0;
}

/* entry wrapper: tracepoint__sched__sched_switch [tracepoint -> tracepoint/sched/sched_switch] */
SEC("tracepoint/sched/sched_switch")
int tracepoint__sched__sched_switch(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_switch_inner((__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_pid, (__s64)((struct trace_event_raw_sched_switch *)ctx)->next_pid);
    return 0;
}
