// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 22_emit_pair.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_22_emit_pair_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_22_emit_pair_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit pair-event channel === */
struct u_22_emit_pair_pair_event {
    struct spnl_event_hdr hdr;
    __s64 a;
    __s64 b;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_22_emit_pair_pair_events SEC(".maps");

/* ctx for tracepoint__sched__sched_switch — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_switch_ctx {
    __s64 prev_pid;
    __s64 next_pid;
};

/* impl: tracepoint__sched__sched_switch : int  params: prev_pid: int, next_pid: int */
static __noinline __s64 tracepoint__sched__sched_switch_inner(__s64 prev_pid, __s64 next_pid)
{
    {
        struct u_22_emit_pair_pair_event *_pe1 = bpf_ringbuf_reserve(&u_22_emit_pair_pair_events, sizeof(*_pe1), 0);
        if (_pe1) {
            _pe1->hdr.type = SPNL_EVT_USER_BASE;
            _pe1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _pe1->hdr.reserved = 0;
            _pe1->hdr.timestamp = bpf_ktime_get_ns();
            _pe1->a = prev_pid;
            _pe1->b = next_pid;
            bpf_ringbuf_submit(_pe1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: tracepoint__sched__sched_switch [tracepoint -> tracepoint/sched/sched_switch] */
SEC("tracepoint/sched/sched_switch")
int tracepoint__sched__sched_switch(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_switch_inner((__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_pid, (__s64)((struct trace_event_raw_sched_switch *)ctx)->next_pid);
    return 0;
}
