// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 26_xdp_proto_count.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @rx_icmp : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_26_xdp_proto_count_top_rx_icmp SEC(".maps");

/* top-level ivar @rx_other : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_26_xdp_proto_count_top_rx_other SEC(".maps");

/* top-level ivar @rx_tcp : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_26_xdp_proto_count_top_rx_tcp SEC(".maps");

/* top-level ivar @rx_udp : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_26_xdp_proto_count_top_rx_udp SEC(".maps");

/* L4 protocol (TCP=6, UDP=17, ICMP=1, ICMPv6=58), or 0 if not
 * IPv4 nor IPv6 / truncated.
 * For IPv6 we return ip6h->nexthdr directly - if it's an
 * extension header (Hop-by-Hop=0, Routing=43, Fragment=44, ...)
 * the caller sees that value as-is (extension header walking is
 * out of scope for this builtin). */
static __noinline __s64 spnl_pkt_l4_proto(struct xdp_md *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {  /* ETH_P_IP */
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        return (__s64)iph->protocol;
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {  /* ETH_P_IPV6 */
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        return (__s64)ip6h->nexthdr;
    }
    return 0;
}

/* impl: xdp__main : int */
static __noinline __s64 xdp__main_inner(struct xdp_md *ctx)
{
    __s64 p = 0;
    p = spnl_pkt_l4_proto(ctx);
    __s64 _if1 = 0;
    if (p == 1) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_26_xdp_proto_count_top_rx_icmp, &_k2);
        __u32 _k4 = 0;
        __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
        bpf_map_update_elem(&u_26_xdp_proto_count_top_rx_icmp, &_k4, &_v5, BPF_ANY);
        _if1 = _v5;
    } else {
        __s64 _if6 = 0;
        if (p == 6) {
            __u32 _k7 = 0;
            __s64 *_p8 = bpf_map_lookup_elem(&u_26_xdp_proto_count_top_rx_tcp, &_k7);
            __u32 _k9 = 0;
            __s64 _v10 = (_p8 ? *_p8 : 0) + 1;
            bpf_map_update_elem(&u_26_xdp_proto_count_top_rx_tcp, &_k9, &_v10, BPF_ANY);
            _if6 = _v10;
        } else {
            __s64 _if11 = 0;
            if (p == 17) {
                __u32 _k12 = 0;
                __s64 *_p13 = bpf_map_lookup_elem(&u_26_xdp_proto_count_top_rx_udp, &_k12);
                __u32 _k14 = 0;
                __s64 _v15 = (_p13 ? *_p13 : 0) + 1;
                bpf_map_update_elem(&u_26_xdp_proto_count_top_rx_udp, &_k14, &_v15, BPF_ANY);
                _if11 = _v15;
            } else {
                __u32 _k16 = 0;
                __s64 *_p17 = bpf_map_lookup_elem(&u_26_xdp_proto_count_top_rx_other, &_k16);
                __u32 _k18 = 0;
                __s64 _v19 = (_p17 ? *_p17 : 0) + 1;
                bpf_map_update_elem(&u_26_xdp_proto_count_top_rx_other, &_k18, &_v19, BPF_ANY);
                _if11 = _v19;
            }
            _if6 = _if11;
        }
        _if1 = _if6;
    }
    return 2;
}

/* entry wrapper: xdp__main [xdp -> xdp] */
SEC("xdp")
int xdp__main(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__main_inner(ctx);
}
