// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 30_tc_port_filter.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @allowed_8080 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_30_tc_port_filter_top_allowed_8080 SEC(".maps");

/* top-level ivar @dropped : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_30_tc_port_filter_top_dropped SEC(".maps");

/* L4 dport (TCP or UDP, IPv4 or IPv6) in host byte order, 0 otherwise. */
static __noinline __s64 spnl_tc_pkt_l4_dport(struct __sk_buff *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        if (iph->protocol != 6 && iph->protocol != 17) return 0;
        __u32 ihl = iph->ihl * 4;
        if (ihl < sizeof(*iph)) return 0;
        char *l4 = (char *)iph + ihl;
        if (l4 + 4 > (char *)data_end) return 0;
        __be16 *p = (__be16 *)(l4 + 2);
        return (__s64)bpf_ntohs(*p);
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        if (ip6h->nexthdr != 6 && ip6h->nexthdr != 17) return 0;
        char *l4 = (char *)(ip6h + 1);
        if (l4 + 4 > (char *)data_end) return 0;
        __be16 *p = (__be16 *)(l4 + 2);
        return (__s64)bpf_ntohs(*p);
    }
    return 0;
}

/* L4 sport (TCP or UDP, IPv4 or IPv6) in host byte order, 0 otherwise. */
static __noinline __s64 spnl_tc_pkt_l4_sport(struct __sk_buff *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        if (iph->protocol != 6 && iph->protocol != 17) return 0;
        __u32 ihl = iph->ihl * 4;
        if (ihl < sizeof(*iph)) return 0;
        char *l4 = (char *)iph + ihl;
        if (l4 + 4 > (char *)data_end) return 0;
        __be16 *p = (__be16 *)(l4 + 0);
        return (__s64)bpf_ntohs(*p);
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        if (ip6h->nexthdr != 6 && ip6h->nexthdr != 17) return 0;
        char *l4 = (char *)(ip6h + 1);
        if (l4 + 4 > (char *)data_end) return 0;
        __be16 *p = (__be16 *)(l4 + 0);
        return (__s64)bpf_ntohs(*p);
    }
    return 0;
}

/* impl: tc__ingress__http_filter : int */
static __noinline __s64 tc__ingress__http_filter_inner(struct __sk_buff *ctx)
{
    __s64 _if1 = 0;
    if (spnl_tc_pkt_l4_dport(ctx) == 8080 || spnl_tc_pkt_l4_sport(ctx) == 8080) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_30_tc_port_filter_top_allowed_8080, &_k2);
        __u32 _k4 = 0;
        __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
        bpf_map_update_elem(&u_30_tc_port_filter_top_allowed_8080, &_k4, &_v5, BPF_ANY);
        _if1 = 0;
    } else {
        __u32 _k6 = 0;
        __s64 *_p7 = bpf_map_lookup_elem(&u_30_tc_port_filter_top_dropped, &_k6);
        __u32 _k8 = 0;
        __s64 _v9 = (_p7 ? *_p7 : 0) + 1;
        bpf_map_update_elem(&u_30_tc_port_filter_top_dropped, &_k8, &_v9, BPF_ANY);
        _if1 = 2;
    }
    return _if1;
}

/* entry wrapper: tc__ingress__http_filter [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__http_filter(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__http_filter_inner(ctx);
}
