// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 31_tc_blocklist.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @blocked_hits : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_31_tc_blocklist_top_blocked_hits SEC(".maps");

/* top-level ivar @passed_hits : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_31_tc_blocklist_top_passed_hits SEC(".maps");

/* IPv4 source address in host byte order, or 0 if not IPv4. */
static __noinline __s64 spnl_tc_pkt_ip4_src(struct __sk_buff *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto != bpf_htons(0x0800)) return 0;
    struct iphdr *iph = (void *)(eth + 1);
    if ((void *)(iph + 1) > data_end) return 0;
    return (__s64)bpf_ntohl(iph->saddr);
}

/* per-unit blocklist. Populated from userspace via
 * sp_bpf_blocklist_add(uint32_t) / sp_bpf_blocklist_del(uint32_t),
 * read from BPF via spnl_blocklist_match(ip_host_order). */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __u8);
    __uint(max_entries, 8192);
} bpf_blocklist SEC(".maps");

static __noinline __s64 spnl_blocklist_match(__s64 ip_host_order)
{
    __u32 k = (__u32)ip_host_order;
    __u8 *v = bpf_map_lookup_elem(&bpf_blocklist, &k);
    return v ? 1 : 0;
}

/* impl: tc__ingress__blocklist_filter : int */
static __noinline __s64 tc__ingress__blocklist_filter_inner(struct __sk_buff *ctx)
{
    __s64 _if1 = 0;
    if (spnl_blocklist_match(spnl_tc_pkt_ip4_src(ctx)) == 1) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_31_tc_blocklist_top_blocked_hits, &_k2);
        __u32 _k4 = 0;
        __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
        bpf_map_update_elem(&u_31_tc_blocklist_top_blocked_hits, &_k4, &_v5, BPF_ANY);
        _if1 = 2;
    } else {
        __u32 _k6 = 0;
        __s64 *_p7 = bpf_map_lookup_elem(&u_31_tc_blocklist_top_passed_hits, &_k6);
        __u32 _k8 = 0;
        __s64 _v9 = (_p7 ? *_p7 : 0) + 1;
        bpf_map_update_elem(&u_31_tc_blocklist_top_passed_hits, &_k8, &_v9, BPF_ANY);
        _if1 = 0;
    }
    return _if1;
}

/* entry wrapper: tc__ingress__blocklist_filter [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__blocklist_filter(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__blocklist_filter_inner(ctx);
}
