// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 34_sk_msg.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @msg_count : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_34_sk_msg_top_msg_count SEC(".maps");

/* top-level ivar @skb_count : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_34_sk_msg_top_skb_count SEC(".maps");

/* impl: sk_msg__pass_all : int */
static __noinline __s64 sk_msg__pass_all_inner(struct sk_msg_md *ctx)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_34_sk_msg_top_msg_count, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_34_sk_msg_top_msg_count, &_k3, &_v4, BPF_ANY);
    return 1;
}

/* entry wrapper: sk_msg__pass_all [sk_msg -> sk_msg] */
SEC("sk_msg")
int sk_msg__pass_all(struct sk_msg_md *ctx)
{
    (void)ctx;
    return (int)sk_msg__pass_all_inner(ctx);
}

/* impl: sk_skb__verdict__pass_all : int */
static __noinline __s64 sk_skb__verdict__pass_all_inner(struct __sk_buff *ctx)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_34_sk_msg_top_skb_count, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_34_sk_msg_top_skb_count, &_k3, &_v4, BPF_ANY);
    return 1;
}

/* entry wrapper: sk_skb__verdict__pass_all [sk_skb_verdict -> sk_skb/stream_verdict] */
SEC("sk_skb/stream_verdict")
int sk_skb__verdict__pass_all(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)sk_skb__verdict__pass_all_inner(ctx);
}
