// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 35_xdp_ipv6.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @last_src_hi : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_35_xdp_ipv6_top_last_src_hi SEC(".maps");

/* top-level ivar @v6_pkts : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_35_xdp_ipv6_top_v6_pkts SEC(".maps");

/* L4 protocol (TCP=6, UDP=17, ICMP=1, ICMPv6=58), or 0 if not
 * IPv4 nor IPv6 / truncated.
 * For IPv6 we return ip6h->nexthdr directly - if it's an
 * extension header (Hop-by-Hop=0, Routing=43, Fragment=44, ...)
 * the caller sees that value as-is (extension header walking is
 * out of scope for this builtin). */
static __noinline __s64 spnl_pkt_l4_proto(struct xdp_md *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {  /* ETH_P_IP */
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        return (__s64)iph->protocol;
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {  /* ETH_P_IPV6 */
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        return (__s64)ip6h->nexthdr;
    }
    return 0;
}

/* IPv6 src address hi half (host byte order), 0 if not IPv6. */
static __noinline __s64 spnl_pkt_ip6_src_hi(struct xdp_md *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto != bpf_htons(0x86DD)) return 0;  /* ETH_P_IPV6 */
    struct ipv6hdr *ip6h = (void *)(eth + 1);
    if ((void *)(ip6h + 1) > data_end) return 0;
    __be32 a0 = ip6h->saddr.in6_u.u6_addr32[0];
    __be32 a1 = ip6h->saddr.in6_u.u6_addr32[1];
    __u64 v = ((__u64)bpf_ntohl(a0) << 32) | (__u64)bpf_ntohl(a1);
    return (__s64)v;
}

/* impl: xdp__main : int */
static __noinline __s64 xdp__main_inner(struct xdp_md *ctx)
{
    __s64 proto = 0;
    proto = spnl_pkt_l4_proto(ctx);
    __s64 _if1 = 0;
    if (proto == 58) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_35_xdp_ipv6_top_v6_pkts, &_k2);
        __s64 _v4 = (_p3 ? *_p3 : 0) + (1);
        bpf_map_update_elem(&u_35_xdp_ipv6_top_v6_pkts, &_k2, &_v4, BPF_ANY);
        __u32 _k5 = 0;
        __s64 _v6 = spnl_pkt_ip6_src_hi(ctx);
        bpf_map_update_elem(&u_35_xdp_ipv6_top_last_src_hi, &_k5, &_v6, BPF_ANY);
        _if1 = _v6;
    }
    return 2;
}

/* entry wrapper: xdp__main [xdp -> xdp] */
SEC("xdp")
int xdp__main(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__main_inner(ctx);
}
