// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 36_emit_n_tuple.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_36_emit_n_tuple_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_36_emit_n_tuple_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit 3-tuple-event channel === */
struct u_36_emit_n_tuple_emit3_event {
    struct spnl_event_hdr hdr;
    __s64 a;
    __s64 b;
    __s64 c;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_36_emit_n_tuple_emit3_events SEC(".maps");

/* === per-unit 4-tuple-event channel === */
struct u_36_emit_n_tuple_emit4_event {
    struct spnl_event_hdr hdr;
    __s64 a;
    __s64 b;
    __s64 c;
    __s64 d;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_36_emit_n_tuple_emit4_events SEC(".maps");

/* ctx for kprobe__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct kprobe__do_sys_openat2_ctx {
    __s64 dfd;
    __s64 filename;
    __s64 how;
};

/* impl: kprobe__do_sys_openat2 : int  params: dfd: int, filename: int, how: int */
static __noinline __s64 kprobe__do_sys_openat2_inner(__s64 dfd, __s64 filename, __s64 how)
{
    {
        struct u_36_emit_n_tuple_emit3_event *_ne1 = bpf_ringbuf_reserve(&u_36_emit_n_tuple_emit3_events, sizeof(*_ne1), 0);
        if (_ne1) {
            _ne1->hdr.type = SPNL_EVT_USER_BASE;
            _ne1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _ne1->hdr.reserved = 0;
            _ne1->hdr.timestamp = bpf_ktime_get_ns();
            _ne1->a = dfd;
            _ne1->b = 1;
            _ne1->c = 2;
            bpf_ringbuf_submit(_ne1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    {
        struct u_36_emit_n_tuple_emit4_event *_ne2 = bpf_ringbuf_reserve(&u_36_emit_n_tuple_emit4_events, sizeof(*_ne2), 0);
        if (_ne2) {
            _ne2->hdr.type = SPNL_EVT_USER_BASE;
            _ne2->hdr.version = SPNL_EVENT_HDR_VERSION;
            _ne2->hdr.reserved = 0;
            _ne2->hdr.timestamp = bpf_ktime_get_ns();
            _ne2->a = dfd;
            _ne2->b = 1;
            _ne2->c = 2;
            _ne2->d = 3;
            bpf_ringbuf_submit(_ne2, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__do_sys_openat2 [kprobe -> kprobe/do_sys_openat2] */
SEC("kprobe/do_sys_openat2")
int kprobe__do_sys_openat2(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__do_sys_openat2_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
