// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 37_c_keyword_collision.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_37_c_keyword_collision_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_37_c_keyword_collision_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_37_c_keyword_collision_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_37_c_keyword_collision_events SEC(".maps");

/* ctx for kprobe__do_test — userspace fills before bpf_prog_test_run */
struct kprobe__do_test_ctx {
    __s64 double_;
    __s64 register_;
};

/* impl: kprobe__do_test : int  params: double_: int, register_: int */
static __noinline __s64 kprobe__do_test_inner(__s64 double_, __s64 register_)
{
    __s64 static_ = 0;
    __s64 volatile_ = 0;
    static_ = double_ + register_;
    volatile_ = static_ * 2;
    {
        struct u_37_c_keyword_collision_event *_e1 = bpf_ringbuf_reserve(&u_37_c_keyword_collision_events, sizeof(*_e1), 0);
        if (_e1) {
            _e1->hdr.type = SPNL_EVT_USER_BASE;
            _e1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e1->hdr.reserved = 0;
            _e1->hdr.timestamp = bpf_ktime_get_ns();
            _e1->value = volatile_;
            bpf_ringbuf_submit(_e1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__do_test [kprobe -> kprobe/do_test] */
SEC("kprobe/do_test")
int kprobe__do_test(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__do_test_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}
