// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 37_c_keyword_collision.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit int-event channel === */
struct u_37_c_keyword_collision_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_37_c_keyword_collision_events SEC(".maps");

/* ctx for kprobe__do_test — userspace fills before bpf_prog_test_run */
struct kprobe__do_test_ctx {
    __s64 double_;
    __s64 register_;
};

/* impl: kprobe__do_test : int  params: double_: int, register_: int */
static __noinline __s64 kprobe__do_test_inner(__s64 double_, __s64 register_)
{
    __s64 static_ = 0;
    __s64 volatile_ = 0;
    static_ = double_ + register_;
    volatile_ = static_ * 2;
    {
        struct u_37_c_keyword_collision_event *_e1 = bpf_ringbuf_reserve(&u_37_c_keyword_collision_events, sizeof(*_e1), 0);
        if (_e1) {
            _e1->hdr.type = SPNL_EVT_USER_BASE;
            _e1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e1->hdr.reserved = 0;
            _e1->hdr.timestamp = bpf_ktime_get_ns();
            _e1->value = volatile_;
            bpf_ringbuf_submit(_e1, 0);
        }
    }
    return 0;
}

/* entry wrapper: kprobe__do_test [kprobe -> kprobe/do_test] */
SEC("kprobe/do_test")
int kprobe__do_test(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__do_test_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}
