// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 38_uprobe_basic.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @calls : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_38_uprobe_basic_top_calls SEC(".maps");

/* top-level ivar @last_ret : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_38_uprobe_basic_top_last_ret SEC(".maps");

/* top-level ivar @returns : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_38_uprobe_basic_top_returns SEC(".maps");

/* ctx for uprobe__readline — userspace fills before bpf_prog_test_run */
struct uprobe__readline_ctx {
    __s64 prompt;
};

/* ctx for uretprobe__readline — userspace fills before bpf_prog_test_run */
struct uretprobe__readline_ctx {
    __s64 ret;
};

/* impl: uprobe__readline : int  params: prompt: int */
static __noinline __s64 uprobe__readline_inner(__s64 prompt)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_38_uprobe_basic_top_calls, &_k1);
    __s64 _v3 = (_p2 ? *_p2 : 0) + (1);
    bpf_map_update_elem(&u_38_uprobe_basic_top_calls, &_k1, &_v3, BPF_ANY);
    return _v3;
}

/* entry wrapper: uprobe__readline [uprobe -> uprobe] */
SEC("uprobe")
int uprobe__readline(struct pt_regs *ctx)
{
    (void)ctx;
    (void)uprobe__readline_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}

/* impl: uretprobe__readline : int  params: ret: int */
static __noinline __s64 uretprobe__readline_inner(__s64 ret)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_38_uprobe_basic_top_returns, &_k1);
    __s64 _v3 = (_p2 ? *_p2 : 0) + (1);
    bpf_map_update_elem(&u_38_uprobe_basic_top_returns, &_k1, &_v3, BPF_ANY);
    __u32 _k4 = 0;
    __s64 _v5 = ret;
    bpf_map_update_elem(&u_38_uprobe_basic_top_last_ret, &_k4, &_v5, BPF_ANY);
    return _v5;
}

/* entry wrapper: uretprobe__readline [uretprobe -> uretprobe] */
SEC("uretprobe")
int uretprobe__readline(struct pt_regs *ctx)
{
    (void)ctx;
    (void)uretprobe__readline_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
