// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 44_reactor_block_params.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @sum : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_44_reactor_block_params_top_sum SEC(".maps");

/* ctx for uprobe__react0 — userspace fills before bpf_prog_test_run */
struct uprobe__react0_ctx {
    __s64 prompt;
};

/* impl: uprobe__react0 : int  params: prompt: int */
static __noinline __s64 uprobe__react0_inner(__s64 prompt)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_44_reactor_block_params_top_sum, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + prompt;
    bpf_map_update_elem(&u_44_reactor_block_params_top_sum, &_k3, &_v4, BPF_ANY);
    return _v4;
}

/* entry wrapper: uprobe__react0 [uprobe -> uprobe] */
SEC("uprobe")
int uprobe__react0(struct pt_regs *ctx)
{
    (void)ctx;
    (void)uprobe__react0_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
