// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 46_comm_builtins.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_46_comm_builtins_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_46_comm_builtins_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit int-event channel === */
struct u_46_comm_builtins_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_46_comm_builtins_events SEC(".maps");

/* === per-unit string-event channel === */
struct u_46_comm_builtins_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_46_comm_builtins_str_events SEC(".maps");

/* linear histogram (256 caller-bucketed slots). */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(key, __u32);
    __type(value, __u64);
    __uint(max_entries, 256);
} bpf_hist_lin SEC(".maps");

static __noinline __s64 spnl_hist_observe_linear(__s64 slot_arg)
{
    if (slot_arg < 0) return 0;
    __u32 slot = (__u32)slot_arg;
    if (slot >= 256) slot = 255;
    __u64 *cur = bpf_map_lookup_elem(&bpf_hist_lin, &slot);
    if (cur) __sync_fetch_and_add(cur, 1);
    return 0;
}

/* ctx for kprobe__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct kprobe__do_sys_openat2_ctx {
    __s64 dfd;
    __s64 filename;
};

/* ctx for kretprobe__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct kretprobe__do_sys_openat2_ctx {
    __s64 ret;
};

/* impl: kprobe__do_sys_openat2 : int  params: dfd: int, filename: int */
static __noinline __s64 kprobe__do_sys_openat2_inner(__s64 dfd, __s64 filename)
{
    spnl_hist_observe_linear(((__s64)((__u64)(((__s64)bpf_ktime_get_ns())) / (__u64)(1000))));
    {
        struct u_46_comm_builtins_str_event *_se1 = bpf_ringbuf_reserve(&u_46_comm_builtins_str_events, sizeof(*_se1), 0);
        if (_se1) {
            _se1->hdr.type = SPNL_EVT_USER_BASE;
            _se1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _se1->hdr.reserved = 0;
            _se1->hdr.timestamp = bpf_ktime_get_ns();
            bpf_get_current_comm(_se1->str, sizeof(_se1->str));
            bpf_ringbuf_submit(_se1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kprobe__do_sys_openat2 [kprobe -> kprobe/do_sys_openat2] */
SEC("kprobe/do_sys_openat2")
int kprobe__do_sys_openat2(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__do_sys_openat2_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx));
    return 0;
}

/* impl: kretprobe__do_sys_openat2 : int  params: ret: int */
static __noinline __s64 kretprobe__do_sys_openat2_inner(__s64 ret)
{
    char _ch1[16] = {0};
    bpf_get_current_comm(_ch1, sizeof(_ch1));
    {
        struct u_46_comm_builtins_event *_e2 = bpf_ringbuf_reserve(&u_46_comm_builtins_events, sizeof(*_e2), 0);
        if (_e2) {
            _e2->hdr.type = SPNL_EVT_USER_BASE;
            _e2->hdr.version = SPNL_EVENT_HDR_VERSION;
            _e2->hdr.reserved = 0;
            _e2->hdr.timestamp = bpf_ktime_get_ns();
            _e2->value = ((__s64)(*((__u64 *)_ch1)));
            bpf_ringbuf_submit(_e2, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    return 0;
}

/* entry wrapper: kretprobe__do_sys_openat2 [kretprobe -> kretprobe/do_sys_openat2] */
SEC("kretprobe/do_sys_openat2")
int kretprobe__do_sys_openat2(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kretprobe__do_sys_openat2_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
