// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 47_reactor_pid.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/usdt.bpf.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @hits : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_47_reactor_pid_top_hits SEC(".maps");

/* top-level ivar @throws : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_47_reactor_pid_top_throws SEC(".maps");

/* ctx for uprobe__react0 — userspace fills before bpf_prog_test_run */
struct uprobe__react0_ctx {
    __s64 prompt;
};

/* ctx for usdt__react__1 — userspace fills before bpf_prog_test_run */
struct usdt__react__1_ctx {
    __s64 obj;
    __s64 tinfo;
    __s64 dest;
};

/* impl: uprobe__react0 : int  params: prompt: int */
static __noinline __s64 uprobe__react0_inner(__s64 prompt)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_47_reactor_pid_top_hits, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_47_reactor_pid_top_hits, &_k3, &_v4, BPF_ANY);
    return _v4;
}

/* entry wrapper: uprobe__react0 [uprobe -> uprobe] */
SEC("uprobe")
int uprobe__react0(struct pt_regs *ctx)
{
    (void)ctx;
    (void)uprobe__react0_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}

/* impl: usdt__react__1 : int  params: obj: int, tinfo: int, dest: int */
static __noinline __s64 usdt__react__1_inner(__s64 obj, __s64 tinfo, __s64 dest)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_47_reactor_pid_top_throws, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_47_reactor_pid_top_throws, &_k3, &_v4, BPF_ANY);
    return _v4;
}

/* entry wrapper: usdt__react__1 [usdt -> usdt] */
SEC("usdt")
int usdt__react__1(struct pt_regs *ctx)
{
    (void)ctx;
    long _usdt_arg0 = 0; (void)bpf_usdt_arg(ctx, 0, &_usdt_arg0);
    long _usdt_arg1 = 0; (void)bpf_usdt_arg(ctx, 1, &_usdt_arg1);
    long _usdt_arg2 = 0; (void)bpf_usdt_arg(ctx, 2, &_usdt_arg2);
    (void)usdt__react__1_inner((__s64)_usdt_arg0, (__s64)_usdt_arg1, (__s64)_usdt_arg2);
    return 0;
}
