// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 50_reactor_named_tp.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @last_next : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_50_reactor_named_tp_top_last_next SEC(".maps");

/* top-level ivar @last_prev : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_50_reactor_named_tp_top_last_prev SEC(".maps");

/* top-level ivar @switches : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_50_reactor_named_tp_top_switches SEC(".maps");

/* ctx for tracepoint__sched__sched_switch — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_switch_ctx {
    __s64 prev_pid;
    __s64 next_pid;
};

/* impl: tracepoint__sched__sched_switch : int  params: prev_pid: int, next_pid: int */
static __noinline __s64 tracepoint__sched__sched_switch_inner(__s64 prev_pid, __s64 next_pid)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_50_reactor_named_tp_top_switches, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_50_reactor_named_tp_top_switches, &_k3, &_v4, BPF_ANY);
    __u32 _k5 = 0;
    __s64 _v6 = prev_pid;
    bpf_map_update_elem(&u_50_reactor_named_tp_top_last_prev, &_k5, &_v6, BPF_ANY);
    __u32 _k7 = 0;
    __s64 _v8 = next_pid;
    bpf_map_update_elem(&u_50_reactor_named_tp_top_last_next, &_k7, &_v8, BPF_ANY);
    return _v8;
}

/* entry wrapper: tracepoint__sched__sched_switch [tracepoint -> tracepoint/sched/sched_switch] */
SEC("tracepoint/sched/sched_switch")
int tracepoint__sched__sched_switch(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_switch_inner((__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_pid, (__s64)((struct trace_event_raw_sched_switch *)ctx)->next_pid);
    return 0;
}
