// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 52_off_cpu.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* per-unit log2 histogram (64 buckets). */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(key, __u32);
    __type(value, __u64);
    __uint(max_entries, 64);
} bpf_hist SEC(".maps");

/* Verifier-safe integer log2: returns floor(log2(v)) clamped to
 * [0, HISTOGRAM_SLOTS-1]. v<=0 maps to slot 0 so callers don't have
 * to guard against zero observations (it just over-reports the
 * smallest bucket). All comparisons are against compile-time
 * constants so the verifier sees a bounded computation. */
static __noinline __s64 spnl_hist_log2(__s64 v)
{
    __s64 r = 0;
    if (v <= 1) return 0;
    if (v >= (1LL << 32)) { v >>= 32; r += 32; }
    if (v >= (1   << 16)) { v >>= 16; r += 16; }
    if (v >= (1   << 8))  { v >>= 8;  r += 8;  }
    if (v >= (1   << 4))  { v >>= 4;  r += 4;  }
    if (v >= (1   << 2))  { v >>= 2;  r += 2;  }
    if (v >= (1   << 1))  { v >>= 1;  r += 1;  }
    if (r > 63) r = 63;
    return r;
}

static __noinline __s64 spnl_hist_observe(__s64 v)
{
    __u32 slot = (__u32)spnl_hist_log2(v);
    if (slot >= 64) return 0;  /* verifier hand-holding */
    __u64 *cur = bpf_map_lookup_elem(&bpf_hist, &slot);
    if (cur) __sync_fetch_and_add(cur, 1);
    return 0;
}

/* keyed log2 histogram (1024 keys * 64 slots).
 * The value struct is 512 bytes - too large to put on the BPF
 * stack (512B limit). We stash a pre-zeroed template in a per-CPU
 * ARRAY of size 1 and use it for new-key initialization. */
struct spnl_hist_struct { __u64 buckets[64]; };

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);
    __type(value, struct spnl_hist_struct);
    __uint(max_entries, 1024);
} bpf_hist_keyed SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __type(key, __u32);
    __type(value, struct spnl_hist_struct);
    __uint(max_entries, 1);
} bpf_hist_keyed_zero SEC(".maps");

static __noinline __s64 spnl_hist_observe_by(__s64 key, __s64 v)
{
    __u64 k = (__u64)key;
    struct spnl_hist_struct *cur = bpf_map_lookup_elem(&bpf_hist_keyed, &k);
    if (!cur) {
        __u32 zk = 0;
        struct spnl_hist_struct *zero =
            bpf_map_lookup_elem(&bpf_hist_keyed_zero, &zk);
        if (!zero) return 0;
        bpf_map_update_elem(&bpf_hist_keyed, &k, zero, BPF_NOEXIST);
        cur = bpf_map_lookup_elem(&bpf_hist_keyed, &k);
        if (!cur) return 0;
    }
    __u32 slot = (__u32)spnl_hist_log2(v);
    if (slot >= 64) return 0;
    __sync_fetch_and_add(&cur->buckets[slot], 1);
    return 0;
}

/* per-unit stack-trace map (16384 unique stacks * 127 frames each).
 * stack_id() returns the kernel stack id, user_stack_id() returns the
 * userspace one. Host code reads the map by stack id to get the PCs. */
struct {
    __uint(type, BPF_MAP_TYPE_STACK_TRACE);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, 127 * sizeof(__u64));
    __uint(max_entries, 16384);
} bpf_stacks SEC(".maps");

/* per-unit off-CPU tracking (ts + stack id per pid).
 * off_cpu_start(pid) records when a task goes off-CPU; off_cpu_observe(pid)
 * fires when it comes back, bins (stack_id -> total off-CPU ns) via
 * the keyed hist. */
struct spnl_off_cpu_entry {
    __u64 ts;
    __u32 stack_id;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, struct spnl_off_cpu_entry);
    __uint(max_entries, 10240);
} bpf_off_cpu SEC(".maps");

/* off_cpu_start: capture (ktime_ns, stack_id) for the going-off task.
 * ctx must be the program's bpf_get_stackid-compatible context. */
static __noinline __s64 spnl_off_cpu_start(__u32 pid, void *ctx)
{
    struct spnl_off_cpu_entry e;
    e.ts       = bpf_ktime_get_ns();
    e.stack_id = (__u32)bpf_get_stackid(ctx, &bpf_stacks, 0);
    bpf_map_update_elem(&bpf_off_cpu, &pid, &e, BPF_ANY);
    return 0;
}

/* off_cpu_observe: if pid has a stored entry, compute delta = now - ts,
 * bin into the keyed log2 hist under key=stack_id, then drop the
 * entry. Returns delta ns (or 0 if no entry). */
static __noinline __s64 spnl_off_cpu_observe(__u32 pid)
{
    struct spnl_off_cpu_entry *e =
        bpf_map_lookup_elem(&bpf_off_cpu, &pid);
    if (!e) return 0;
    __u64 delta    = bpf_ktime_get_ns() - e->ts;
    __u32 stack_id = e->stack_id;
    bpf_map_delete_elem(&bpf_off_cpu, &pid);

    /* Inline hist_observe_by(stack_id, delta) - keyed log2 hist. */
    __u64 k = (__u64)stack_id;
    struct spnl_hist_struct *cur =
        bpf_map_lookup_elem(&bpf_hist_keyed, &k);
    if (!cur) {
        __u32 zk = 0;
        struct spnl_hist_struct *zero =
            bpf_map_lookup_elem(&bpf_hist_keyed_zero, &zk);
        if (!zero) return (__s64)delta;
        bpf_map_update_elem(&bpf_hist_keyed, &k, zero, BPF_NOEXIST);
        cur = bpf_map_lookup_elem(&bpf_hist_keyed, &k);
        if (!cur) return (__s64)delta;
    }
    __u32 slot = (__u32)spnl_hist_log2((__s64)delta);
    if (slot >= 64) return (__s64)delta;
    __sync_fetch_and_add(&cur->buckets[slot], 1);
    return (__s64)delta;
}

/* ctx for tracepoint__sched__sched_switch — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_switch_ctx {
    __s64 prev_pid;
    __s64 prev_state;
    __s64 next_pid;
};

/* impl: tracepoint__sched__sched_switch : int  params: prev_pid: int, prev_state: int, next_pid: int */
static __noinline __s64 tracepoint__sched__sched_switch_inner(void *ctx, __s64 prev_pid, __s64 prev_state, __s64 next_pid)
{
    __s64 _if1 = 0;
    if (prev_state != 0) {
        spnl_off_cpu_start((__u32)(prev_pid), ctx);
        _if1 = 0;
    }
    return spnl_off_cpu_observe((__u32)(next_pid));
}

/* entry wrapper: tracepoint__sched__sched_switch [tracepoint -> tracepoint/sched/sched_switch] */
SEC("tracepoint/sched/sched_switch")
int tracepoint__sched__sched_switch(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_switch_inner(ctx, (__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_pid, (__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_state, (__s64)((struct trace_event_raw_sched_switch *)ctx)->next_pid);
    return 0;
}
