// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 53_scx_simple.rb
// ebpf-eligible methods: 3, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* sched_ext constant macros. scx_bpf_* kfunc declarations
 * already live in vmlinux.h (BTF-generated, marked __weak __ksym),
 * so we don't redeclare them here. */

/* SCX DSQ id helpers (see kernel: include/linux/sched/ext.h). */
#ifndef SCX_DSQ_FLAG_BUILTIN
#define SCX_DSQ_FLAG_BUILTIN (1ULL << 63)
#endif
#ifndef SCX_DSQ_GLOBAL
#define SCX_DSQ_GLOBAL   (SCX_DSQ_FLAG_BUILTIN | 1ULL)
#endif
#ifndef SCX_DSQ_LOCAL
#define SCX_DSQ_LOCAL    (SCX_DSQ_FLAG_BUILTIN | 0ULL)
#endif
#ifndef SCX_SLICE_DFL
#define SCX_SLICE_DFL    20000000ULL    /* 20 ms */
#endif
#ifndef SCX_SLICE_INF
#define SCX_SLICE_INF    (~0ULL)
#endif
#ifndef SCX_KICK_PREEMPT
#define SCX_KICK_PREEMPT (1U << 0)
#endif
#ifndef SCX_ENQ_PREEMPT
#define SCX_ENQ_PREEMPT  (1ULL << 32)
#endif

/* ctx for sched_ext__enqueue — userspace fills before bpf_prog_test_run */
struct sched_ext__enqueue_ctx {
    __s64 p;
    __s64 enq_flags;
};

/* ctx for sched_ext__dispatch — userspace fills before bpf_prog_test_run */
struct sched_ext__dispatch_ctx {
    __s64 cpu;
    __s64 prev;
};

/* impl: sched_ext__enqueue */
static __noinline __s64 sched_ext__enqueue_inner(__s64 p, __s64 enq_flags)
{
    scx_bpf_dsq_insert((struct task_struct *)(unsigned long)(p), SCX_DSQ_GLOBAL, SCX_SLICE_DFL, enq_flags);
    return 0;
}

/* entry: SEC("struct_ops/enqueue") for sched_ext_ops */
SEC("struct_ops/enqueue")
void BPF_PROG(sched_ext__enqueue, struct task_struct *p, __u64 enq_flags)
{
    (void)sched_ext__enqueue_inner((__s64)(unsigned long)p, (__s64)(unsigned long)enq_flags);
}

/* impl: sched_ext__dispatch */
static __noinline __s64 sched_ext__dispatch_inner(__s64 cpu, __s64 prev)
{
    return ((__s64)scx_bpf_dsq_move_to_local(SCX_DSQ_GLOBAL));
}

/* entry: SEC("struct_ops/dispatch") for sched_ext_ops */
SEC("struct_ops/dispatch")
void BPF_PROG(sched_ext__dispatch, __s32 cpu, struct task_struct *prev)
{
    (void)sched_ext__dispatch_inner((__s64)(unsigned long)cpu, (__s64)(unsigned long)prev);
}

/* impl: sched_ext__init */
static __noinline __s64 sched_ext__init_inner(void)
{
    return 0;
}

/* entry: SEC("struct_ops.s/init") for sched_ext_ops */
SEC("struct_ops.s/init")
__s32 BPF_PROG(sched_ext__init)
{
    return (__s32)sched_ext__init_inner();
}

/* struct_ops registration for sched_ext_ops. */
SEC(".struct_ops.link")
struct sched_ext_ops spnl_sched_ext_ops = {
    .enqueue = (void *)sched_ext__enqueue,
    .dispatch = (void *)sched_ext__dispatch,
    .init = (void *)sched_ext__init,
    .name = "spnl_sx",
};
