// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 55_qdisc_fifo.rb
// ebpf-eligible methods: 5, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* bpf_list/bpf_obj/kptr helper machinery for BPF qdiscs. */
#ifndef __contains
#define __contains(name, node) __attribute__((btf_decl_tag("contains:" #name ":" #node)))
#endif
#ifndef __kptr
#define __kptr __attribute__((btf_type_tag("kptr")))
#endif
#ifndef private
#define private(name) SEC(".data." #name) __hidden __attribute__((aligned(8)))
#endif
#ifndef bpf_obj_new
#define bpf_obj_new(type)              ((type *)bpf_obj_new_impl(bpf_core_type_id_local(type), NULL))
#endif
#ifndef bpf_obj_drop
#define bpf_obj_drop(kptr)             bpf_obj_drop_impl(kptr, NULL)
#endif
#ifndef bpf_list_push_back
#define bpf_list_push_back(head, node) bpf_list_push_back_impl(head, node, NULL, 0)
#endif
#ifndef container_of
#define container_of(ptr, type, member) ((type *)((char *)(ptr) - __builtin_offsetof(type, member)))
#endif

/* Wrapper struct holding one skb in a bpf_list. The __kptr tag
 * tells the verifier that this field owns a kernel sk_buff that
 * must be released via bpf_kptr_xchg before the wrapper is freed. */
struct spnl_qdisc_skb_node {
    struct bpf_list_node node;
    struct sk_buff __kptr *skb;
};

/* Per-unit single queue (spin_lock + list_head pair). The
 * __contains tag wires the list head to skb_node.node so the
 * verifier knows which container type the list holds. */
private(A) struct bpf_spin_lock spnl_qdisc_q_lock;
private(A) struct bpf_list_head spnl_qdisc_q_head __contains(spnl_qdisc_skb_node, node);

/* top-level ivar @dequeued : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_55_qdisc_fifo_top_dequeued SEC(".maps");

/* top-level ivar @enqueued : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_55_qdisc_fifo_top_enqueued SEC(".maps");

/* ctx for qdisc__init — userspace fills before bpf_prog_test_run */
struct qdisc__init_ctx {
    __s64 sch;
    __s64 opt;
    __s64 extack;
};

/* ctx for qdisc__enqueue — userspace fills before bpf_prog_test_run */
struct qdisc__enqueue_ctx {
    __s64 skb;
    __s64 sch;
    __s64 to_free;
};

/* ctx for qdisc__dequeue — userspace fills before bpf_prog_test_run */
struct qdisc__dequeue_ctx {
    __s64 sch;
};

/* ctx for qdisc__reset — userspace fills before bpf_prog_test_run */
struct qdisc__reset_ctx {
    __s64 sch;
};

/* ctx for qdisc__destroy — userspace fills before bpf_prog_test_run */
struct qdisc__destroy_ctx {
    __s64 sch;
};

/* impl: qdisc__init */
static __noinline __s64 qdisc__init_inner(__s64 sch, __s64 opt, __s64 extack)
{
    return 0;
}

/* entry: SEC("struct_ops/init") for Qdisc_ops */
SEC("struct_ops/init")
int BPF_PROG(qdisc__init, struct Qdisc *sch, struct nlattr *opt, struct netlink_ext_ack *extack)
{
    return (int)qdisc__init_inner((__s64)(unsigned long)sch, (__s64)(unsigned long)opt, (__s64)(unsigned long)extack);
}

/* impl: qdisc__enqueue */
static __noinline __s64 qdisc__enqueue_inner(__s64 skb, __s64 sch, __s64 to_free)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_55_qdisc_fifo_top_enqueued, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_55_qdisc_fifo_top_enqueued, &_k3, &_v4, BPF_ANY);
    __s64 _qp_ret5 = 1;  /* NET_XMIT_DROP unless we make it through */
    do {
        struct spnl_qdisc_skb_node *_qpn = bpf_obj_new(typeof(*_qpn));
        if (!_qpn) {
            bpf_qdisc_skb_drop((struct sk_buff *)(unsigned long)(skb), (struct bpf_sk_buff_ptr *)(unsigned long)(to_free));
            break;
        }
        struct sk_buff *_swap = bpf_kptr_xchg(&_qpn->skb, (struct sk_buff *)(unsigned long)(skb));
        if (_swap) {
            bpf_qdisc_skb_drop(_swap, (struct bpf_sk_buff_ptr *)(unsigned long)(to_free));
            bpf_obj_drop(_qpn);
            break;
        }
        bpf_spin_lock(&spnl_qdisc_q_lock);
        bpf_list_push_back(&spnl_qdisc_q_head, &_qpn->node);
        bpf_spin_unlock(&spnl_qdisc_q_lock);
        _qp_ret5 = 0;  /* NET_XMIT_SUCCESS */
    } while (0);
    return _qp_ret5;
}

/* entry: SEC("struct_ops/enqueue") for Qdisc_ops */
SEC("struct_ops/enqueue")
int BPF_PROG(qdisc__enqueue, struct sk_buff *skb, struct Qdisc *sch, struct sk_buff **to_free)
{
    return (int)qdisc__enqueue_inner((__s64)(unsigned long)skb, (__s64)(unsigned long)sch, (__s64)(unsigned long)to_free);
}

/* impl: qdisc__dequeue */
static __noinline __s64 qdisc__dequeue_inner(__s64 sch)
{
    __s64 skb = 0;
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_55_qdisc_fifo_top_dequeued, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_55_qdisc_fifo_top_dequeued, &_k3, &_v4, BPF_ANY);
    __s64 _qpop_ret5 = 0;
    do {
        struct bpf_list_node *_qpn = NULL;
        struct sk_buff *_qpr = NULL;
        bpf_spin_lock(&spnl_qdisc_q_lock);
        _qpn = bpf_list_pop_front(&spnl_qdisc_q_head);
        bpf_spin_unlock(&spnl_qdisc_q_lock);
        if (!_qpn) break;
        struct spnl_qdisc_skb_node *_qps = container_of(_qpn, struct spnl_qdisc_skb_node, node);
        _qpr = bpf_kptr_xchg(&_qps->skb, NULL);
        bpf_obj_drop(_qps);
        _qpop_ret5 = (__s64)(unsigned long)_qpr;
    } while (0);
    skb = _qpop_ret5;
    __s64 _if6 = 0;
    if (skb != 0) {
        bpf_qdisc_bstats_update((struct Qdisc *)(unsigned long)(sch), (const struct sk_buff *)(unsigned long)(skb));
        _if6 = 0;
    }
    return skb;
}

/* entry: SEC("struct_ops/dequeue") for Qdisc_ops */
SEC("struct_ops/dequeue")
struct sk_buff * BPF_PROG(qdisc__dequeue, struct Qdisc *sch)
{
    return (struct sk_buff *)(unsigned long)qdisc__dequeue_inner((__s64)(unsigned long)sch);
}

/* impl: qdisc__reset */
static __noinline __s64 qdisc__reset_inner(__s64 sch)
{
    return 0;
}

/* entry: SEC("struct_ops/reset") for Qdisc_ops */
SEC("struct_ops/reset")
void BPF_PROG(qdisc__reset, struct Qdisc *sch)
{
    (void)qdisc__reset_inner((__s64)(unsigned long)sch);
}

/* impl: qdisc__destroy */
static __noinline __s64 qdisc__destroy_inner(__s64 sch)
{
    return 0;
}

/* entry: SEC("struct_ops/destroy") for Qdisc_ops */
SEC("struct_ops/destroy")
void BPF_PROG(qdisc__destroy, struct Qdisc *sch)
{
    (void)qdisc__destroy_inner((__s64)(unsigned long)sch);
}

/* struct_ops registration for Qdisc_ops. */
SEC(".struct_ops.link")
struct Qdisc_ops spnl_qdisc_ops = {
    .init = (void *)qdisc__init,
    .enqueue = (void *)qdisc__enqueue,
    .dequeue = (void *)qdisc__dequeue,
    .reset = (void *)qdisc__reset,
    .destroy = (void *)qdisc__destroy,
    .id = "spnl_qdisc",
};
