// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 56_kfield.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @calls : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_56_kfield_top_calls SEC(".maps");

/* top-level ivar @rcvbuf : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_56_kfield_top_rcvbuf SEC(".maps");

/* top-level ivar @sndbuf : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_56_kfield_top_sndbuf SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk)
{
    __s64 s = 0;
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_56_kfield_top_calls, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_56_kfield_top_calls, &_k3, &_v4, BPF_ANY);
    __u32 _k5 = 0;
    __s64 _v6 = ((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(sk), sk_sndbuf));
    bpf_map_update_elem(&u_56_kfield_top_sndbuf, &_k5, &_v6, BPF_ANY);
    s = ((__s64)(sk));
    __u32 _k7 = 0;
    __s64 _v8 = ((__s64)BPF_CORE_READ((struct sock *)(unsigned long)(s), sk_rcvbuf));
    bpf_map_update_elem(&u_56_kfield_top_rcvbuf, &_k7, &_v8, BPF_ANY);
    return _v8;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
