// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 57_cidr_blocklist.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @blocked_hits : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_57_cidr_blocklist_top_blocked_hits SEC(".maps");

/* top-level ivar @passed_hits : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_57_cidr_blocklist_top_passed_hits SEC(".maps");

/* IPv4 source address in host byte order, or 0 if not IPv4. */
static __noinline __s64 spnl_tc_pkt_ip4_src(struct __sk_buff *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto != bpf_htons(0x0800)) return 0;
    struct iphdr *iph = (void *)(eth + 1);
    if ((void *)(iph + 1) > data_end) return 0;
    return (__s64)bpf_ntohl(iph->saddr);
}

/* per-unit CIDR blocklist (LPM_TRIE). Populated from userspace via
 * sp_bpf_cidr_blocklist_add(ip_host_order, prefixlen) / _del, read from
 * BPF via spnl_cidr_blocklist_match(ip_host_order). The key's data[] is
 * big-endian (network order) - the trie matches bits MSB-first. */
struct spnl_cidr_key {
    __u32 prefixlen;
    __u8  data[4];
};
struct {
    __uint(type, BPF_MAP_TYPE_LPM_TRIE);
    __type(key, struct spnl_cidr_key);
    __type(value, __u8);
    __uint(max_entries, 8192);
    __uint(map_flags, BPF_F_NO_PREALLOC);
} bpf_cidr_block SEC(".maps");

static __noinline __s64 spnl_cidr_blocklist_match(__s64 ip_host_order)
{
    struct spnl_cidr_key k;
    __u32 ip = (__u32)ip_host_order;
    k.prefixlen = 32;
    k.data[0] = (__u8)((ip >> 24) & 0xff);
    k.data[1] = (__u8)((ip >> 16) & 0xff);
    k.data[2] = (__u8)((ip >> 8) & 0xff);
    k.data[3] = (__u8)(ip & 0xff);
    __u8 *v = bpf_map_lookup_elem(&bpf_cidr_block, &k);
    return v ? 1 : 0;
}

/* impl: tc__ingress__cidr_filter : int */
static __noinline __s64 tc__ingress__cidr_filter_inner(struct __sk_buff *ctx)
{
    __s64 _if1 = 0;
    if (spnl_cidr_blocklist_match(spnl_tc_pkt_ip4_src(ctx)) == 1) {
        __u32 _k2 = 0;
        __s64 *_p3 = bpf_map_lookup_elem(&u_57_cidr_blocklist_top_blocked_hits, &_k2);
        __u32 _k4 = 0;
        __s64 _v5 = (_p3 ? *_p3 : 0) + 1;
        bpf_map_update_elem(&u_57_cidr_blocklist_top_blocked_hits, &_k4, &_v5, BPF_ANY);
        _if1 = 2;
    } else {
        __u32 _k6 = 0;
        __s64 *_p7 = bpf_map_lookup_elem(&u_57_cidr_blocklist_top_passed_hits, &_k6);
        __u32 _k8 = 0;
        __s64 _v9 = (_p7 ? *_p7 : 0) + 1;
        bpf_map_update_elem(&u_57_cidr_blocklist_top_passed_hits, &_k8, &_v9, BPF_ANY);
        _if1 = 0;
    }
    return _if1;
}

/* entry wrapper: tc__ingress__cidr_filter [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__cidr_filter(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__cidr_filter_inner(ctx);
}
