// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 61_cgroup_connect4.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* impl: cgroup__connect4__guard : int */
static __noinline __s64 cgroup__connect4__guard_inner(struct bpf_sock_addr *ctx)
{
    __s64 _if1 = 0;
    if (((__s64)(__u32)__builtin_bswap16((__u16)ctx->user_port)) == 9999) {
        _if1 = 0;
    } else {
        _if1 = 1;
    }
    return _if1;
}

/* entry wrapper: cgroup__connect4__guard [cgroup_connect4 -> cgroup/connect4] */
SEC("cgroup/connect4")
int cgroup__connect4__guard(struct bpf_sock_addr *ctx)
{
    (void)ctx;
    return (int)cgroup__connect4__guard_inner(ctx);
}
