// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 63_queue_stack.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @last_popped : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_63_queue_stack_top_last_popped SEC(".maps");

/* QUEUE (FIFO) map. fifo_push(v) / fifo_pop(). */
struct {
    __uint(type, BPF_MAP_TYPE_QUEUE);
    __uint(max_entries, 1024);
    __type(value, __s64);
} bpf_fifo SEC(".maps");

static __always_inline __s64 spnl_fifo_push(__s64 v)
{
    return (__s64)bpf_map_push_elem(&bpf_fifo, &v, BPF_ANY);
}
static __always_inline __s64 spnl_fifo_pop(void)
{
    __s64 v = 0;
    return bpf_map_pop_elem(&bpf_fifo, &v) == 0 ? v : 0;
}

/* STACK (LIFO) map. lifo_push(v) / lifo_pop(). */
struct {
    __uint(type, BPF_MAP_TYPE_STACK);
    __uint(max_entries, 1024);
    __type(value, __s64);
} bpf_lifo SEC(".maps");

static __always_inline __s64 spnl_lifo_push(__s64 v)
{
    return (__s64)bpf_map_push_elem(&bpf_lifo, &v, BPF_ANY);
}
static __always_inline __s64 spnl_lifo_pop(void)
{
    __s64 v = 0;
    return bpf_map_pop_elem(&bpf_lifo, &v) == 0 ? v : 0;
}

/* ctx for fentry__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct fentry__do_sys_openat2_ctx {
    __s64 dfd;
};

/* ctx for fexit__do_sys_openat2 — userspace fills before bpf_prog_test_run */
struct fexit__do_sys_openat2_ctx {
    __s64 dfd;
    __s64 ret;
};

/* impl: fentry__do_sys_openat2 : int  params: dfd: int */
static __noinline __s64 fentry__do_sys_openat2_inner(__s64 dfd)
{
    (void)(spnl_fifo_push(42));
    return spnl_lifo_push(7);
}

/* entry wrapper: fentry__do_sys_openat2 [fentry -> fentry/do_sys_openat2] */
SEC("fentry/do_sys_openat2")
int fentry__do_sys_openat2(__u64 *ctx)
{
    (void)ctx;
    (void)fentry__do_sys_openat2_inner((__s64)ctx[0]);
    return 0;
}

/* impl: fexit__do_sys_openat2 : int  params: dfd: int, ret: int */
static __noinline __s64 fexit__do_sys_openat2_inner(__s64 dfd, __s64 ret)
{
    __u32 _k1 = 0;
    __s64 _v2 = spnl_fifo_pop();
    bpf_map_update_elem(&u_63_queue_stack_top_last_popped, &_k1, &_v2, BPF_ANY);
    return _v2;
}

/* entry wrapper: fexit__do_sys_openat2 [fexit -> fexit/do_sys_openat2] */
SEC("fexit/do_sys_openat2")
int fexit__do_sys_openat2(__u64 *ctx)
{
    (void)ctx;
    (void)fexit__do_sys_openat2_inner((__s64)ctx[0], (__s64)ctx[1]);
    return 0;
}
