// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 64_xsk_dev_redirect.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* L4 protocol (TCP=6, UDP=17, ICMP=1, ICMPv6=58), or 0 if not
 * IPv4 nor IPv6 / truncated.
 * For IPv6 we return ip6h->nexthdr directly - if it's an
 * extension header (Hop-by-Hop=0, Routing=43, Fragment=44, ...)
 * the caller sees that value as-is (extension header walking is
 * out of scope for this builtin). */
static __noinline __s64 spnl_pkt_l4_proto(struct xdp_md *ctx)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return 0;
    if (eth->h_proto == bpf_htons(0x0800)) {  /* ETH_P_IP */
        struct iphdr *iph = (void *)(eth + 1);
        if ((void *)(iph + 1) > data_end) return 0;
        return (__s64)iph->protocol;
    }
    if (eth->h_proto == bpf_htons(0x86DD)) {  /* ETH_P_IPV6 */
        struct ipv6hdr *ip6h = (void *)(eth + 1);
        if ((void *)(ip6h + 1) > data_end) return 0;
        return (__s64)ip6h->nexthdr;
    }
    return 0;
}

/* XSKMAP for AF_XDP zero-copy redirect to user sockets. */
struct {
    __uint(type, BPF_MAP_TYPE_XSKMAP);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
    __uint(max_entries, 64);
} bpf_xskmap SEC(".maps");

/* DEVMAP for XDP redirect to another net device (ifindex). */
struct {
    __uint(type, BPF_MAP_TYPE_DEVMAP);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
    __uint(max_entries, 64);
} bpf_devmap SEC(".maps");

/* impl: xdp__redir : int */
static __noinline __s64 xdp__redir_inner(struct xdp_md *ctx)
{
    __s64 p = 0;
    p = spnl_pkt_l4_proto(ctx);
    __s64 _if1 = 0;
    if (p == 6) {
        _if1 = (__s64)bpf_redirect_map(&bpf_xskmap, (__u32)(0), XDP_PASS);
    } else {
        __s64 _if2 = 0;
        if (p == 17) {
            _if2 = (__s64)bpf_redirect_map(&bpf_devmap, (__u32)(0), 0);
        } else {
            _if2 = 2;
        }
        _if1 = _if2;
    }
    return _if1;
}

/* entry wrapper: xdp__redir [xdp -> xdp] */
SEC("xdp")
int xdp__redir(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__redir_inner(ctx);
}
