// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 65_raw_tp.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @syscalls : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_65_raw_tp_top_syscalls SEC(".maps");

/* impl: raw_tp__sys_enter : int */
static __noinline __s64 raw_tp__sys_enter_inner(void)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_65_raw_tp_top_syscalls, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_65_raw_tp_top_syscalls, &_k3, &_v4, BPF_ANY);
    return _v4;
}

/* entry wrapper: raw_tp__sys_enter [raw_tp -> raw_tp/sys_enter] */
SEC("raw_tp/sys_enter")
int raw_tp__sys_enter(struct bpf_raw_tracepoint_args *ctx)
{
    (void)ctx;
    (void)raw_tp__sys_enter_inner();
    return 0;
}
