// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 67_memleak.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* per-unit outstanding-allocation map for memleak-style tools.
 * key = allocation pointer, value = {size, stack_id}. Host reads the
 * surviving entries (= un-freed allocations) and groups by stack_id. */
struct spnl_alloc_info {
    __s64 size;
    __s64 stack_id;
};
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);
    __type(value, struct spnl_alloc_info);
    __uint(max_entries, 262144);
} bpf_allocs SEC(".maps");

static __noinline __s64 spnl_leak_record(__s64 ptr, __s64 size, __s64 stack_id)
{
    __u64 k = (__u64)ptr;
    struct spnl_alloc_info info = {};
    info.size = size;
    info.stack_id = stack_id;
    bpf_map_update_elem(&bpf_allocs, &k, &info, BPF_ANY);
    return 0;
}

static __noinline __s64 spnl_leak_forget(__s64 ptr)
{
    __u64 k = (__u64)ptr;
    bpf_map_delete_elem(&bpf_allocs, &k);
    return 0;
}

/* per-unit stack-trace map (16384 unique stacks * 127 frames each).
 * stack_id() returns the kernel stack id, user_stack_id() returns the
 * userspace one. Host code reads the map by stack id to get the PCs. */
struct {
    __uint(type, BPF_MAP_TYPE_STACK_TRACE);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, 127 * sizeof(__u64));
    __uint(max_entries, 16384);
} bpf_stacks SEC(".maps");

/* ctx for tracepoint__kmem__kmalloc — userspace fills before bpf_prog_test_run */
struct tracepoint__kmem__kmalloc_ctx {
    __s64 call_site;
    __s64 ptr;
    __s64 bytes_req;
    __s64 bytes_alloc;
    __s64 gfp_flags;
    __s64 node;
};

/* ctx for tracepoint__kmem__kfree — userspace fills before bpf_prog_test_run */
struct tracepoint__kmem__kfree_ctx {
    __s64 call_site;
    __s64 ptr;
};

/* impl: tracepoint__kmem__kmalloc : int  params: call_site: int, ptr: int, bytes_req: int, bytes_alloc: int, gfp_flags: int, node: int */
static __noinline __s64 tracepoint__kmem__kmalloc_inner(void *ctx, __s64 call_site, __s64 ptr, __s64 bytes_req, __s64 bytes_alloc, __s64 gfp_flags, __s64 node)
{
    spnl_leak_record(ptr, bytes_alloc, ((__s64)bpf_get_stackid(ctx, &bpf_stacks, 0)));
    return 0;
}

/* entry wrapper: tracepoint__kmem__kmalloc [tracepoint -> tracepoint/kmem/kmalloc] */
SEC("tracepoint/kmem/kmalloc")
int tracepoint__kmem__kmalloc(void *ctx)
{
    (void)ctx;
    (void)tracepoint__kmem__kmalloc_inner(ctx, (__s64)((struct trace_event_raw_kmalloc *)ctx)->call_site, (__s64)((struct trace_event_raw_kmalloc *)ctx)->ptr, (__s64)((struct trace_event_raw_kmalloc *)ctx)->bytes_req, (__s64)((struct trace_event_raw_kmalloc *)ctx)->bytes_alloc, (__s64)((struct trace_event_raw_kmalloc *)ctx)->gfp_flags, (__s64)((struct trace_event_raw_kmalloc *)ctx)->node);
    return 0;
}

/* impl: tracepoint__kmem__kfree : int  params: call_site: int, ptr: int */
static __noinline __s64 tracepoint__kmem__kfree_inner(void *ctx, __s64 call_site, __s64 ptr)
{
    spnl_leak_forget(ptr);
    return 0;
}

/* entry wrapper: tracepoint__kmem__kfree [tracepoint -> tracepoint/kmem/kfree] */
SEC("tracepoint/kmem/kfree")
int tracepoint__kmem__kfree(void *ctx)
{
    (void)ctx;
    (void)tracepoint__kmem__kfree_inner(ctx, (__s64)((struct trace_event_raw_kfree *)ctx)->call_site, (__s64)((struct trace_event_raw_kfree *)ctx)->ptr);
    return 0;
}
