// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 68_deadlock.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* per-unit lock-order edge map for deadlock detection.
 * key = {lock_a, lock_b} (a was held when b was acquired). */
struct spnl_lock_edge {
    __u64 a;
    __u64 b;
};
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, struct spnl_lock_edge);
    __type(value, __u64);
    __uint(max_entries, 65536);
} bpf_lock_edges SEC(".maps");

static __noinline __s64 spnl_lock_edge(__s64 a, __s64 b)
{
    struct spnl_lock_edge k = {};
    k.a = (__u64)a;
    k.b = (__u64)b;
    __u64 *v = bpf_map_lookup_elem(&bpf_lock_edges, &k);
    if (v) {
        __sync_fetch_and_add(v, 1);
    } else {
        __u64 one = 1;
        bpf_map_update_elem(&bpf_lock_edges, &k, &one, BPF_NOEXIST);
    }
    return 0;
}

/* per-task local storage. task_store(v) / task_load() read+write
 * a value scoped to the current task_struct (no explicit key). */
struct {
    __uint(type, BPF_MAP_TYPE_TASK_STORAGE);
    __uint(map_flags, BPF_F_NO_PREALLOC);
    __type(key, int);
    __type(value, __s64);
} bpf_task_store SEC(".maps");

/* __always_inline: the PTR_TRUSTED task from bpf_get_current_task_btf()
 * must reach bpf_task_storage_get in the program's own context, not
 * across a __noinline sub-prog boundary (where it degrades and the
 * storage silently fails to persist). */
static __always_inline __s64 spnl_task_load(void)
{
    struct task_struct *t = bpf_get_current_task_btf();
    __s64 *v = bpf_task_storage_get(&bpf_task_store, t, 0, 0);
    return v ? *v : 0;
}

static __always_inline __s64 spnl_task_store(__s64 value)
{
    struct task_struct *t = bpf_get_current_task_btf();
    __s64 *v = bpf_task_storage_get(&bpf_task_store, t, 0, BPF_LOCAL_STORAGE_GET_F_CREATE);
    if (v) { *v = value; }
    return value;
}

static __always_inline __s64 spnl_task_incr(__s64 delta)
{
    struct task_struct *t = bpf_get_current_task_btf();
    __s64 *v = bpf_task_storage_get(&bpf_task_store, t, 0, BPF_LOCAL_STORAGE_GET_F_CREATE);
    if (!v) return 0;
    *v += delta;
    return *v;
}

/* single-get read-modify-write - store `value`, return the prior
 * value. One bpf_task_storage_get so it stays clear of the two-get
 * aliasing quirk. */
static __always_inline __s64 spnl_task_swap(__s64 value)
{
    struct task_struct *t = bpf_get_current_task_btf();
    __s64 *v = bpf_task_storage_get(&bpf_task_store, t, 0, BPF_LOCAL_STORAGE_GET_F_CREATE);
    if (!v) return 0;
    __s64 old = *v;
    *v = value;
    return old;
}

/* ctx for uprobe__pthread_mutex_lock — userspace fills before bpf_prog_test_run */
struct uprobe__pthread_mutex_lock_ctx {
    __s64 mutex;
};

/* ctx for uprobe__pthread_mutex_unlock — userspace fills before bpf_prog_test_run */
struct uprobe__pthread_mutex_unlock_ctx {
    __s64 mutex;
};

/* impl: uprobe__pthread_mutex_lock : int  params: mutex: int */
static __noinline __s64 uprobe__pthread_mutex_lock_inner(__s64 mutex)
{
    __s64 prev = 0;
    prev = spnl_task_swap(mutex);
    __s64 _if1 = 0;
    if (prev != 0) {
        spnl_lock_edge(prev, mutex);
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: uprobe__pthread_mutex_lock [uprobe -> uprobe] */
SEC("uprobe")
int uprobe__pthread_mutex_lock(struct pt_regs *ctx)
{
    (void)ctx;
    (void)uprobe__pthread_mutex_lock_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}

/* impl: uprobe__pthread_mutex_unlock : int  params: mutex: int */
static __noinline __s64 uprobe__pthread_mutex_unlock_inner(__s64 mutex)
{
    (void)(spnl_task_store(0));
    return 0;
}

/* entry wrapper: uprobe__pthread_mutex_unlock [uprobe -> uprobe] */
SEC("uprobe")
int uprobe__pthread_mutex_unlock(struct pt_regs *ctx)
{
    (void)ctx;
    (void)uprobe__pthread_mutex_unlock_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
