// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 69_execsnoop.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit ringbuf lost-sample counter ===
 * A bpf_ringbuf_reserve() that returns NULL (the ring filled faster than
 * userspace drained it) would otherwise drop the record silently -- invisible to
 * the drain-layer channel balance report, which can only count what came out.
 * Every emit else-branch bumps this; the runtime reads it at exit and prints the
 * 4th balance-report failure ("dropped by the kernel -- ring full").
 *
 * One PERCPU_ARRAY slot for the whole unit, not one per channel. Per-channel
 * attribution would need a codegen-assigned slot table shared with the glue
 * generator (two generators agreeing on indices) -- a unit-wide total answers the
 * question that matters (were records dropped by ring-full, and about how many)
 * with one map and no cross-generator contract. per-CPU so the bump needs no
 * atomic; the runtime sums the slots. Inspektor Gadget keeps a per-CPU lost
 * counter the same way. */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u64));
    __uint(max_entries, 1);
} u_69_execsnoop_lost SEC(".maps");

static __always_inline void spnl_lost_inc(void)
{
    __u32 _z = 0;
    __u64 *_l = bpf_map_lookup_elem(&u_69_execsnoop_lost, &_z);
    if (_l) *_l += 1;
}

/* === per-unit string-event channel === */
struct u_69_execsnoop_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_69_execsnoop_str_events SEC(".maps");

/* ctx for tracepoint__syscalls__sys_enter_execve — userspace fills before bpf_prog_test_run */
struct tracepoint__syscalls__sys_enter_execve_ctx {
    __s64 filename;
    __s64 argv;
};

/* impl: tracepoint__syscalls__sys_enter_execve : int  params: filename: int, argv: int */
static __noinline __s64 tracepoint__syscalls__sys_enter_execve_inner(__s64 filename, __s64 argv)
{
    {
        struct u_69_execsnoop_str_event *_se1 = bpf_ringbuf_reserve(&u_69_execsnoop_str_events, sizeof(*_se1), 0);
        if (_se1) {
            _se1->hdr.type = SPNL_EVT_USER_BASE;
            _se1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _se1->hdr.reserved = 0;
            _se1->hdr.timestamp = bpf_ktime_get_ns();
            bpf_probe_read_user_str(_se1->str, sizeof(_se1->str), (const void *)(filename));
            bpf_ringbuf_submit(_se1, 0);
        } else spnl_lost_inc();   /* ring full -> account the dropped record */
    }
    {
        #pragma unroll
        for (int _ai2 = 0; _ai2 < 20; _ai2++) {
            const char *_ap3 = 0;
            bpf_probe_read_user(&_ap3, sizeof(_ap3), &((const char *const *)(unsigned long)(argv))[_ai2]);
            if (!_ap3) break;
            struct u_69_execsnoop_str_event *_ae4 = bpf_ringbuf_reserve(&u_69_execsnoop_str_events, sizeof(*_ae4), 0);
            if (_ae4) {
                _ae4->hdr.type = SPNL_EVT_USER_BASE;
                _ae4->hdr.version = SPNL_EVENT_HDR_VERSION;
                _ae4->hdr.reserved = 0;
                _ae4->hdr.timestamp = bpf_ktime_get_ns();
                bpf_probe_read_user_str(_ae4->str, sizeof(_ae4->str), _ap3);
                bpf_ringbuf_submit(_ae4, 0);
            } else spnl_lost_inc();   /* ring full -> account the dropped record */
        }
    }
    return 0;
}

/* entry wrapper: tracepoint__syscalls__sys_enter_execve [tracepoint -> tracepoint/syscalls/sys_enter_execve] */
SEC("tracepoint/syscalls/sys_enter_execve")
int tracepoint__syscalls__sys_enter_execve(void *ctx)
{
    (void)ctx;
    (void)tracepoint__syscalls__sys_enter_execve_inner((__s64)((struct trace_event_raw_sys_enter *)ctx)->args[0], (__s64)((struct trace_event_raw_sys_enter *)ctx)->args[1]);
    return 0;
}
