// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 69_execsnoop.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit string-event channel === */
struct u_69_execsnoop_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_69_execsnoop_str_events SEC(".maps");

/* ctx for tracepoint__syscalls__sys_enter_execve — userspace fills before bpf_prog_test_run */
struct tracepoint__syscalls__sys_enter_execve_ctx {
    __s64 filename;
    __s64 argv;
};

/* impl: tracepoint__syscalls__sys_enter_execve : int  params: filename: int, argv: int */
static __noinline __s64 tracepoint__syscalls__sys_enter_execve_inner(__s64 filename, __s64 argv)
{
    {
        struct u_69_execsnoop_str_event *_se1 = bpf_ringbuf_reserve(&u_69_execsnoop_str_events, sizeof(*_se1), 0);
        if (_se1) {
            _se1->hdr.type = SPNL_EVT_USER_BASE;
            _se1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _se1->hdr.reserved = 0;
            _se1->hdr.timestamp = bpf_ktime_get_ns();
            bpf_probe_read_user_str(_se1->str, sizeof(_se1->str), (const void *)(filename));
            bpf_ringbuf_submit(_se1, 0);
        }
    }
    {
        #pragma unroll
        for (int _ai2 = 0; _ai2 < 20; _ai2++) {
            const char *_ap3 = 0;
            bpf_probe_read_user(&_ap3, sizeof(_ap3), &((const char *const *)(unsigned long)(argv))[_ai2]);
            if (!_ap3) break;
            struct u_69_execsnoop_str_event *_ae4 = bpf_ringbuf_reserve(&u_69_execsnoop_str_events, sizeof(*_ae4), 0);
            if (_ae4) {
                _ae4->hdr.type = SPNL_EVT_USER_BASE;
                _ae4->hdr.version = SPNL_EVENT_HDR_VERSION;
                _ae4->hdr.reserved = 0;
                _ae4->hdr.timestamp = bpf_ktime_get_ns();
                bpf_probe_read_user_str(_ae4->str, sizeof(_ae4->str), _ap3);
                bpf_ringbuf_submit(_ae4, 0);
            }
        }
    }
    return 0;
}

/* entry wrapper: tracepoint__syscalls__sys_enter_execve [tracepoint -> tracepoint/syscalls/sys_enter_execve] */
SEC("tracepoint/syscalls/sys_enter_execve")
int tracepoint__syscalls__sys_enter_execve(void *ctx)
{
    (void)ctx;
    (void)tracepoint__syscalls__sys_enter_execve_inner((__s64)((struct trace_event_raw_sys_enter *)ctx)->args[0], (__s64)((struct trace_event_raw_sys_enter *)ctx)->args[1]);
    return 0;
}
