// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 70_runqlat.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* per-unit arbitrary-key latency map (bcc biolatency / runqlat).
 * key = any u64 id; value = entry ktime. */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);
    __type(value, __u64);
    __uint(max_entries, 65536);
} bpf_keyed_lat SEC(".maps");

static __noinline __s64 spnl_lat_start_key(__s64 key)
{
    __u64 k = (__u64)key;
    __u64 now = bpf_ktime_get_ns();
    bpf_map_update_elem(&bpf_keyed_lat, &k, &now, BPF_ANY);
    return 0;
}

static __noinline __s64 spnl_lat_end_key(__s64 key)
{
    __u64 k = (__u64)key;
    __u64 *t = bpf_map_lookup_elem(&bpf_keyed_lat, &k);
    if (!t) return 0;
    __u64 d = bpf_ktime_get_ns() - *t;
    bpf_map_delete_elem(&bpf_keyed_lat, &k);
    return (__s64)d;
}

/* per-unit log2 histogram (64 buckets). */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(key, __u32);
    __type(value, __u64);
    __uint(max_entries, 64);
} bpf_hist SEC(".maps");

/* Verifier-safe integer log2: returns floor(log2(v)) clamped to
 * [0, HISTOGRAM_SLOTS-1]. v<=0 maps to slot 0 so callers don't have
 * to guard against zero observations (it just over-reports the
 * smallest bucket). All comparisons are against compile-time
 * constants so the verifier sees a bounded computation. */
static __noinline __s64 spnl_hist_log2(__s64 v)
{
    __s64 r = 0;
    if (v <= 1) return 0;
    if (v >= (1LL << 32)) { v >>= 32; r += 32; }
    if (v >= (1   << 16)) { v >>= 16; r += 16; }
    if (v >= (1   << 8))  { v >>= 8;  r += 8;  }
    if (v >= (1   << 4))  { v >>= 4;  r += 4;  }
    if (v >= (1   << 2))  { v >>= 2;  r += 2;  }
    if (v >= (1   << 1))  { v >>= 1;  r += 1;  }
    if (r > 63) r = 63;
    return r;
}

static __noinline __s64 spnl_hist_observe(__s64 v)
{
    __u32 slot = (__u32)spnl_hist_log2(v);
    if (slot >= 64) return 0;  /* verifier hand-holding */
    __u64 *cur = bpf_map_lookup_elem(&bpf_hist, &slot);
    if (cur) __sync_fetch_and_add(cur, 1);
    return 0;
}

/* ctx for tracepoint__sched__sched_wakeup — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_wakeup_ctx {
    __s64 pid;
};

/* ctx for tracepoint__sched__sched_switch — userspace fills before bpf_prog_test_run */
struct tracepoint__sched__sched_switch_ctx {
    __s64 prev_pid;
    __s64 next_pid;
};

/* impl: tracepoint__sched__sched_wakeup : int  params: pid: int */
static __noinline __s64 tracepoint__sched__sched_wakeup_inner(__s64 pid)
{
    (void)(spnl_lat_start_key(pid));
    return 0;
}

/* entry wrapper: tracepoint__sched__sched_wakeup [tracepoint -> tracepoint/sched/sched_wakeup] */
SEC("tracepoint/sched/sched_wakeup")
int tracepoint__sched__sched_wakeup(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_wakeup_inner((__s64)((struct trace_event_raw_sched_wakeup_template *)ctx)->pid);
    return 0;
}

/* impl: tracepoint__sched__sched_switch : int  params: prev_pid: int, next_pid: int */
static __noinline __s64 tracepoint__sched__sched_switch_inner(__s64 prev_pid, __s64 next_pid)
{
    __s64 d = 0;
    d = spnl_lat_end_key(next_pid);
    __s64 _if1 = 0;
    if (d > 0) {
        spnl_hist_observe(d);
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: tracepoint__sched__sched_switch [tracepoint -> tracepoint/sched/sched_switch] */
SEC("tracepoint/sched/sched_switch")
int tracepoint__sched__sched_switch(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sched__sched_switch_inner((__s64)((struct trace_event_raw_sched_switch *)ctx)->prev_pid, (__s64)((struct trace_event_raw_sched_switch *)ctx)->next_pid);
    return 0;
}
