// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 72_tcpconnect.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit pair-event channel === */
struct u_72_tcpconnect_pair_event {
    struct spnl_event_hdr hdr;
    __s64 a;
    __s64 b;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_72_tcpconnect_pair_events SEC(".maps");

/* ctx for tracepoint__sock__inet_sock_set_state — userspace fills before bpf_prog_test_run */
struct tracepoint__sock__inet_sock_set_state_ctx {
    __s64 daddr;
    __s64 dport;
    __s64 oldstate;
    __s64 newstate;
};

/* impl: tracepoint__sock__inet_sock_set_state : int  params: daddr: int, dport: int, oldstate: int, newstate: int */
static __noinline __s64 tracepoint__sock__inet_sock_set_state_inner(__s64 daddr, __s64 dport, __s64 oldstate, __s64 newstate)
{
    __s64 _if1 = 0;
    if ((oldstate == 7) && (newstate == 2)) {
        {
            struct u_72_tcpconnect_pair_event *_pe2 = bpf_ringbuf_reserve(&u_72_tcpconnect_pair_events, sizeof(*_pe2), 0);
            if (_pe2) {
                _pe2->hdr.type = SPNL_EVT_USER_BASE;
                _pe2->hdr.version = SPNL_EVENT_HDR_VERSION;
                _pe2->hdr.reserved = 0;
                _pe2->hdr.timestamp = bpf_ktime_get_ns();
                _pe2->a = daddr;
                _pe2->b = dport;
                bpf_ringbuf_submit(_pe2, 0);
            }
        }
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: tracepoint__sock__inet_sock_set_state [tracepoint -> tracepoint/sock/inet_sock_set_state] */
SEC("tracepoint/sock/inet_sock_set_state")
int tracepoint__sock__inet_sock_set_state(void *ctx)
{
    (void)ctx;
    (void)tracepoint__sock__inet_sock_set_state_inner((__s64)(*(__u32 *)(((struct trace_event_raw_inet_sock_set_state *)ctx)->daddr)), (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->dport, (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->oldstate, (__s64)((struct trace_event_raw_inet_sock_set_state *)ctx)->newstate);
    return 0;
}
