// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 73_irq.rb
// ebpf-eligible methods: 4, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* per-unit arbitrary-key latency map (bcc biolatency / runqlat).
 * key = any u64 id; value = entry ktime. */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);
    __type(value, __u64);
    __uint(max_entries, 65536);
} bpf_keyed_lat SEC(".maps");

static __noinline __s64 spnl_lat_start_key(__s64 key)
{
    __u64 k = (__u64)key;
    __u64 now = bpf_ktime_get_ns();
    bpf_map_update_elem(&bpf_keyed_lat, &k, &now, BPF_ANY);
    return 0;
}

static __noinline __s64 spnl_lat_end_key(__s64 key)
{
    __u64 k = (__u64)key;
    __u64 *t = bpf_map_lookup_elem(&bpf_keyed_lat, &k);
    if (!t) return 0;
    __u64 d = bpf_ktime_get_ns() - *t;
    bpf_map_delete_elem(&bpf_keyed_lat, &k);
    return (__s64)d;
}

/* per-unit log2 histogram (64 buckets). */
struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __type(key, __u32);
    __type(value, __u64);
    __uint(max_entries, 64);
} bpf_hist SEC(".maps");

/* Verifier-safe integer log2: returns floor(log2(v)) clamped to
 * [0, HISTOGRAM_SLOTS-1]. v<=0 maps to slot 0 so callers don't have
 * to guard against zero observations (it just over-reports the
 * smallest bucket). All comparisons are against compile-time
 * constants so the verifier sees a bounded computation. */
static __noinline __s64 spnl_hist_log2(__s64 v)
{
    __s64 r = 0;
    if (v <= 1) return 0;
    if (v >= (1LL << 32)) { v >>= 32; r += 32; }
    if (v >= (1   << 16)) { v >>= 16; r += 16; }
    if (v >= (1   << 8))  { v >>= 8;  r += 8;  }
    if (v >= (1   << 4))  { v >>= 4;  r += 4;  }
    if (v >= (1   << 2))  { v >>= 2;  r += 2;  }
    if (v >= (1   << 1))  { v >>= 1;  r += 1;  }
    if (r > 63) r = 63;
    return r;
}

static __noinline __s64 spnl_hist_observe(__s64 v)
{
    __u32 slot = (__u32)spnl_hist_log2(v);
    if (slot >= 64) return 0;  /* verifier hand-holding */
    __u64 *cur = bpf_map_lookup_elem(&bpf_hist, &slot);
    if (cur) __sync_fetch_and_add(cur, 1);
    return 0;
}

/* ctx for tracepoint__irq__irq_handler_entry — userspace fills before bpf_prog_test_run */
struct tracepoint__irq__irq_handler_entry_ctx {
    __s64 irq;
};

/* ctx for tracepoint__irq__irq_handler_exit — userspace fills before bpf_prog_test_run */
struct tracepoint__irq__irq_handler_exit_ctx {
    __s64 irq;
    __s64 ret;
};

/* ctx for tracepoint__irq__softirq_entry — userspace fills before bpf_prog_test_run */
struct tracepoint__irq__softirq_entry_ctx {
    __s64 vec;
};

/* ctx for tracepoint__irq__softirq_exit — userspace fills before bpf_prog_test_run */
struct tracepoint__irq__softirq_exit_ctx {
    __s64 vec;
};

/* impl: tracepoint__irq__irq_handler_entry : int  params: irq: int */
static __noinline __s64 tracepoint__irq__irq_handler_entry_inner(__s64 irq)
{
    (void)(spnl_lat_start_key(((__s64)bpf_get_smp_processor_id()) + irq));
    return 0;
}

/* entry wrapper: tracepoint__irq__irq_handler_entry [tracepoint -> tracepoint/irq/irq_handler_entry] */
SEC("tracepoint/irq/irq_handler_entry")
int tracepoint__irq__irq_handler_entry(void *ctx)
{
    (void)ctx;
    (void)tracepoint__irq__irq_handler_entry_inner((__s64)((struct trace_event_raw_irq_handler_entry *)ctx)->irq);
    return 0;
}

/* impl: tracepoint__irq__irq_handler_exit : int  params: irq: int, ret: int */
static __noinline __s64 tracepoint__irq__irq_handler_exit_inner(__s64 irq, __s64 ret)
{
    __s64 d = 0;
    d = spnl_lat_end_key(((__s64)bpf_get_smp_processor_id()) + irq);
    __s64 _if1 = 0;
    if (d > 0) {
        spnl_hist_observe(d);
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: tracepoint__irq__irq_handler_exit [tracepoint -> tracepoint/irq/irq_handler_exit] */
SEC("tracepoint/irq/irq_handler_exit")
int tracepoint__irq__irq_handler_exit(void *ctx)
{
    (void)ctx;
    (void)tracepoint__irq__irq_handler_exit_inner((__s64)((struct trace_event_raw_irq_handler_exit *)ctx)->irq, (__s64)((struct trace_event_raw_irq_handler_exit *)ctx)->ret);
    return 0;
}

/* impl: tracepoint__irq__softirq_entry : int  params: vec: int */
static __noinline __s64 tracepoint__irq__softirq_entry_inner(__s64 vec)
{
    (void)(spnl_lat_start_key(((__s64)bpf_get_smp_processor_id()) + vec));
    return 0;
}

/* entry wrapper: tracepoint__irq__softirq_entry [tracepoint -> tracepoint/irq/softirq_entry] */
SEC("tracepoint/irq/softirq_entry")
int tracepoint__irq__softirq_entry(void *ctx)
{
    (void)ctx;
    (void)tracepoint__irq__softirq_entry_inner((__s64)((struct trace_event_raw_softirq *)ctx)->vec);
    return 0;
}

/* impl: tracepoint__irq__softirq_exit : int  params: vec: int */
static __noinline __s64 tracepoint__irq__softirq_exit_inner(__s64 vec)
{
    __s64 d = 0;
    d = spnl_lat_end_key(((__s64)bpf_get_smp_processor_id()) + vec);
    __s64 _if1 = 0;
    if (d > 0) {
        spnl_hist_observe(d);
        _if1 = 0;
    }
    return 0;
}

/* entry wrapper: tracepoint__irq__softirq_exit [tracepoint -> tracepoint/irq/softirq_exit] */
SEC("tracepoint/irq/softirq_exit")
int tracepoint__irq__softirq_exit(void *ctx)
{
    (void)ctx;
    (void)tracepoint__irq__softirq_exit_inner((__s64)((struct trace_event_raw_softirq *)ctx)->vec);
    return 0;
}
