// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 78_fib_lookup_kprobe.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @x : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_78_fib_lookup_kprobe_top_x SEC(".maps");

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
};

/* impl: kprobe__tcp_sendmsg : int  params: sk: int */
static __noinline __s64 kprobe__tcp_sendmsg_inner(__s64 sk)
{
    __u32 _k2 = 0;
    __s64 _v3 = ({
        struct bpf_fib_lookup _spnl_fib_1 = {};
        _spnl_fib_1.family = 2; /* AF_INET */
        _spnl_fib_1.ipv4_dst = bpf_htonl((__u32)(sk));
        __s64 _spnl_fibret_1 = bpf_fib_lookup(ctx, &_spnl_fib_1, sizeof(_spnl_fib_1), 0);
        (__s64)(_spnl_fibret_1 == 0 ? _spnl_fib_1.ifindex : (__s64)-1);
    });
    bpf_map_update_elem(&u_78_fib_lookup_kprobe_top_x, &_k2, &_v3, BPF_ANY);
    return _v3;
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    (void)kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx));
    return 0;
}
