// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 79_skb_rewrite.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @n : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_79_skb_rewrite_top_n SEC(".maps");

/* impl: tc__egress__ttl : int */
static __noinline __s64 tc__egress__ttl_inner(struct __sk_buff *ctx)
{
    __s64 ttl = 0;
    __s64 nt = 0;
    ttl = ({ __u8 _spnl_lb_1 = 0; __s64 _r1 = bpf_skb_load_bytes(ctx, (22), &_spnl_lb_1, 1); (__s64)(_r1 < 0 ? (__s64)-1 : (__s64)_spnl_lb_1); });
    __s64 _if2 = 0;
    if (ttl > 1) {
        nt = ttl - 1;
        (void)((__s64)bpf_l3_csum_replace(ctx, (24), bpf_htons((__u16)(ttl << 8)), bpf_htons((__u16)(nt << 8)), 2));
        (void)(({ __u8 _spnl_sb_3 = (__u8)(nt); (__s64)bpf_skb_store_bytes(ctx, (22), &_spnl_sb_3, 1, 0); }));
        __u32 _k4 = 0;
        __s64 *_p5 = bpf_map_lookup_elem(&u_79_skb_rewrite_top_n, &_k4);
        __u32 _k6 = 0;
        __s64 _v7 = (_p5 ? *_p5 : 0) + 1;
        bpf_map_update_elem(&u_79_skb_rewrite_top_n, &_k6, &_v7, BPF_ANY);
        _if2 = _v7;
    }
    return 0;
}

/* entry wrapper: tc__egress__ttl [tc_egress -> tcx/egress] */
SEC("tcx/egress")
int tc__egress__ttl(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__egress__ttl_inner(ctx);
}
