// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 80_skb_rewrite_xdp.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @x : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_80_skb_rewrite_xdp_top_x SEC(".maps");

/* impl: xdp__main : int */
static __noinline __s64 xdp__main_inner(struct xdp_md *ctx)
{
    __u32 _k2 = 0;
    __s64 _v3 = ({ __u8 _spnl_sb_1 = (__u8)(5); (__s64)bpf_skb_store_bytes(ctx, (22), &_spnl_sb_1, 1, 0); });
    bpf_map_update_elem(&u_80_skb_rewrite_xdp_top_x, &_k2, &_v3, BPF_ANY);
    return 2;
}

/* entry wrapper: xdp__main [xdp -> xdp] */
SEC("xdp")
int xdp__main(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__main_inner(ctx);
}
