// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 81_nat_rewrite.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @n : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_81_nat_rewrite_top_n SEC(".maps");

/* impl: tc__ingress__dnat : int */
static __noinline __s64 tc__ingress__dnat_inner(struct __sk_buff *ctx)
{
    __s64 dst = 0;
    __s64 new = 0;
    dst = ({ __u32 _spnl_l4r_1 = 0; __s64 _r1 = bpf_skb_load_bytes(ctx, (30), &_spnl_l4r_1, 4); (__s64)(_r1 < 0 ? (__s64)-1 : (__s64)(__u32)bpf_ntohl(_spnl_l4r_1)); });
    __s64 _if2 = 0;
    if (dst == 167772162) {
        new = 167772259;
        (void)((__s64)bpf_l3_csum_replace(ctx, (24), bpf_htonl((__u32)(dst)), bpf_htonl((__u32)(new)), 4));
        (void)((__s64)bpf_l4_csum_replace(ctx, (50), bpf_htonl((__u32)(dst)), bpf_htonl((__u32)(new)), ((1 << 4) | 4)));
        (void)(({ __u32 _spnl_su_3 = bpf_htonl((__u32)(new)); (__s64)bpf_skb_store_bytes(ctx, (30), &_spnl_su_3, 4, 0); }));
        __u32 _k4 = 0;
        __s64 *_p5 = bpf_map_lookup_elem(&u_81_nat_rewrite_top_n, &_k4);
        __u32 _k6 = 0;
        __s64 _v7 = (_p5 ? *_p5 : 0) + 1;
        bpf_map_update_elem(&u_81_nat_rewrite_top_n, &_k6, &_v7, BPF_ANY);
        _if2 = _v7;
    }
    return 0;
}

/* entry wrapper: tc__ingress__dnat [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__dnat(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__dnat_inner(ctx);
}
