// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 82_nat_xdp.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @x : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_82_nat_xdp_top_x SEC(".maps");

/* impl: xdp__main : int */
static __noinline __s64 xdp__main_inner(struct xdp_md *ctx)
{
    __u32 _k2 = 0;
    __s64 _v3 = ({ __u32 _spnl_l4r_1 = 0; __s64 _r1 = bpf_skb_load_bytes(ctx, (30), &_spnl_l4r_1, 4); (__s64)(_r1 < 0 ? (__s64)-1 : (__s64)(__u32)bpf_ntohl(_spnl_l4r_1)); });
    bpf_map_update_elem(&u_82_nat_xdp_top_x, &_k2, &_v3, BPF_ANY);
    return 2;
}

/* entry wrapper: xdp__main [xdp -> xdp] */
SEC("xdp")
int xdp__main(struct xdp_md *ctx)
{
    (void)ctx;
    return (int)xdp__main_inner(ctx);
}
