// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 84_arena.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @slot0 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_84_arena_top_slot0 SEC(".maps");

/* top-level ivar @slot1 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_84_arena_top_slot1 SEC(".maps");

/* bpf_arena - sparse, mmap-able shared memory backing arena_set/get. */
#ifndef __arena
#define __arena __attribute__((address_space(1)))
#endif

struct {
    __uint(type, BPF_MAP_TYPE_ARENA);
    __uint(map_flags, BPF_F_MMAPABLE);
    __uint(max_entries, 1); /* pages; 1 page = 512 u64 slots */
#if defined(__TARGET_ARCH_arm64)
    __ulong(map_extra, (1ull << 32)); /* user mmap base (arm64) */
#else
    __ulong(map_extra, (1ull << 44)); /* user mmap base (x86-64) */
#endif
} u_84_arena_arena SEC(".maps");

/* Lives in the arena (placed at load time); index masked to stay in-page. */
__u64 __arena u_84_arena_arena_data[512];

/* impl: tc__ingress__arena_demo : int */
static __noinline __s64 tc__ingress__arena_demo_inner(struct __sk_buff *ctx)
{
    (void)(({ u_84_arena_arena_data[(__u64)(0) & 511] = (__u64)(305419896); (__s64)0; }));
    (void)(({ u_84_arena_arena_data[(__u64)(1) & 511] = (__u64)(((__s64)u_84_arena_arena_data[(__u64)(0) & 511]) + 1); (__s64)0; }));
    __u32 _k1 = 0;
    __s64 _v2 = ((__s64)u_84_arena_arena_data[(__u64)(0) & 511]);
    bpf_map_update_elem(&u_84_arena_top_slot0, &_k1, &_v2, BPF_ANY);
    __u32 _k3 = 0;
    __s64 _v4 = ((__s64)u_84_arena_arena_data[(__u64)(1) & 511]);
    bpf_map_update_elem(&u_84_arena_top_slot1, &_k3, &_v4, BPF_ANY);
    return 0;
}

/* entry wrapper: tc__ingress__arena_demo [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__arena_demo(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__arena_demo_inner(ctx);
}
