// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 85_l4_lb.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @new_flows : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_85_l4_lb_top_new_flows SEC(".maps");

/* Roadmap #2: per-flow state map :conn (4-tuple key, u64 fields). */
struct spnl_flow_u_85_l4_lb_conn_k {
    __be32 saddr;
    __be32 daddr;
    __be16 sport;
    __be16 dport;
};
struct spnl_flow_u_85_l4_lb_conn_v {
    __u64 backend_ip;
};
struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __type(key, struct spnl_flow_u_85_l4_lb_conn_k);
    __type(value, struct spnl_flow_u_85_l4_lb_conn_v);
    __uint(max_entries, 65536);
} spnl_flow_u_85_l4_lb_conn SEC(".maps");

/* Fill :conn flow key (saddr,daddr,sport,dport) from the packet. */
static __noinline int spnl_flow_u_85_l4_lb_conn_key_tc(struct __sk_buff *ctx, struct spnl_flow_u_85_l4_lb_conn_k *k)
{
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return -1;
    if (eth->h_proto != bpf_htons(0x0800)) return -1;
    struct iphdr *iph = (void *)(eth + 1);
    if ((void *)(iph + 1) > data_end) return -1;
    if (iph->protocol != 6) return -1;  /* IPPROTO_TCP */
    __u32 ihl = iph->ihl * 4;
    if (ihl < sizeof(*iph)) return -1;
    struct tcphdr *tcp = (struct tcphdr *)((char *)iph + ihl);
    if ((void *)(tcp + 1) > data_end) return -1;
    k->saddr = iph->saddr;
    k->daddr = iph->daddr;
    k->sport = tcp->source;
    k->dport = tcp->dest;
    return 0;
}

/* impl: tc__ingress__lb : int */
static __noinline __s64 tc__ingress__lb_inner(struct __sk_buff *ctx)
{
    __s64 bip = 0;
    __s64 idx = 0;
    __s64 old = 0;
    struct spnl_flow_u_85_l4_lb_conn_k _fk1 = {};
    struct spnl_flow_u_85_l4_lb_conn_v *_fp2 = (spnl_flow_u_85_l4_lb_conn_key_tc(ctx, &_fk1) == 0) ? bpf_map_lookup_elem(&spnl_flow_u_85_l4_lb_conn, &_fk1) : NULL;
    bip = (_fp2 ? (__s64)_fp2->backend_ip : 0);
    __s64 _if3 = 0;
    if (bip == 0) {
        idx = ({ __u16 _spnl_l2r_4 = 0; __s64 _r4 = bpf_skb_load_bytes(ctx, (34), &_spnl_l2r_4, 2); (__s64)(_r4 < 0 ? (__s64)-1 : (__s64)(__u16)bpf_ntohs(_spnl_l2r_4)); }) & 3;
        __s64 _if5 = 0;
        if (idx == 0) {
            bip = 167772261;
            _if5 = bip;
        } else {
            __s64 _if6 = 0;
            if (idx == 1) {
                bip = 167772262;
                _if6 = bip;
            } else {
                __s64 _if7 = 0;
                if (idx == 2) {
                    bip = 167772263;
                    _if7 = bip;
                } else {
                    bip = 167772264;
                    _if7 = bip;
                }
                _if6 = _if7;
            }
            _if5 = _if6;
        }
        struct spnl_flow_u_85_l4_lb_conn_k _fk8 = {};
        struct spnl_flow_u_85_l4_lb_conn_v _fz9 = {};
        int _fok10 = spnl_flow_u_85_l4_lb_conn_key_tc(ctx, &_fk8);
        struct spnl_flow_u_85_l4_lb_conn_v *_fp11 = _fok10 == 0 ? bpf_map_lookup_elem(&spnl_flow_u_85_l4_lb_conn, &_fk8) : NULL;
        if (_fok10 == 0 && !_fp11) bpf_map_update_elem(&spnl_flow_u_85_l4_lb_conn, &_fk8, &_fz9, BPF_ANY);
        if (_fok10 == 0 && !_fp11) _fp11 = bpf_map_lookup_elem(&spnl_flow_u_85_l4_lb_conn, &_fk8);
        if (_fp11) _fp11->backend_ip = (__u64)(bip);
        __u32 _k12 = 0;
        __s64 *_p13 = bpf_map_lookup_elem(&u_85_l4_lb_top_new_flows, &_k12);
        __u32 _k14 = 0;
        __s64 _v15 = (_p13 ? *_p13 : 0) + 1;
        bpf_map_update_elem(&u_85_l4_lb_top_new_flows, &_k14, &_v15, BPF_ANY);
        _if3 = _v15;
    }
    old = ({ __u32 _spnl_l4r_16 = 0; __s64 _r16 = bpf_skb_load_bytes(ctx, (30), &_spnl_l4r_16, 4); (__s64)(_r16 < 0 ? (__s64)-1 : (__s64)(__u32)bpf_ntohl(_spnl_l4r_16)); });
    (void)((__s64)bpf_l3_csum_replace(ctx, (24), bpf_htonl((__u32)(old)), bpf_htonl((__u32)(bip)), 4));
    (void)((__s64)bpf_l4_csum_replace(ctx, (50), bpf_htonl((__u32)(old)), bpf_htonl((__u32)(bip)), ((1 << 4) | 4)));
    (void)(({ __u32 _spnl_su_17 = bpf_htonl((__u32)(bip)); (__s64)bpf_skb_store_bytes(ctx, (30), &_spnl_su_17, 4, 0); }));
    return 0;
}

/* entry wrapper: tc__ingress__lb [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__lb(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__lb_inner(ctx);
}
