// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 86_arena_hash.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @v1 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_86_arena_hash_top_v1 SEC(".maps");

/* top-level ivar @v2 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_86_arena_hash_top_v2 SEC(".maps");

/* top-level ivar @v3 : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_86_arena_hash_top_v3 SEC(".maps");

/* bpf_arena - sparse, mmap-able shared memory backing arena_set/get. */
#ifndef __arena
#define __arena __attribute__((address_space(1)))
#endif

struct {
    __uint(type, BPF_MAP_TYPE_ARENA);
    __uint(map_flags, BPF_F_MMAPABLE);
    __uint(max_entries, 1); /* pages; 1 page = 512 u64 slots */
#if defined(__TARGET_ARCH_arm64)
    __ulong(map_extra, (1ull << 32)); /* user mmap base (arm64) */
#else
    __ulong(map_extra, (1ull << 44)); /* user mmap base (x86-64) */
#endif
} u_86_arena_hash_arena SEC(".maps");

/* Lives in the arena (placed at load time); index masked to stay in-page. */
__u64 __arena u_86_arena_hash_arena_data[512];

/* impl: tc__ingress__hashdemo : int */
static __noinline __s64 tc__ingress__hashdemo_inner(struct __sk_buff *ctx)
{
    (void)(({
        __u64 _hk1 = (__u64)(1001); __u64 _hv1 = (__u64)(42); __s64 _hok1 = 0;
        __u32 _hh1 = ((__u32)_hk1 * 2654435761U) & 255U;
        #pragma unroll
        for (int _hi1 = 0; _hi1 < 8; _hi1++) {
            __u32 _hs1 = (_hh1 + (__u32)_hi1) & 255U;
            __u64 _hek1 = u_86_arena_hash_arena_data[2U * _hs1];
            if (!_hok1 && (_hek1 == 0 || _hek1 == _hk1)) {
                u_86_arena_hash_arena_data[2U * _hs1] = _hk1; u_86_arena_hash_arena_data[2U * _hs1 + 1] = _hv1; _hok1 = 1;
            }
        }
        _hok1;
    }));
    (void)(({
        __u64 _hk2 = (__u64)(2002); __u64 _hv2 = (__u64)(99); __s64 _hok2 = 0;
        __u32 _hh2 = ((__u32)_hk2 * 2654435761U) & 255U;
        #pragma unroll
        for (int _hi2 = 0; _hi2 < 8; _hi2++) {
            __u32 _hs2 = (_hh2 + (__u32)_hi2) & 255U;
            __u64 _hek2 = u_86_arena_hash_arena_data[2U * _hs2];
            if (!_hok2 && (_hek2 == 0 || _hek2 == _hk2)) {
                u_86_arena_hash_arena_data[2U * _hs2] = _hk2; u_86_arena_hash_arena_data[2U * _hs2 + 1] = _hv2; _hok2 = 1;
            }
        }
        _hok2;
    }));
    (void)(({
        __u64 _hk3 = (__u64)(1001); __u64 _hv3 = (__u64)(50); __s64 _hok3 = 0;
        __u32 _hh3 = ((__u32)_hk3 * 2654435761U) & 255U;
        #pragma unroll
        for (int _hi3 = 0; _hi3 < 8; _hi3++) {
            __u32 _hs3 = (_hh3 + (__u32)_hi3) & 255U;
            __u64 _hek3 = u_86_arena_hash_arena_data[2U * _hs3];
            if (!_hok3 && (_hek3 == 0 || _hek3 == _hk3)) {
                u_86_arena_hash_arena_data[2U * _hs3] = _hk3; u_86_arena_hash_arena_data[2U * _hs3 + 1] = _hv3; _hok3 = 1;
            }
        }
        _hok3;
    }));
    __u32 _k5 = 0;
    __s64 _v6 = ({
        __u64 _hk4 = (__u64)(1001); __s64 _hr4 = 0; __s64 _hf4 = 0;
        __u32 _hh4 = ((__u32)_hk4 * 2654435761U) & 255U;
        #pragma unroll
        for (int _hi4 = 0; _hi4 < 8; _hi4++) {
            __u32 _hs4 = (_hh4 + (__u32)_hi4) & 255U;
            __u64 _hek4 = u_86_arena_hash_arena_data[2U * _hs4];
            if (!_hf4 && _hek4 == _hk4) { _hr4 = (__s64)u_86_arena_hash_arena_data[2U * _hs4 + 1]; _hf4 = 1; }
        }
        _hr4;
    });
    bpf_map_update_elem(&u_86_arena_hash_top_v1, &_k5, &_v6, BPF_ANY);
    __u32 _k8 = 0;
    __s64 _v9 = ({
        __u64 _hk7 = (__u64)(2002); __s64 _hr7 = 0; __s64 _hf7 = 0;
        __u32 _hh7 = ((__u32)_hk7 * 2654435761U) & 255U;
        #pragma unroll
        for (int _hi7 = 0; _hi7 < 8; _hi7++) {
            __u32 _hs7 = (_hh7 + (__u32)_hi7) & 255U;
            __u64 _hek7 = u_86_arena_hash_arena_data[2U * _hs7];
            if (!_hf7 && _hek7 == _hk7) { _hr7 = (__s64)u_86_arena_hash_arena_data[2U * _hs7 + 1]; _hf7 = 1; }
        }
        _hr7;
    });
    bpf_map_update_elem(&u_86_arena_hash_top_v2, &_k8, &_v9, BPF_ANY);
    __u32 _k11 = 0;
    __s64 _v12 = ({
        __u64 _hk10 = (__u64)(7777); __s64 _hr10 = 0; __s64 _hf10 = 0;
        __u32 _hh10 = ((__u32)_hk10 * 2654435761U) & 255U;
        #pragma unroll
        for (int _hi10 = 0; _hi10 < 8; _hi10++) {
            __u32 _hs10 = (_hh10 + (__u32)_hi10) & 255U;
            __u64 _hek10 = u_86_arena_hash_arena_data[2U * _hs10];
            if (!_hf10 && _hek10 == _hk10) { _hr10 = (__s64)u_86_arena_hash_arena_data[2U * _hs10 + 1]; _hf10 = 1; }
        }
        _hr10;
    });
    bpf_map_update_elem(&u_86_arena_hash_top_v3, &_k11, &_v12, BPF_ANY);
    return 0;
}

/* entry wrapper: tc__ingress__hashdemo [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__hashdemo(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__hashdemo_inner(ctx);
}
