// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 89_arena_list.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @sum : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_89_arena_list_top_sum SEC(".maps");

/* bpf_arena - sparse, mmap-able shared memory backing arena_set/get. */
#ifndef __arena
#define __arena __attribute__((address_space(1)))
#endif

struct {
    __uint(type, BPF_MAP_TYPE_ARENA);
    __uint(map_flags, BPF_F_MMAPABLE);
    __uint(max_entries, 1); /* pages; 1 page = 512 u64 slots */
#if defined(__TARGET_ARCH_arm64)
    __ulong(map_extra, (1ull << 32)); /* user mmap base (arm64) */
#else
    __ulong(map_extra, (1ull << 44)); /* user mmap base (x86-64) */
#endif
} u_89_arena_list_arena SEC(".maps");

/* Lives in the arena (placed at load time); index masked to stay in-page. */
__u64 __arena u_89_arena_list_arena_data[512];

/* impl: tc__ingress__listdemo : int */
static __noinline __s64 tc__ingress__listdemo_inner(struct __sk_buff *ctx)
{
    (void)(({
        __u64 _lv1 = (__u64)(10);
        __u64 _li1 = u_89_arena_list_arena_data[1];          /* bump pointer */
        if (_li1 == 0) _li1 = 1;       /* node indices start at 1 */
        __s64 _lok1 = 0;
        if (_li1 < 256) {
            u_89_arena_list_arena_data[(2U * _li1) & 511] = _lv1;
            u_89_arena_list_arena_data[(2U * _li1 + 1) & 511] = u_89_arena_list_arena_data[0]; /* next = head */
            u_89_arena_list_arena_data[0] = _li1;            /* head = new node */
            u_89_arena_list_arena_data[1] = _li1 + 1;        /* bump++ */
            _lok1 = 1;
        }
        _lok1;
    }));
    (void)(({
        __u64 _lv2 = (__u64)(20);
        __u64 _li2 = u_89_arena_list_arena_data[1];          /* bump pointer */
        if (_li2 == 0) _li2 = 1;       /* node indices start at 1 */
        __s64 _lok2 = 0;
        if (_li2 < 256) {
            u_89_arena_list_arena_data[(2U * _li2) & 511] = _lv2;
            u_89_arena_list_arena_data[(2U * _li2 + 1) & 511] = u_89_arena_list_arena_data[0]; /* next = head */
            u_89_arena_list_arena_data[0] = _li2;            /* head = new node */
            u_89_arena_list_arena_data[1] = _li2 + 1;        /* bump++ */
            _lok2 = 1;
        }
        _lok2;
    }));
    (void)(({
        __u64 _lv3 = (__u64)(30);
        __u64 _li3 = u_89_arena_list_arena_data[1];          /* bump pointer */
        if (_li3 == 0) _li3 = 1;       /* node indices start at 1 */
        __s64 _lok3 = 0;
        if (_li3 < 256) {
            u_89_arena_list_arena_data[(2U * _li3) & 511] = _lv3;
            u_89_arena_list_arena_data[(2U * _li3 + 1) & 511] = u_89_arena_list_arena_data[0]; /* next = head */
            u_89_arena_list_arena_data[0] = _li3;            /* head = new node */
            u_89_arena_list_arena_data[1] = _li3 + 1;        /* bump++ */
            _lok3 = 1;
        }
        _lok3;
    }));
    __u32 _k5 = 0;
    __s64 _v6 = ({
        __u64 _ls4 = 0, _lc4 = u_89_arena_list_arena_data[0];   /* head */
        #pragma unroll
        for (int _lj4 = 0; _lj4 < 16; _lj4++) {
            if (_lc4 != 0 && _lc4 < 256) {
                _ls4 += u_89_arena_list_arena_data[(2U * _lc4) & 511];
                _lc4 = u_89_arena_list_arena_data[(2U * _lc4 + 1) & 511];
            }
        }
        (__s64)_ls4;
    });
    bpf_map_update_elem(&u_89_arena_list_top_sum, &_k5, &_v6, BPF_ANY);
    return 0;
}

/* entry wrapper: tc__ingress__listdemo [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__listdemo(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__listdemo_inner(ctx);
}
