// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 95_sk_assign.rb
// ebpf-eligible methods: 1, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* top-level ivar @assigned : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_95_sk_assign_top_assigned SEC(".maps");

/* impl: tc__ingress__steer : int */
static __noinline __s64 tc__ingress__steer_inner(struct __sk_buff *ctx)
{
    __u32 _k2 = 0;
    __s64 _v3 = ({
        struct bpf_sock_tuple _spnl_aktup_1 = {};
        _spnl_aktup_1.ipv4.saddr = bpf_htonl((__u32)(2130706433));
        _spnl_aktup_1.ipv4.daddr = bpf_htonl((__u32)(2130706433));
        _spnl_aktup_1.ipv4.sport = bpf_htons((__u16)(12345));
        _spnl_aktup_1.ipv4.dport = bpf_htons((__u16)(9999));
        struct bpf_sock *_spnl_ask_1 = bpf_sk_lookup_tcp(ctx, &_spnl_aktup_1, sizeof(_spnl_aktup_1.ipv4), -1, 0);
        __s64 _spnl_akr_1 = -1;
        if (_spnl_ask_1) { _spnl_akr_1 = (__s64)bpf_sk_assign(ctx, _spnl_ask_1, 0); bpf_sk_release(_spnl_ask_1); }
        _spnl_akr_1;
    });
    bpf_map_update_elem(&u_95_sk_assign_top_assigned, &_k2, &_v3, BPF_ANY);
    return 0;
}

/* entry wrapper: tc__ingress__steer [tc_ingress -> tcx/ingress] */
SEC("tcx/ingress")
int tc__ingress__steer(struct __sk_buff *ctx)
{
    (void)ctx;
    return (int)tc__ingress__steer_inner(ctx);
}
