// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 98_bool_sig.rb
// ebpf-eligible methods: 3, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
#include <bpf/bpf_tracing.h>
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit int-event channel === */
struct u_98_bool_sig_event {
    struct spnl_event_hdr hdr;
    __s64 value;
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_98_bool_sig_events SEC(".maps");

/* ctx for is_big — userspace fills before bpf_prog_test_run */
struct is_big_ctx {
    __s64 size;
};

/* ctx for both — userspace fills before bpf_prog_test_run */
struct both_ctx {
    __s32 flag;
};

/* ctx for kprobe__tcp_sendmsg — userspace fills before bpf_prog_test_run */
struct kprobe__tcp_sendmsg_ctx {
    __s64 sk;
    __s64 msg;
    __s64 size;
};

/* impl: is_big : bool  params: size: int */
static __noinline __s32 is_big_inner(__s64 size)
{
    return size > 256;
}

/* entry wrapper: is_big */
SEC("syscall")
int is_big(struct is_big_ctx *ctx)
{
    return (int)is_big_inner(ctx->size);
}

/* impl: both : bool  params: flag: bool */
static __noinline __s32 both_inner(__s32 flag)
{
    return flag;
}

/* entry wrapper: both */
SEC("syscall")
int both(struct both_ctx *ctx)
{
    return (int)both_inner(ctx->flag);
}

/* impl: kprobe__tcp_sendmsg : void  params: sk: int, msg: int, size: int */
static __noinline void kprobe__tcp_sendmsg_inner(__s64 sk, __s64 msg, __s64 size)
{
    __s64 _if1 = 0;
    if (both_inner(is_big_inner(size))) {
        {
            struct u_98_bool_sig_event *_e2 = bpf_ringbuf_reserve(&u_98_bool_sig_events, sizeof(*_e2), 0);
            if (_e2) {
                _e2->hdr.type = SPNL_EVT_USER_BASE;
                _e2->hdr.version = SPNL_EVENT_HDR_VERSION;
                _e2->hdr.reserved = 0;
                _e2->hdr.timestamp = bpf_ktime_get_ns();
                _e2->value = size;
                bpf_ringbuf_submit(_e2, 0);
            }
        }
        _if1 = 0;
    }
}

/* entry wrapper: kprobe__tcp_sendmsg [kprobe -> kprobe/tcp_sendmsg] */
SEC("kprobe/tcp_sendmsg")
int kprobe__tcp_sendmsg(struct pt_regs *ctx)
{
    (void)ctx;
    kprobe__tcp_sendmsg_inner((__s64)PT_REGS_PARM1(ctx), (__s64)PT_REGS_PARM2(ctx), (__s64)PT_REGS_PARM3(ctx));
    return 0;
}
