// SPDX-License-Identifier: GPL-2.0 OR MIT
//
// GENERATED by spinel-ebpf. Do not edit by hand.
// Source unit: 99_emit_path.rb
// ebpf-eligible methods: 2, classes touched: 0

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include "spnl/types.h"
char LICENSE[] SEC("license") = "Dual MIT/GPL";

/* === per-unit string-event channel === */
struct u_99_emit_path_str_event {
    struct spnl_event_hdr hdr;
    char str[256];
};

struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} u_99_emit_path_str_events SEC(".maps");

/* top-level ivar @opens : int */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __s64);
    __uint(max_entries, 1);
} u_99_emit_path_top_opens SEC(".maps");

/* ctx for lsm__file_open — userspace fills before bpf_prog_test_run */
struct lsm__file_open_ctx {
    __s64 file;
    __s64 ret;
};

/* ctx for fmod_ret__security_file_open — userspace fills before bpf_prog_test_run */
struct fmod_ret__security_file_open_ctx {
    __s64 file;
    __s64 ret;
};

/* impl: lsm__file_open : int  params: file: int, ret: int */
static __noinline __s64 lsm__file_open_inner(__s64 file, __s64 ret)
{
    __u32 _k1 = 0;
    __s64 *_p2 = bpf_map_lookup_elem(&u_99_emit_path_top_opens, &_k1);
    __u32 _k3 = 0;
    __s64 _v4 = (_p2 ? *_p2 : 0) + 1;
    bpf_map_update_elem(&u_99_emit_path_top_opens, &_k3, &_v4, BPF_ANY);
    {
        struct u_99_emit_path_str_event *_pe5 = bpf_ringbuf_reserve(&u_99_emit_path_str_events, sizeof(*_pe5), 0);
        if (_pe5) {
            _pe5->hdr.type = SPNL_EVT_USER_BASE;
            _pe5->hdr.version = SPNL_EVENT_HDR_VERSION;
            _pe5->hdr.reserved = 0;
            _pe5->hdr.timestamp = bpf_ktime_get_ns();
            __builtin_memset(_pe5->str, 0, sizeof(_pe5->str));
            bpf_d_path(&((struct file *)(unsigned long)(file))->f_path, _pe5->str, sizeof(_pe5->str));
            bpf_ringbuf_submit(_pe5, 0);
        }
    }
    return 0;
}

/* entry wrapper: lsm__file_open [lsm -> lsm/file_open] */
SEC("lsm/file_open")
int lsm__file_open(__u64 *ctx)
{
    (void)ctx;
    return (int)lsm__file_open_inner((__s64)ctx[0], (__s64)ctx[1]);
}

/* impl: fmod_ret__security_file_open : int  params: file: int, ret: int */
static __noinline __s64 fmod_ret__security_file_open_inner(__s64 file, __s64 ret)
{
    {
        struct u_99_emit_path_str_event *_pe1 = bpf_ringbuf_reserve(&u_99_emit_path_str_events, sizeof(*_pe1), 0);
        if (_pe1) {
            _pe1->hdr.type = SPNL_EVT_USER_BASE;
            _pe1->hdr.version = SPNL_EVENT_HDR_VERSION;
            _pe1->hdr.reserved = 0;
            _pe1->hdr.timestamp = bpf_ktime_get_ns();
            __builtin_memset(_pe1->str, 0, sizeof(_pe1->str));
            bpf_d_path(&((struct file *)(unsigned long)(file))->f_path, _pe1->str, sizeof(_pe1->str));
            bpf_ringbuf_submit(_pe1, 0);
        }
    }
    return ret;
}

/* entry wrapper: fmod_ret__security_file_open [fmod_ret -> fmod_ret/security_file_open] */
SEC("fmod_ret/security_file_open")
int fmod_ret__security_file_open(__u64 *ctx)
{
    (void)ctx;
    return (int)fmod_ret__security_file_open_inner((__s64)ctx[0], (__s64)ctx[1]);
}
