/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "opentelemetry/proto/collector/trace/v1/trace_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(opentelemetry_proto_collector_trace_v1_ExportTraceServiceRequest, opentelemetry_proto_collector_trace_v1_ExportTraceServiceRequest, AUTO)


PB_BIND(opentelemetry_proto_collector_trace_v1_ExportTraceServiceResponse, opentelemetry_proto_collector_trace_v1_ExportTraceServiceResponse, AUTO)


PB_BIND(opentelemetry_proto_collector_trace_v1_ExportTracePartialSuccess, opentelemetry_proto_collector_trace_v1_ExportTracePartialSuccess, AUTO)



