/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "opentelemetry/proto/logs/v1/logs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(opentelemetry_proto_logs_v1_LogsData, opentelemetry_proto_logs_v1_LogsData, AUTO)


PB_BIND(opentelemetry_proto_logs_v1_ResourceLogs, opentelemetry_proto_logs_v1_ResourceLogs, AUTO)


PB_BIND(opentelemetry_proto_logs_v1_ScopeLogs, opentelemetry_proto_logs_v1_ScopeLogs, AUTO)


PB_BIND(opentelemetry_proto_logs_v1_LogRecord, opentelemetry_proto_logs_v1_LogRecord, AUTO)







