/* GENERATED by tools/gen_record_mirror.c from src/codegen_c/record_schema.h.
 * Do not edit by hand -- edit the schema table and re-run
 *     make -C src/codegen_c mirror
 * then commit this file (a derived artifact, like templates_gen.h).
 *
 * Userspace mirror of the ringbuf record contracts. Both ends now
 * derive from one declaration: the kernel producer struct is generated from the
 * schema table and so are the offsets below, so a producer/consumer
 * offset desync is not expressible.
 *
 * The SPNL_EGRESS_* macros are the other half of the same contract:
 * the OpenTelemetry attribute keys the consumer puts on the span it builds. The
 * runtime uses these macros so the keys have one author (the schema table) and
 * `capabilities --json` cannot drift from what actually goes on the wire.
 *
 * The spnl_rec_<id>_<prop>() accessors are what a Ruby typed consumer
 * (`on_emit :<id> do |ev| ... end`) calls for `ev.<prop>`; they are compiled only
 * in the TU that #defines SPNL_REC_CONSUME_IMPL. Their SPNL_REC_DERIVED_*_CAP
 * macros are not: the runtime's span builder passes the same capacity to the same
 * derivation, so a long value cannot truncate differently on the two sides
 * (each capacity is that derivation's own bound, not a shared default).
 *
 * The spnl_valmap_<id>() lookups are the type-driven half: a CODE -- a
 * value from a closed set whose members have names -- has no domain logic to
 * keep in C, only a table, so the table is the declaration and this is its
 * generated form. They sit OUTSIDE the impl guard because both the accessor
 * and the span builder call them, which is what makes `ev.tcp_state` and
 * spnl.conn.tcp_state one function's output rather than two switches.
 *
 * Prerequisite: __u16/__u32/__u64 must already be visible (host side that means
 * <bpf/libbpf.h> or <linux/types.h>), because the record header field has type
 * `struct spnl_event_hdr` from include/spnl/types.h. */
#ifndef SPNL_RECORD_MIRROR_BOUNDS_H
#define SPNL_RECORD_MIRROR_BOUNDS_H

/* bounds set "otel_duration_s", in s -- OpenTelemetry eBPF Instrumentation (OBI, ex-Beyla) pkg/export/bucket.go -- the default duration buckets its HTTP/RPC duration metrics use. They were adopted for http.server.request.duration so that the two agents' histograms are comparable, and the array itself is now the declaration both sides read */
#define SPNL_BOUNDS_OTEL_DURATION_S_N 15
#define SPNL_BOUNDS_OTEL_DURATION_S_INIT { 0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 }

/* bounds set "log2_ns_31", in ns -- derived from the kernel's own histogram: every boundary is 2^k - 1, the exclusive upper edge of a spnl_hist_log2 slot, so each bucket is a whole number of slots and no count is ever split. The count 31 is Splunk Observability Cloud's documented ceiling ("Use no more than 31 bucket boundaries when sending histograms"; more are dropped -- measured, and dropped silently behind HTTP 200). The split point between one-to-one and paired buckets is measured, not chosen */
#define SPNL_BOUNDS_LOG2_NS_31_N 31
#define SPNL_BOUNDS_LOG2_NS_31_INIT { 1, 3, 7, 15, 31, 63, 127, 255, 511, 1023, 2047, 4095, 8191, 16383, 32767, 65535, 131071, 262143, 524287, 1048575, 2097151, 4194303, 8388607, 16777215, 33554431, 67108863, 134217727, 536870911, 2147483647, 8589934591, 34359738367 }
#endif /* SPNL_RECORD_MIRROR_BOUNDS_H */

#ifndef SPNL_RECORD_MIRROR_MACROS_ONLY
#ifndef SPNL_RECORD_MIRROR_GEN_H
#define SPNL_RECORD_MIRROR_GEN_H

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "spnl/types.h"

/* ===================== declared value maps =====================
 * A CODE -- a value from a closed set whose members have names -- is the one
 * derivation whose implementation IS its declaration, so these lookups are
 * generated from src/codegen_c/record_schema.h rather than written in the
 * runtime. They live outside SPNL_REC_CONSUME_IMPL because BOTH ends call
 * them: the typed consumer's accessor (`ev.tcp_state`) and the span builder
 * that fills the attribute -- one function, so the two cannot drift. */

/* --- value map "tcp_state" ---
 * authority: the kernel's own TCP state enum (include/net/tcp_states.h; the
 * same values are frozen into the uapi enum BPF_TCP_* in
 * include/uapi/linux/bpf.h). Both are in vmlinux BTF, so the declaration
 * below is checked against the running kernel rather than trusted
 * the state a sock was in, spelled as the kernel spells it (without the TCP_
 * prefix, which is the enum's namespace and not part of the name of the
 * state)
 * An unnamed value renders as shown in the default branch.
 * Architecture-invariant: a map that cannot say so does not compile
 * (check_valmap() in tools/gen_record_mirror.c).
 */
static inline void spnl_valmap_tcp_state(long v, char *out, int cap) {
    const char *name = 0;
    switch (v) {
    case 1L: name = "ESTABLISHED"; break;
    case 2L: name = "SYN_SENT"; break;
    case 3L: name = "SYN_RECV"; break;
    case 4L: name = "FIN_WAIT1"; break;
    case 5L: name = "FIN_WAIT2"; break;
    case 6L: name = "TIME_WAIT"; break;
    case 7L: name = "CLOSE"; break;
    case 8L: name = "CLOSE_WAIT"; break;
    case 9L: name = "LAST_ACK"; break;
    case 10L: name = "LISTEN"; break;
    case 11L: name = "CLOSING"; break;
    case 12L: name = "NEW_SYN_RECV"; break;
    case 13L: name = "BOUND_INACTIVE"; break;
    default: break;
    }
    if (!out || cap <= 0) return;
    if (name) snprintf(out, (size_t)cap, "%s", name);
    else      snprintf(out, (size_t)cap, "unnamed(%ld)", v);
}

/* --- value map "conn_direction" ---
 * authority: this project's reading of the pre-ESTABLISHED TCP state. The
 * names are this project's (semconv has no connection-direction key); only
 * the two keys come from the kernel enum, and those are checked against its
 * BTF
 * "active" = we initiated, "passive" = we accepted, "other" = a transition
 * into ESTABLISHED from neither (and, on a probe that emits every transition,
 * any transition at all -- which is what spnl.conn.tcp_state is for)
 * An unnamed value renders as shown in the default branch.
 * Architecture-invariant: a map that cannot say so does not compile
 * (check_valmap() in tools/gen_record_mirror.c).
 */
static inline void spnl_valmap_conn_direction(long v, char *out, int cap) {
    const char *name = 0;
    switch (v) {
    case 2L: name = "active"; break;
    case 3L: name = "passive"; break;
    default: break;
    }
    if (!out || cap <= 0) return;
    if (name) snprintf(out, (size_t)cap, "%s", name);
    else      snprintf(out, (size_t)cap, "%s", "other");
}


extern void spnl_recmetric_observe(int metric, const char *const *label_values,
                                   int nlabels, int has_value, double value);
/* ===================== channel "dns" =====================
 * record struct: <unit>_dns_event   ringbuf map: <unit>_dns_events (256 * 1024)
 * 7 fields, 128 bytes on the wire. */

enum {
    SPNL_REC_DNS_OFF_HDR         =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_DNS_OFF_PID         =  16,   /* __u32, 4 B */
    SPNL_REC_DNS_OFF_COMM        =  20,   /* char[16], 16 B */
    SPNL_REC_DNS_OFF_RAW         =  36,   /* unsigned char[64], 64 B */
    SPNL_REC_DNS_OFF_CGID        = 104,   /* __u64, 8 B */
    SPNL_REC_DNS_OFF_DURATION_NS = 112,   /* __u64, 8 B */
    SPNL_REC_DNS_OFF_RAW_STATUS  = 120,   /* __s32, 4 B */
    SPNL_REC_DNS_SIZE            = 128,   /* whole record, incl. trailing pad */
    SPNL_REC_DNS_MIN             = 120,   /* accepted prefix: through `duration_ns` (later fields read as zero) */
};

typedef struct spnl_rec_dns {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint32_t pid;                            /* @16   producer tgid (init-ns) */
    char comm[16];                           /* @20   bpf_get_current_comm -> process.executable.name */
    unsigned char raw[64];                   /* @36   first 64B of the DNS payload; QNAME parsed in userspace */
    uint64_t cgid;                           /* @104  cgroup id -> k8s.* pod attribution */
    uint64_t duration_ns;                    /* @112  resolution RTT; 0 = query-only */
    int32_t raw_status;                      /* @120  what happened when the kernel tried to fill `raw`. 0 = the bytes are the sender's; -1 = there was no user buffer to read (msg_iter described pages or kernel memory); anything else = the errno bpf_probe_read_user returned. The return value used to be discarded, so a record carrying no bytes was indistinguishable from one whose bytes did not parse, and the drain reported the second reason for the first cause. NOT exposed to Ruby: a bare errno is exactly the kind of number the value-map rule is about, and what a consumer wants -- `ev.qname` -- is already empty in both cases. The drain reads it to pick the drop reason it prints */
} spnl_rec_dns_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_dns_t, hdr) == SPNL_REC_DNS_OFF_HDR,
               "spnl_rec_dns_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_dns_t, pid) == SPNL_REC_DNS_OFF_PID,
               "spnl_rec_dns_t.pid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_dns_t, comm) == SPNL_REC_DNS_OFF_COMM,
               "spnl_rec_dns_t.comm moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_dns_t, raw) == SPNL_REC_DNS_OFF_RAW,
               "spnl_rec_dns_t.raw moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_dns_t, cgid) == SPNL_REC_DNS_OFF_CGID,
               "spnl_rec_dns_t.cgid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_dns_t, duration_ns) == SPNL_REC_DNS_OFF_DURATION_NS,
               "spnl_rec_dns_t.duration_ns moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_dns_t, raw_status) == SPNL_REC_DNS_OFF_RAW_STATUS,
               "spnl_rec_dns_t.raw_status moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_dns_t) == SPNL_REC_DNS_SIZE,
               "spnl_rec_dns_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_dns_unpack(const void *data, size_t size, spnl_rec_dns_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_DNS_MIN) return -1;
    memset(out, 0, sizeof *out);   /* appended fields read as zero on an older producer */
    memcpy(&out->hdr, p + SPNL_REC_DNS_OFF_HDR, sizeof out->hdr);
    memcpy(&out->pid, p + SPNL_REC_DNS_OFF_PID, sizeof out->pid);
    memcpy(out->comm, p + SPNL_REC_DNS_OFF_COMM, sizeof out->comm);
    out->comm[sizeof out->comm - 1] = '\0';   /* char[] = C string */
    memcpy(out->raw, p + SPNL_REC_DNS_OFF_RAW, sizeof out->raw);
    memcpy(&out->cgid, p + SPNL_REC_DNS_OFF_CGID, sizeof out->cgid);
    memcpy(&out->duration_ns, p + SPNL_REC_DNS_OFF_DURATION_NS, sizeof out->duration_ns);
    if (size >= (size_t)124) memcpy(&out->raw_status, p + SPNL_REC_DNS_OFF_RAW_STATUS, sizeof out->raw_status);
    return 0;
}

/* --- egress contract for channel "dns" ---
 * spnl_otlp_dns_span_push() turns one record into a span named "resolve {dns.question.name}"
 * (SpanKind INTERNAL; start = hdr.timestamp (ktime -> unix); end = start + duration_ns (equal to start for emit_dns)).
 * Note: The request-tree push (spnl_otlp_request_tree_push) consumes the same record and the same attribute keys, but nests it under a request span as a CLIENT child.
 * The runtime spells these keys via the macros below, so the attribute
 * contract has exactly one author: the schema table. */
#define SPNL_EGRESS_DNS_SPAN_NAME_FMT                "resolve %s"
#define SPNL_EGRESS_DNS_ATTR_DNS_QUESTION_NAME       "dns.question.name"   /* semconv <- raw[64] -> QNAME (length-prefixed labels walked in userspace) */
#define SPNL_EGRESS_DNS_ATTR_PROCESS_EXECUTABLE_NAME "process.executable.name"   /* semconv <- comm[16] (bpf_get_current_comm) */
#define SPNL_EGRESS_DNS_ATTR_SPNL_DNS_LATENCY_NS     "spnl.dns.latency_ns"   /* spinel <- duration_ns */

/* --- typed consumer for channel "dns" ---
 * `on_emit :dns do |ev| ... end` lowers `ev.<prop>` to these accessors, so the
 * property set a Ruby consumer sees is generated from the same table as the
 * record struct. `i` is the record's index in the last drain (the opaque handle
 * Ruby holds); the byte image itself never crosses the FFI boundary.
 *
 * Expanded in exactly one TU: the one that #defines SPNL_REC_CONSUME_IMPL before
 * including this header (src/runtime/otlp/otlp_agent.c). That TU must define the
 * two functions declared below -- the drained-record lookup and each declared
 * derivation -- and a missing one is a link error, not a silent wrong value. */

/* Declared output capacity of each string derivation, in bytes
 * including the NUL, and >= the longest value that derivation can return
 * (the schema table says why). Handed to the impl by the accessor below AND
 * by the runtime's span builder, so `ev.<prop>` and the attribute it feeds
 * are the same function's output at the same width. */
#define SPNL_REC_DERIVED_DNS_QNAME_CAP           256

#ifdef SPNL_REC_CONSUME_IMPL
const spnl_rec_dns_t *spnl_rec_dns_at(int i);
void spnl_dns_qname(const unsigned char *src, char *out, int cap);   /* qname <- raw */

long spnl_rec_dns_pid(int i) {
    const spnl_rec_dns_t *r = spnl_rec_dns_at(i);
    return r ? (long)r->pid : 0;   /* producer tgid (init-ns) */
}
const char *spnl_rec_dns_comm(int i) {
    const spnl_rec_dns_t *r = spnl_rec_dns_at(i);
    return r ? r->comm : "";   /* bpf_get_current_comm -> process.executable.name */
}
long spnl_rec_dns_cgid(int i) {
    const spnl_rec_dns_t *r = spnl_rec_dns_at(i);
    return r ? (long)r->cgid : 0;   /* cgroup id -> k8s.* pod attribution */
}
long spnl_rec_dns_duration_ns(int i) {
    const spnl_rec_dns_t *r = spnl_rec_dns_at(i);
    return r ? (long)r->duration_ns : 0;   /* resolution RTT; 0 = query-only */
}
const char *spnl_rec_dns_qname(int i) {
    const spnl_rec_dns_t *r = spnl_rec_dns_at(i);
    static char buf[SPNL_REC_DERIVED_DNS_QNAME_CAP];
    if (!r) return "";
    spnl_dns_qname(r->raw, buf, (int)sizeof buf);   /* derived: qname */
    return buf;
}
#endif /* SPNL_REC_CONSUME_IMPL */

/* ===================== channel "conn" =====================
 * record struct: <unit>_conn_event   ringbuf map: <unit>_conn_events (256 * 1024)
 * 11 fields, 88 bytes on the wire. */

enum {
    SPNL_REC_CONN_OFF_HDR       =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_CONN_OFF_PID       =  16,   /* __u32, 4 B */
    SPNL_REC_CONN_OFF_COMM      =  20,   /* char[16], 16 B */
    SPNL_REC_CONN_OFF_DADDR     =  36,   /* __u32, 4 B */
    SPNL_REC_CONN_OFF_DPORT     =  40,   /* __u16, 2 B */
    SPNL_REC_CONN_OFF_FAMILY    =  42,   /* __u16, 2 B */
    SPNL_REC_CONN_OFF_SRTT_US   =  48,   /* __s64, 8 B */
    SPNL_REC_CONN_OFF_CGID      =  56,   /* __u64, 8 B */
    SPNL_REC_CONN_OFF_OLDSTATE  =  64,   /* __u32, 4 B */
    SPNL_REC_CONN_OFF_DADDR6_HI =  72,   /* __u64, 8 B */
    SPNL_REC_CONN_OFF_DADDR6_LO =  80,   /* __u64, 8 B */
    SPNL_REC_CONN_SIZE          =  88,   /* whole record, incl. trailing pad */
    SPNL_REC_CONN_MIN           =  88,   /* the whole record is required */
};

typedef struct spnl_rec_conn {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint32_t pid;                            /* @16   producer tgid; sock_owner_set restores it when the ESTABLISHED transition fires in softirq */
    char comm[16];                           /* @20   bpf_get_current_comm -- the connecting process, not the idle task */
    uint32_t daddr;                          /* @36   remote IPv4 address, network byte order (valid when family == AF_INET) */
    uint16_t dport;                          /* @40   remote port, host byte order */
    uint16_t family;                         /* @42   address family (2 = AF_INET, 10 = AF_INET6) */
    int64_t srtt_us;                         /* @48   tcp_sock->srtt_us via CO-RE, on the wire in the kernel's 1/8 us scale. Not exposed raw: the us value is the derived property ev.srtt_us, which is the same function's output as the span attribute net.peer.srtt_us */
    uint64_t cgid;                           /* @56   cgroup id -> k8s.* pod attribution */
    uint32_t oldstate;                       /* @64   TCP state before ESTABLISHED (2 = SYN_SENT -> active, 3 = SYN_RECV -> passive) */
    uint64_t daddr6_hi;                      /* @72   remote IPv6 address, bytes 0..7 (network order) */
    uint64_t daddr6_lo;                      /* @80   remote IPv6 address, bytes 8..15 (network order) */
} spnl_rec_conn_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_conn_t, hdr) == SPNL_REC_CONN_OFF_HDR,
               "spnl_rec_conn_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, pid) == SPNL_REC_CONN_OFF_PID,
               "spnl_rec_conn_t.pid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, comm) == SPNL_REC_CONN_OFF_COMM,
               "spnl_rec_conn_t.comm moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, daddr) == SPNL_REC_CONN_OFF_DADDR,
               "spnl_rec_conn_t.daddr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, dport) == SPNL_REC_CONN_OFF_DPORT,
               "spnl_rec_conn_t.dport moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, family) == SPNL_REC_CONN_OFF_FAMILY,
               "spnl_rec_conn_t.family moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, srtt_us) == SPNL_REC_CONN_OFF_SRTT_US,
               "spnl_rec_conn_t.srtt_us moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, cgid) == SPNL_REC_CONN_OFF_CGID,
               "spnl_rec_conn_t.cgid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, oldstate) == SPNL_REC_CONN_OFF_OLDSTATE,
               "spnl_rec_conn_t.oldstate moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, daddr6_hi) == SPNL_REC_CONN_OFF_DADDR6_HI,
               "spnl_rec_conn_t.daddr6_hi moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_conn_t, daddr6_lo) == SPNL_REC_CONN_OFF_DADDR6_LO,
               "spnl_rec_conn_t.daddr6_lo moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_conn_t) == SPNL_REC_CONN_SIZE,
               "spnl_rec_conn_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_conn_unpack(const void *data, size_t size, spnl_rec_conn_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_CONN_MIN) return -1;
    memcpy(&out->hdr, p + SPNL_REC_CONN_OFF_HDR, sizeof out->hdr);
    memcpy(&out->pid, p + SPNL_REC_CONN_OFF_PID, sizeof out->pid);
    memcpy(out->comm, p + SPNL_REC_CONN_OFF_COMM, sizeof out->comm);
    out->comm[sizeof out->comm - 1] = '\0';   /* char[] = C string */
    memcpy(&out->daddr, p + SPNL_REC_CONN_OFF_DADDR, sizeof out->daddr);
    memcpy(&out->dport, p + SPNL_REC_CONN_OFF_DPORT, sizeof out->dport);
    memcpy(&out->family, p + SPNL_REC_CONN_OFF_FAMILY, sizeof out->family);
    memcpy(&out->srtt_us, p + SPNL_REC_CONN_OFF_SRTT_US, sizeof out->srtt_us);
    memcpy(&out->cgid, p + SPNL_REC_CONN_OFF_CGID, sizeof out->cgid);
    memcpy(&out->oldstate, p + SPNL_REC_CONN_OFF_OLDSTATE, sizeof out->oldstate);
    memcpy(&out->daddr6_hi, p + SPNL_REC_CONN_OFF_DADDR6_HI, sizeof out->daddr6_hi);
    memcpy(&out->daddr6_lo, p + SPNL_REC_CONN_OFF_DADDR6_LO, sizeof out->daddr6_lo);
    return 0;
}

/* --- egress contract for channel "conn" ---
 * spnl_otlp_conn_span_push() turns one record into a span named "connect {network.peer.address}:{network.peer.port}"
 * (SpanKind INTERNAL; start = end = hdr.timestamp (ktime -> unix); a connect is a point event, so duration is 0).
 * Note: The request-tree push consumes the same record and the same attribute keys, but nests it under a request span as a CLIENT child (and drops network.transport / network.type there).
 * The runtime spells these keys via the macros below, so the attribute
 * contract has exactly one author: the schema table. */
#define SPNL_EGRESS_CONN_SPAN_NAME_FMT                "connect %s:%u"
#define SPNL_EGRESS_CONN_ATTR_NETWORK_PEER_ADDRESS    "network.peer.address"   /* semconv <- daddr (AF_INET) or daddr6_hi/lo (AF_INET6) -> inet_ntop */
#define SPNL_EGRESS_CONN_ATTR_NETWORK_PEER_PORT       "network.peer.port"   /* semconv <- dport */
#define SPNL_EGRESS_CONN_ATTR_NETWORK_TRANSPORT       "network.transport"   /* semconv <- constant "tcp" */
#define SPNL_EGRESS_CONN_ATTR_NETWORK_TYPE            "network.type"   /* semconv <- family (AF_INET -> "ipv4", AF_INET6 -> "ipv6") */
#define SPNL_EGRESS_CONN_ATTR_NET_PEER_SRTT_US        "net.peer.srtt_us"   /* spinel <- srtt_us >> 3 (spnl_conn_srtt_us -- the same function as the property ev.srtt_us) */
#define SPNL_EGRESS_CONN_ATTR_SPNL_CONN_DIRECTION     "spnl.conn.direction"   /* spinel <- oldstate (SYN_SENT -> active, SYN_RECV -> passive, else other) */
#define SPNL_EGRESS_CONN_ATTR_SPNL_CONN_TCP_STATE     "spnl.conn.tcp_state"   /* spinel <- oldstate -> value map `tcp_state` (the kernel's enum, by name) */
#define SPNL_EGRESS_CONN_ATTR_PROCESS_EXECUTABLE_NAME "process.executable.name"   /* semconv <- comm[16] */

/* --- typed consumer for channel "conn" ---
 * `on_emit :conn do |ev| ... end` lowers `ev.<prop>` to these accessors, so the
 * property set a Ruby consumer sees is generated from the same table as the
 * record struct. `i` is the record's index in the last drain (the opaque handle
 * Ruby holds); the byte image itself never crosses the FFI boundary.
 *
 * Expanded in exactly one TU: the one that #defines SPNL_REC_CONSUME_IMPL before
 * including this header (src/runtime/otlp/otlp_agent.c). That TU must define the
 * two functions declared below -- the drained-record lookup and each declared
 * derivation -- and a missing one is a link error, not a silent wrong value. */

/* Declared output capacity of each string derivation, in bytes
 * including the NUL, and >= the longest value that derivation can return
 * (the schema table says why). Handed to the impl by the accessor below AND
 * by the runtime's span builder, so `ev.<prop>` and the attribute it feeds
 * are the same function's output at the same width. */
#define SPNL_REC_DERIVED_CONN_PEER_CAP           64
#define SPNL_REC_DERIVED_CONN_DIRECTION_CAP      16
#define SPNL_REC_DERIVED_CONN_TCP_STATE_CAP      24

#ifdef SPNL_REC_CONSUME_IMPL
const spnl_rec_conn_t *spnl_rec_conn_at(int i);
void spnl_conn_peer(const spnl_rec_conn_t *r, char *out, int cap);   /* peer <- family + daddr / daddr6_hi,daddr6_lo + dport */
/* direction <- oldstate via the generated value map spnl_valmap_conn_direction() */
/* tcp_state <- oldstate via the generated value map spnl_valmap_tcp_state() */
long spnl_conn_srtt_us(const spnl_rec_conn_t *r);   /* srtt_us <- srtt_us (the kernel's 1/8 us scale) */

long spnl_rec_conn_pid(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    return r ? (long)r->pid : 0;   /* producer tgid; sock_owner_set restores it when the ESTABLISHED transition fires in softirq */
}
const char *spnl_rec_conn_comm(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    return r ? r->comm : "";   /* bpf_get_current_comm -- the connecting process, not the idle task */
}
long spnl_rec_conn_dport(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    return r ? (long)r->dport : 0;   /* remote port, host byte order */
}
long spnl_rec_conn_cgid(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    return r ? (long)r->cgid : 0;   /* cgroup id -> k8s.* pod attribution */
}
const char *spnl_rec_conn_peer(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    static char buf[SPNL_REC_DERIVED_CONN_PEER_CAP];
    if (!r) return "";
    spnl_conn_peer(r, buf, (int)sizeof buf);   /* derived: peer */
    return buf;
}
const char *spnl_rec_conn_direction(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    static char buf[SPNL_REC_DERIVED_CONN_DIRECTION_CAP];
    if (!r) return "";
    spnl_valmap_conn_direction((long)r->oldstate, buf, (int)sizeof buf);   /* derived: direction */
    return buf;
}
const char *spnl_rec_conn_tcp_state(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    static char buf[SPNL_REC_DERIVED_CONN_TCP_STATE_CAP];
    if (!r) return "";
    spnl_valmap_tcp_state((long)r->oldstate, buf, (int)sizeof buf);   /* derived: tcp_state */
    return buf;
}
long spnl_rec_conn_srtt_us(int i) {
    const spnl_rec_conn_t *r = spnl_rec_conn_at(i);
    return r ? (long)spnl_conn_srtt_us(r) : 0;   /* derived: srtt_us */
}

/* --- metric intake for channel "conn" ---
 * Called once per drained record, on the one path every record of this channel
 * takes (the ringbuf callback), so the concise push and the typed consumer feed
 * the same aggregate. Every label value below is produced by CALLING the
 * declared derivation the span attribute calls, so the metric cannot describe a
 * different request from the span built out of the same bytes; projecting a
 * value onto its declared set is the runtime's job, in one place. */
static inline void spnl_recmetric_observe_conn(const spnl_rec_conn_t *r) {
    if (!r) return;
    {   /* spnl.conn.count */
        char lb0[16];
        const char *lv[1];
        spnl_valmap_conn_direction((long)r->oldstate, lb0, (int)sizeof lb0);
        lv[0] = lb0;
        spnl_recmetric_observe(0, lv, 1, 0, 0.0);
    }
}
#endif /* SPNL_REC_CONSUME_IMPL */

/* ===================== channel "l7" =====================
 * record struct: <unit>_l7_event   ringbuf map: <unit>_l7_events (256 * 1024)
 * 9 fields, 72 bytes on the wire. */

enum {
    SPNL_REC_L7_OFF_HDR         =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_L7_OFF_PID         =  16,   /* __u32, 4 B */
    SPNL_REC_L7_OFF_COMM        =  20,   /* char[16], 16 B */
    SPNL_REC_L7_OFF_DADDR       =  36,   /* __u32, 4 B */
    SPNL_REC_L7_OFF_DPORT       =  40,   /* __u16, 2 B */
    SPNL_REC_L7_OFF_FAMILY      =  42,   /* __u16, 2 B */
    SPNL_REC_L7_OFF_START_KTIME =  48,   /* __u64, 8 B */
    SPNL_REC_L7_OFF_DURATION_NS =  56,   /* __u64, 8 B */
    SPNL_REC_L7_OFF_CGID        =  64,   /* __u64, 8 B */
    SPNL_REC_L7_SIZE            =  72,   /* whole record, incl. trailing pad */
    SPNL_REC_L7_MIN             =  72,   /* the whole record is required */
};

typedef struct spnl_rec_l7 {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint32_t pid;                            /* @16   producer tgid (the process that sent the request) */
    char comm[16];                           /* @20   bpf_get_current_comm -> process.executable.name */
    uint32_t daddr;                          /* @36   remote IPv4 address, network byte order */
    uint16_t dport;                          /* @40   remote port, host byte order */
    uint16_t family;                         /* @42   address family (2 = AF_INET; IPv6 addresses are not carried on this channel) */
    uint64_t start_ktime;                    /* @48   ktime of the first send on this socket (span start) */
    uint64_t duration_ns;                    /* @56   send -> response-visible round trip (tcp_cleanup_rbuf), = span duration */
    uint64_t cgid;                           /* @64   cgroup id -> k8s.* pod attribution */
} spnl_rec_l7_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_l7_t, hdr) == SPNL_REC_L7_OFF_HDR,
               "spnl_rec_l7_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, pid) == SPNL_REC_L7_OFF_PID,
               "spnl_rec_l7_t.pid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, comm) == SPNL_REC_L7_OFF_COMM,
               "spnl_rec_l7_t.comm moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, daddr) == SPNL_REC_L7_OFF_DADDR,
               "spnl_rec_l7_t.daddr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, dport) == SPNL_REC_L7_OFF_DPORT,
               "spnl_rec_l7_t.dport moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, family) == SPNL_REC_L7_OFF_FAMILY,
               "spnl_rec_l7_t.family moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, start_ktime) == SPNL_REC_L7_OFF_START_KTIME,
               "spnl_rec_l7_t.start_ktime moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, duration_ns) == SPNL_REC_L7_OFF_DURATION_NS,
               "spnl_rec_l7_t.duration_ns moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7_t, cgid) == SPNL_REC_L7_OFF_CGID,
               "spnl_rec_l7_t.cgid moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_l7_t) == SPNL_REC_L7_SIZE,
               "spnl_rec_l7_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_l7_unpack(const void *data, size_t size, spnl_rec_l7_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_L7_MIN) return -1;
    memcpy(&out->hdr, p + SPNL_REC_L7_OFF_HDR, sizeof out->hdr);
    memcpy(&out->pid, p + SPNL_REC_L7_OFF_PID, sizeof out->pid);
    memcpy(out->comm, p + SPNL_REC_L7_OFF_COMM, sizeof out->comm);
    out->comm[sizeof out->comm - 1] = '\0';   /* char[] = C string */
    memcpy(&out->daddr, p + SPNL_REC_L7_OFF_DADDR, sizeof out->daddr);
    memcpy(&out->dport, p + SPNL_REC_L7_OFF_DPORT, sizeof out->dport);
    memcpy(&out->family, p + SPNL_REC_L7_OFF_FAMILY, sizeof out->family);
    memcpy(&out->start_ktime, p + SPNL_REC_L7_OFF_START_KTIME, sizeof out->start_ktime);
    memcpy(&out->duration_ns, p + SPNL_REC_L7_OFF_DURATION_NS, sizeof out->duration_ns);
    memcpy(&out->cgid, p + SPNL_REC_L7_OFF_CGID, sizeof out->cgid);
    return 0;
}

/* --- egress contract for channel "l7" ---
 * spnl_otlp_l7_span_push() turns one record into a span named "request {network.peer.address}:{network.peer.port}"
 * (SpanKind CLIENT; start = start_ktime (ktime -> unix); end = start + duration_ns).
 * Note: the earlier multiplexing guard suppresses records for sockets carrying overlapping requests, so a record on this channel is always one clean request/response pair.
 * The runtime spells these keys via the macros below, so the attribute
 * contract has exactly one author: the schema table. */
#define SPNL_EGRESS_L7_SPAN_NAME_FMT                "request %s:%u"
#define SPNL_EGRESS_L7_ATTR_NETWORK_PEER_ADDRESS    "network.peer.address"   /* semconv <- daddr -> inet_ntop */
#define SPNL_EGRESS_L7_ATTR_NETWORK_PEER_PORT       "network.peer.port"   /* semconv <- dport */
#define SPNL_EGRESS_L7_ATTR_NETWORK_TRANSPORT       "network.transport"   /* semconv <- constant "tcp" */
#define SPNL_EGRESS_L7_ATTR_NETWORK_TYPE            "network.type"   /* semconv <- family (AF_INET -> "ipv4", AF_INET6 -> "ipv6") */
#define SPNL_EGRESS_L7_ATTR_SPNL_L7_LATENCY_NS      "spnl.l7.latency_ns"   /* spinel <- duration_ns */
#define SPNL_EGRESS_L7_ATTR_PROCESS_EXECUTABLE_NAME "process.executable.name"   /* semconv <- comm[16] */

/* --- typed consumer for channel "l7" ---
 * `on_emit :l7 do |ev| ... end` lowers `ev.<prop>` to these accessors, so the
 * property set a Ruby consumer sees is generated from the same table as the
 * record struct. `i` is the record's index in the last drain (the opaque handle
 * Ruby holds); the byte image itself never crosses the FFI boundary.
 *
 * Expanded in exactly one TU: the one that #defines SPNL_REC_CONSUME_IMPL before
 * including this header (src/runtime/otlp/otlp_agent.c). That TU must define the
 * two functions declared below -- the drained-record lookup and each declared
 * derivation -- and a missing one is a link error, not a silent wrong value. */
#ifdef SPNL_REC_CONSUME_IMPL
const spnl_rec_l7_t *spnl_rec_l7_at(int i);

long spnl_rec_l7_pid(int i) {
    const spnl_rec_l7_t *r = spnl_rec_l7_at(i);
    return r ? (long)r->pid : 0;   /* producer tgid (the process that sent the request) */
}
const char *spnl_rec_l7_comm(int i) {
    const spnl_rec_l7_t *r = spnl_rec_l7_at(i);
    return r ? r->comm : "";   /* bpf_get_current_comm -> process.executable.name */
}
long spnl_rec_l7_dport(int i) {
    const spnl_rec_l7_t *r = spnl_rec_l7_at(i);
    return r ? (long)r->dport : 0;   /* remote port, host byte order */
}
long spnl_rec_l7_duration_ns(int i) {
    const spnl_rec_l7_t *r = spnl_rec_l7_at(i);
    return r ? (long)r->duration_ns : 0;   /* send -> response-visible round trip (tcp_cleanup_rbuf), = span duration */
}
long spnl_rec_l7_cgid(int i) {
    const spnl_rec_l7_t *r = spnl_rec_l7_at(i);
    return r ? (long)r->cgid : 0;   /* cgroup id -> k8s.* pod attribution */
}
#endif /* SPNL_REC_CONSUME_IMPL */

/* ===================== channel "http" =====================
 * record struct: <unit>_http_event   ringbuf map: <unit>_http_events (256 * 1024)
 * 11 fields, 152 bytes on the wire. */

enum {
    SPNL_REC_HTTP_OFF_HDR         =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_HTTP_OFF_PID         =  16,   /* __u32, 4 B */
    SPNL_REC_HTTP_OFF_COMM        =  20,   /* char[16], 16 B */
    SPNL_REC_HTTP_OFF_DADDR       =  36,   /* __u32, 4 B */
    SPNL_REC_HTTP_OFF_DPORT       =  40,   /* __u16, 2 B */
    SPNL_REC_HTTP_OFF_FAMILY      =  42,   /* __u16, 2 B */
    SPNL_REC_HTTP_OFF_START_KTIME =  48,   /* __u64, 8 B */
    SPNL_REC_HTTP_OFF_DURATION_NS =  56,   /* __u64, 8 B */
    SPNL_REC_HTTP_OFF_REQ         =  64,   /* unsigned char[64], 64 B */
    SPNL_REC_HTTP_OFF_RESP        = 128,   /* unsigned char[16], 16 B */
    SPNL_REC_HTTP_OFF_CGID        = 144,   /* __u64, 8 B */
    SPNL_REC_HTTP_SIZE            = 152,   /* whole record, incl. trailing pad */
    SPNL_REC_HTTP_MIN             = 152,   /* the whole record is required */
};

typedef struct spnl_rec_http {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint32_t pid;                            /* @16   producer tgid */
    char comm[16];                           /* @20   bpf_get_current_comm -> process.executable.name */
    uint32_t daddr;                          /* @36   remote IPv4 address, network byte order; 0 on the TLS path (no sock) */
    uint16_t dport;                          /* @40   remote port, host byte order; 0 on the TLS path */
    uint16_t family;                         /* @42   address family (2 = AF_INET) */
    uint64_t start_ktime;                    /* @48   ktime of the request send (span start) */
    uint64_t duration_ns;                    /* @56   request -> response round trip, = span duration */
    unsigned char req[64];                   /* @64   first 64B of the request; "METHOD path HTTP/x" parsed in userspace */
    unsigned char resp[16];                  /* @128  first 16B of the response; "HTTP/1.1 NNN" status parsed in userspace */
    uint64_t cgid;                           /* @144  cgroup id -> k8s.* pod attribution */
} spnl_rec_http_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_http_t, hdr) == SPNL_REC_HTTP_OFF_HDR,
               "spnl_rec_http_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, pid) == SPNL_REC_HTTP_OFF_PID,
               "spnl_rec_http_t.pid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, comm) == SPNL_REC_HTTP_OFF_COMM,
               "spnl_rec_http_t.comm moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, daddr) == SPNL_REC_HTTP_OFF_DADDR,
               "spnl_rec_http_t.daddr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, dport) == SPNL_REC_HTTP_OFF_DPORT,
               "spnl_rec_http_t.dport moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, family) == SPNL_REC_HTTP_OFF_FAMILY,
               "spnl_rec_http_t.family moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, start_ktime) == SPNL_REC_HTTP_OFF_START_KTIME,
               "spnl_rec_http_t.start_ktime moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, duration_ns) == SPNL_REC_HTTP_OFF_DURATION_NS,
               "spnl_rec_http_t.duration_ns moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, req) == SPNL_REC_HTTP_OFF_REQ,
               "spnl_rec_http_t.req moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, resp) == SPNL_REC_HTTP_OFF_RESP,
               "spnl_rec_http_t.resp moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_http_t, cgid) == SPNL_REC_HTTP_OFF_CGID,
               "spnl_rec_http_t.cgid moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_http_t) == SPNL_REC_HTTP_SIZE,
               "spnl_rec_http_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_http_unpack(const void *data, size_t size, spnl_rec_http_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_HTTP_MIN) return -1;
    memcpy(&out->hdr, p + SPNL_REC_HTTP_OFF_HDR, sizeof out->hdr);
    memcpy(&out->pid, p + SPNL_REC_HTTP_OFF_PID, sizeof out->pid);
    memcpy(out->comm, p + SPNL_REC_HTTP_OFF_COMM, sizeof out->comm);
    out->comm[sizeof out->comm - 1] = '\0';   /* char[] = C string */
    memcpy(&out->daddr, p + SPNL_REC_HTTP_OFF_DADDR, sizeof out->daddr);
    memcpy(&out->dport, p + SPNL_REC_HTTP_OFF_DPORT, sizeof out->dport);
    memcpy(&out->family, p + SPNL_REC_HTTP_OFF_FAMILY, sizeof out->family);
    memcpy(&out->start_ktime, p + SPNL_REC_HTTP_OFF_START_KTIME, sizeof out->start_ktime);
    memcpy(&out->duration_ns, p + SPNL_REC_HTTP_OFF_DURATION_NS, sizeof out->duration_ns);
    memcpy(out->req, p + SPNL_REC_HTTP_OFF_REQ, sizeof out->req);
    memcpy(out->resp, p + SPNL_REC_HTTP_OFF_RESP, sizeof out->resp);
    memcpy(&out->cgid, p + SPNL_REC_HTTP_OFF_CGID, sizeof out->cgid);
    return 0;
}

/* --- egress contract for channel "http" ---
 * spnl_otlp_http_span_push() turns one record into a span named "{http.request.method} {url.path}"
 * (SpanKind CLIENT; start = start_ktime (ktime -> unix); end = start + duration_ns).
 * Note: the span carries no request body or headers -- only method, path and status leave the process.
 * The runtime spells these keys via the macros below, so the attribute
 * contract has exactly one author: the schema table. */
#define SPNL_EGRESS_HTTP_SPAN_NAME_FMT                  "%s %s"
#define SPNL_EGRESS_HTTP_ATTR_HTTP_REQUEST_METHOD       "http.request.method"   /* semconv <- req[64] -> first token */
#define SPNL_EGRESS_HTTP_ATTR_URL_PATH                  "url.path"   /* semconv <- req[64] -> second token */
#define SPNL_EGRESS_HTTP_ATTR_HTTP_RESPONSE_STATUS_CODE "http.response.status_code"   /* semconv <- resp[16] -> status digits */
#define SPNL_EGRESS_HTTP_ATTR_URL_SCHEME                "url.scheme"   /* semconv <- constant "https" */
#define SPNL_EGRESS_HTTP_ATTR_NETWORK_PEER_ADDRESS      "network.peer.address"   /* semconv <- daddr -> inet_ntop */
#define SPNL_EGRESS_HTTP_ATTR_NETWORK_PEER_PORT         "network.peer.port"   /* semconv <- dport */
#define SPNL_EGRESS_HTTP_ATTR_NETWORK_TRANSPORT         "network.transport"   /* semconv <- constant "tcp" */
#define SPNL_EGRESS_HTTP_ATTR_SPNL_HTTP_LATENCY_NS      "spnl.http.latency_ns"   /* spinel <- duration_ns */
#define SPNL_EGRESS_HTTP_ATTR_PROCESS_EXECUTABLE_NAME   "process.executable.name"   /* semconv <- comm[16] */

/* --- typed consumer for channel "http" ---
 * `on_emit :http do |ev| ... end` lowers `ev.<prop>` to these accessors, so the
 * property set a Ruby consumer sees is generated from the same table as the
 * record struct. `i` is the record's index in the last drain (the opaque handle
 * Ruby holds); the byte image itself never crosses the FFI boundary.
 *
 * Expanded in exactly one TU: the one that #defines SPNL_REC_CONSUME_IMPL before
 * including this header (src/runtime/otlp/otlp_agent.c). That TU must define the
 * two functions declared below -- the drained-record lookup and each declared
 * derivation -- and a missing one is a link error, not a silent wrong value. */

/* Declared output capacity of each string derivation, in bytes
 * including the NUL, and >= the longest value that derivation can return
 * (the schema table says why). Handed to the impl by the accessor below AND
 * by the runtime's span builder, so `ev.<prop>` and the attribute it feeds
 * are the same function's output at the same width. */
#define SPNL_REC_DERIVED_HTTP_METHOD_CAP         65
#define SPNL_REC_DERIVED_HTTP_PATH_CAP           65

#ifdef SPNL_REC_CONSUME_IMPL
const spnl_rec_http_t *spnl_rec_http_at(int i);
void spnl_http_method(const unsigned char *src, char *out, int cap);   /* method <- req */
void spnl_http_path(const unsigned char *src, char *out, int cap);   /* path <- req */
long spnl_http_status(const unsigned char *src);   /* status <- resp */

long spnl_rec_http_pid(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    return r ? (long)r->pid : 0;   /* producer tgid */
}
const char *spnl_rec_http_comm(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    return r ? r->comm : "";   /* bpf_get_current_comm -> process.executable.name */
}
long spnl_rec_http_dport(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    return r ? (long)r->dport : 0;   /* remote port, host byte order; 0 on the TLS path */
}
long spnl_rec_http_duration_ns(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    return r ? (long)r->duration_ns : 0;   /* request -> response round trip, = span duration */
}
long spnl_rec_http_cgid(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    return r ? (long)r->cgid : 0;   /* cgroup id -> k8s.* pod attribution */
}
const char *spnl_rec_http_method(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    static char buf[SPNL_REC_DERIVED_HTTP_METHOD_CAP];
    if (!r) return "";
    spnl_http_method(r->req, buf, (int)sizeof buf);   /* derived: method */
    return buf;
}
const char *spnl_rec_http_path(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    static char buf[SPNL_REC_DERIVED_HTTP_PATH_CAP];
    if (!r) return "";
    spnl_http_path(r->req, buf, (int)sizeof buf);   /* derived: path */
    return buf;
}
long spnl_rec_http_status(int i) {
    const spnl_rec_http_t *r = spnl_rec_http_at(i);
    return r ? (long)spnl_http_status(r->resp) : 0;   /* derived: status */
}

/* --- metric intake for channel "http" ---
 * Called once per drained record, on the one path every record of this channel
 * takes (the ringbuf callback), so the concise push and the typed consumer feed
 * the same aggregate. Every label value below is produced by CALLING the
 * declared derivation the span attribute calls, so the metric cannot describe a
 * different request from the span built out of the same bytes; projecting a
 * value onto its declared set is the runtime's job, in one place. */
static inline void spnl_recmetric_observe_http(const spnl_rec_http_t *r) {
    if (!r) return;
    {   /* spnl.http.client.request.duration */
        char lb0[65];
        char lb1[24];
        const char *lv[2];
        spnl_http_method(r->req, lb0, (int)sizeof lb0);
        lv[0] = lb0;
        snprintf(lb1, sizeof lb1, "%ld", spnl_http_status(r->resp));
        lv[1] = lb1;
        double v = (double)(r->duration_ns) / 1e9;
        spnl_recmetric_observe(1, lv, 2, 1, v);
    }
}
#endif /* SPNL_REC_CONSUME_IMPL */

/* ===================== channel "redis" =====================
 * record struct: <unit>_redis_event   ringbuf map: <unit>_redis_events (256 * 1024)
 * 11 fields, 152 bytes on the wire. */

enum {
    SPNL_REC_REDIS_OFF_HDR         =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_REDIS_OFF_PID         =  16,   /* __u32, 4 B */
    SPNL_REC_REDIS_OFF_COMM        =  20,   /* char[16], 16 B */
    SPNL_REC_REDIS_OFF_DADDR       =  36,   /* __u32, 4 B */
    SPNL_REC_REDIS_OFF_DPORT       =  40,   /* __u16, 2 B */
    SPNL_REC_REDIS_OFF_FAMILY      =  42,   /* __u16, 2 B */
    SPNL_REC_REDIS_OFF_START_KTIME =  48,   /* __u64, 8 B */
    SPNL_REC_REDIS_OFF_DURATION_NS =  56,   /* __u64, 8 B */
    SPNL_REC_REDIS_OFF_REQ         =  64,   /* unsigned char[64], 64 B */
    SPNL_REC_REDIS_OFF_RESP        = 128,   /* unsigned char[16], 16 B */
    SPNL_REC_REDIS_OFF_CGID        = 144,   /* __u64, 8 B */
    SPNL_REC_REDIS_SIZE            = 152,   /* whole record, incl. trailing pad */
    SPNL_REC_REDIS_MIN             = 152,   /* the whole record is required */
};

typedef struct spnl_rec_redis {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint32_t pid;                            /* @16   producer tgid */
    char comm[16];                           /* @20   bpf_get_current_comm -> process.executable.name */
    uint32_t daddr;                          /* @36   remote IPv4 address, network byte order */
    uint16_t dport;                          /* @40   remote port, host byte order */
    uint16_t family;                         /* @42   address family (2 = AF_INET) */
    uint64_t start_ktime;                    /* @48   ktime of the command send (span start) */
    uint64_t duration_ns;                    /* @56   command -> reply round trip, = span duration */
    unsigned char req[64];                   /* @64   first 64B of the RESP request; command + first key parsed in userspace (values never read) */
    unsigned char resp[16];                  /* @128  first 16B of the reply; a leading '-' marks a RESP error */
    uint64_t cgid;                           /* @144  cgroup id -> k8s.* pod attribution */
} spnl_rec_redis_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_redis_t, hdr) == SPNL_REC_REDIS_OFF_HDR,
               "spnl_rec_redis_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, pid) == SPNL_REC_REDIS_OFF_PID,
               "spnl_rec_redis_t.pid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, comm) == SPNL_REC_REDIS_OFF_COMM,
               "spnl_rec_redis_t.comm moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, daddr) == SPNL_REC_REDIS_OFF_DADDR,
               "spnl_rec_redis_t.daddr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, dport) == SPNL_REC_REDIS_OFF_DPORT,
               "spnl_rec_redis_t.dport moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, family) == SPNL_REC_REDIS_OFF_FAMILY,
               "spnl_rec_redis_t.family moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, start_ktime) == SPNL_REC_REDIS_OFF_START_KTIME,
               "spnl_rec_redis_t.start_ktime moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, duration_ns) == SPNL_REC_REDIS_OFF_DURATION_NS,
               "spnl_rec_redis_t.duration_ns moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, req) == SPNL_REC_REDIS_OFF_REQ,
               "spnl_rec_redis_t.req moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, resp) == SPNL_REC_REDIS_OFF_RESP,
               "spnl_rec_redis_t.resp moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_redis_t, cgid) == SPNL_REC_REDIS_OFF_CGID,
               "spnl_rec_redis_t.cgid moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_redis_t) == SPNL_REC_REDIS_SIZE,
               "spnl_rec_redis_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_redis_unpack(const void *data, size_t size, spnl_rec_redis_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_REDIS_MIN) return -1;
    memcpy(&out->hdr, p + SPNL_REC_REDIS_OFF_HDR, sizeof out->hdr);
    memcpy(&out->pid, p + SPNL_REC_REDIS_OFF_PID, sizeof out->pid);
    memcpy(out->comm, p + SPNL_REC_REDIS_OFF_COMM, sizeof out->comm);
    out->comm[sizeof out->comm - 1] = '\0';   /* char[] = C string */
    memcpy(&out->daddr, p + SPNL_REC_REDIS_OFF_DADDR, sizeof out->daddr);
    memcpy(&out->dport, p + SPNL_REC_REDIS_OFF_DPORT, sizeof out->dport);
    memcpy(&out->family, p + SPNL_REC_REDIS_OFF_FAMILY, sizeof out->family);
    memcpy(&out->start_ktime, p + SPNL_REC_REDIS_OFF_START_KTIME, sizeof out->start_ktime);
    memcpy(&out->duration_ns, p + SPNL_REC_REDIS_OFF_DURATION_NS, sizeof out->duration_ns);
    memcpy(out->req, p + SPNL_REC_REDIS_OFF_REQ, sizeof out->req);
    memcpy(out->resp, p + SPNL_REC_REDIS_OFF_RESP, sizeof out->resp);
    memcpy(&out->cgid, p + SPNL_REC_REDIS_OFF_CGID, sizeof out->cgid);
    return 0;
}

/* --- egress contract for channel "redis" ---
 * spnl_otlp_redis_span_push() turns one record into a span named "{db.operation.name}"
 * (SpanKind CLIENT; start = start_ktime (ktime -> unix); end = start + duration_ns).
 * Note: the record layout is identical to the http channel, which is why one drain used to serve both; each now unpacks through its own generated mirror.
 * The runtime spells these keys via the macros below, so the attribute
 * contract has exactly one author: the schema table. */
#define SPNL_EGRESS_REDIS_SPAN_NAME_FMT                "%s"
#define SPNL_EGRESS_REDIS_ATTR_DB_SYSTEM               "db.system"   /* semconv <- constant "redis" */
#define SPNL_EGRESS_REDIS_ATTR_DB_OPERATION_NAME       "db.operation.name"   /* semconv <- req[64] -> first RESP bulk string, upper-cased */
#define SPNL_EGRESS_REDIS_ATTR_DB_QUERY_TEXT           "db.query.text"   /* semconv <- req[64] -> command + first key */
#define SPNL_EGRESS_REDIS_ATTR_ERROR_TYPE              "error.type"   /* semconv <- constant "redis_error" */
#define SPNL_EGRESS_REDIS_ATTR_NETWORK_PEER_ADDRESS    "network.peer.address"   /* semconv <- daddr -> inet_ntop */
#define SPNL_EGRESS_REDIS_ATTR_NETWORK_PEER_PORT       "network.peer.port"   /* semconv <- dport */
#define SPNL_EGRESS_REDIS_ATTR_NETWORK_TRANSPORT       "network.transport"   /* semconv <- constant "tcp" */
#define SPNL_EGRESS_REDIS_ATTR_PROCESS_EXECUTABLE_NAME "process.executable.name"   /* semconv <- comm[16] */

/* ===================== channel "offcpu" =====================
 * record struct: <unit>_offcpu_event   ringbuf map: <unit>_offcpu_events (256 * 1024)
 * 11 fields, 288 bytes on the wire. */

enum {
    SPNL_REC_OFFCPU_OFF_HDR         =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_OFFCPU_OFF_PID         =  16,   /* __u32, 4 B */
    SPNL_REC_OFFCPU_OFF_COMM        =  20,   /* char[16], 16 B */
    SPNL_REC_OFFCPU_OFF_DURATION_NS =  40,   /* __u64, 8 B */
    SPNL_REC_OFFCPU_OFF_OFFCPU_NS   =  48,   /* __u64, 8 B */
    SPNL_REC_OFFCPU_OFF_WAIT_STACK  =  56,   /* __s32, 4 B */
    SPNL_REC_OFFCPU_OFF_REQ         =  60,   /* unsigned char[64], 64 B */
    SPNL_REC_OFFCPU_OFF_RESP        = 124,   /* unsigned char[16], 16 B */
    SPNL_REC_OFFCPU_OFF_CGID        = 144,   /* __u64, 8 B */
    SPNL_REC_OFFCPU_OFF_START_KTIME = 152,   /* __u64, 8 B */
    SPNL_REC_OFFCPU_OFF_HDR_EXT     = 160,   /* unsigned char[128], 128 B */
    SPNL_REC_OFFCPU_SIZE            = 288,   /* whole record, incl. trailing pad */
    SPNL_REC_OFFCPU_MIN             = 152,   /* accepted prefix: through `cgid` (later fields read as zero) */
};

typedef struct spnl_rec_offcpu {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint32_t pid;                            /* @16   producer tgid (the request handler) */
    char comm[16];                           /* @20   bpf_get_current_comm -> process.executable.name */
    uint64_t duration_ns;                    /* @40   whole request window (recv -> send), = parent span duration */
    uint64_t offcpu_ns;                      /* @48   voluntary off-CPU time accumulated inside the window. Not exposed raw: what the span carries is min(offcpu_ns, duration_ns) -- the accumulation and the window are measured by different hooks, so a record where the sum overshoots the window is expressible. The clamped value is the derived property ev.offcpu_ns, the same function's output as spnl.offcpu_ns */
    int32_t wait_stack;                      /* @56   bpf_get_stackid of the last wait; -1 = none. Classified against kallsyms in userspace. Not exposed: a stack id is an index into a per-unit BPF map, meaningless as a number in Ruby -- the reading of it is the derived property ev.wait_kind */
    unsigned char req[64];                   /* @60   first 64B of the request; "METHOD path HTTP/x" parsed in userspace */
    unsigned char resp[16];                  /* @124  first 16B of the response; "HTTP/1.1 NNN" status parsed in userspace */
    uint64_t cgid;                           /* @144  cgroup id -> k8s.* pod attribution */
    uint64_t start_ktime;                    /* @152  real window start (span anchor + child correlation); 0 on a pre- producer. Not exposed: a raw ktime is an anchor for span assembly (layer 2), not something a consumer can judge on */
    unsigned char hdr_ext[128];              /* @160  first 128B of the request head, scanned for a W3C traceparent in userspace; zero on a pre- producer. Not exposed: raw header bytes, like dns `raw` -- what a consumer wants from them (the trace context) is layer 2's, and the request line is already ev.method / ev.path */
} spnl_rec_offcpu_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_offcpu_t, hdr) == SPNL_REC_OFFCPU_OFF_HDR,
               "spnl_rec_offcpu_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, pid) == SPNL_REC_OFFCPU_OFF_PID,
               "spnl_rec_offcpu_t.pid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, comm) == SPNL_REC_OFFCPU_OFF_COMM,
               "spnl_rec_offcpu_t.comm moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, duration_ns) == SPNL_REC_OFFCPU_OFF_DURATION_NS,
               "spnl_rec_offcpu_t.duration_ns moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, offcpu_ns) == SPNL_REC_OFFCPU_OFF_OFFCPU_NS,
               "spnl_rec_offcpu_t.offcpu_ns moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, wait_stack) == SPNL_REC_OFFCPU_OFF_WAIT_STACK,
               "spnl_rec_offcpu_t.wait_stack moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, req) == SPNL_REC_OFFCPU_OFF_REQ,
               "spnl_rec_offcpu_t.req moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, resp) == SPNL_REC_OFFCPU_OFF_RESP,
               "spnl_rec_offcpu_t.resp moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, cgid) == SPNL_REC_OFFCPU_OFF_CGID,
               "spnl_rec_offcpu_t.cgid moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, start_ktime) == SPNL_REC_OFFCPU_OFF_START_KTIME,
               "spnl_rec_offcpu_t.start_ktime moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_offcpu_t, hdr_ext) == SPNL_REC_OFFCPU_OFF_HDR_EXT,
               "spnl_rec_offcpu_t.hdr_ext moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_offcpu_t) == SPNL_REC_OFFCPU_SIZE,
               "spnl_rec_offcpu_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_offcpu_unpack(const void *data, size_t size, spnl_rec_offcpu_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_OFFCPU_MIN) return -1;
    memset(out, 0, sizeof *out);   /* appended fields read as zero on an older producer */
    memcpy(&out->hdr, p + SPNL_REC_OFFCPU_OFF_HDR, sizeof out->hdr);
    memcpy(&out->pid, p + SPNL_REC_OFFCPU_OFF_PID, sizeof out->pid);
    memcpy(out->comm, p + SPNL_REC_OFFCPU_OFF_COMM, sizeof out->comm);
    out->comm[sizeof out->comm - 1] = '\0';   /* char[] = C string */
    memcpy(&out->duration_ns, p + SPNL_REC_OFFCPU_OFF_DURATION_NS, sizeof out->duration_ns);
    memcpy(&out->offcpu_ns, p + SPNL_REC_OFFCPU_OFF_OFFCPU_NS, sizeof out->offcpu_ns);
    memcpy(&out->wait_stack, p + SPNL_REC_OFFCPU_OFF_WAIT_STACK, sizeof out->wait_stack);
    memcpy(out->req, p + SPNL_REC_OFFCPU_OFF_REQ, sizeof out->req);
    memcpy(out->resp, p + SPNL_REC_OFFCPU_OFF_RESP, sizeof out->resp);
    memcpy(&out->cgid, p + SPNL_REC_OFFCPU_OFF_CGID, sizeof out->cgid);
    if (size >= (size_t)160) memcpy(&out->start_ktime, p + SPNL_REC_OFFCPU_OFF_START_KTIME, sizeof out->start_ktime);
    if (size >= (size_t)288) memcpy(out->hdr_ext, p + SPNL_REC_OFFCPU_OFF_HDR_EXT, sizeof out->hdr_ext);
    return 0;
}

/* --- egress contract for channel "offcpu" ---
 * spnl_otlp_offcpu_span_push() turns one record into a span named "{http.request.method} {url.path}"
 * (SpanKind SERVER; start = now - duration_ns (the push path) or start_ktime (the request-tree path); end = start + duration_ns).
 * Note: one record renders as TWO spans: the request window plus, when offcpu_ns > 0, a nested "off-CPU wait (<kind>)" child carrying spnl.wait.kind and spnl.offcpu_ns. The typed consumer's to_span(ev) builds the request-window span (the parent, which carries all the attributes above); nesting the wait child is the concise push's rendering of the same values.
 * The runtime spells these keys via the macros below, so the attribute
 * contract has exactly one author: the schema table. */
#define SPNL_EGRESS_OFFCPU_SPAN_NAME_FMT                  "%s %s"
#define SPNL_EGRESS_OFFCPU_ATTR_HTTP_REQUEST_METHOD       "http.request.method"   /* semconv <- req[64] -> first token */
#define SPNL_EGRESS_OFFCPU_ATTR_URL_PATH                  "url.path"   /* semconv <- req[64] -> second token */
#define SPNL_EGRESS_OFFCPU_ATTR_HTTP_RESPONSE_STATUS_CODE "http.response.status_code"   /* semconv <- resp[16] -> status digits */
#define SPNL_EGRESS_OFFCPU_ATTR_SPNL_OFFCPU_NS            "spnl.offcpu_ns"   /* spinel <- min(offcpu_ns, duration_ns) */
#define SPNL_EGRESS_OFFCPU_ATTR_SPNL_ONCPU_NS             "spnl.oncpu_ns"   /* spinel <- duration_ns - offcpu_ns */
#define SPNL_EGRESS_OFFCPU_ATTR_SPNL_WAIT_KIND            "spnl.wait.kind"   /* spinel <- wait_stack -> kallsyms scan (io / lock / sleep / net / other / none / unknown) */
#define SPNL_EGRESS_OFFCPU_ATTR_SPNL_WAIT_STACK           "spnl.wait.stack"   /* spinel <- wait_stack -> the same frames spnl.wait.kind classifies, symbolised (";"-joined, innermost first, at most SPNL_STACK_FRAMES of them) */
#define SPNL_EGRESS_OFFCPU_ATTR_PROCESS_EXECUTABLE_NAME   "process.executable.name"   /* semconv <- comm[16] */

/* --- typed consumer for channel "offcpu" ---
 * `on_emit :offcpu do |ev| ... end` lowers `ev.<prop>` to these accessors, so the
 * property set a Ruby consumer sees is generated from the same table as the
 * record struct. `i` is the record's index in the last drain (the opaque handle
 * Ruby holds); the byte image itself never crosses the FFI boundary.
 *
 * Expanded in exactly one TU: the one that #defines SPNL_REC_CONSUME_IMPL before
 * including this header (src/runtime/otlp/otlp_agent.c). That TU must define the
 * two functions declared below -- the drained-record lookup and each declared
 * derivation -- and a missing one is a link error, not a silent wrong value. */

/* Declared output capacity of each string derivation, in bytes
 * including the NUL, and >= the longest value that derivation can return
 * (the schema table says why). Handed to the impl by the accessor below AND
 * by the runtime's span builder, so `ev.<prop>` and the attribute it feeds
 * are the same function's output at the same width. */
#define SPNL_REC_DERIVED_OFFCPU_METHOD_CAP       65
#define SPNL_REC_DERIVED_OFFCPU_PATH_CAP         65
#define SPNL_REC_DERIVED_OFFCPU_WAIT_KIND_CAP    16
#define SPNL_REC_DERIVED_OFFCPU_WAIT_STACK_TRACE_CAP 448

#ifdef SPNL_REC_CONSUME_IMPL
const spnl_rec_offcpu_t *spnl_rec_offcpu_at(int i);
void spnl_http_method(const unsigned char *src, char *out, int cap);   /* method <- req */
void spnl_http_path(const unsigned char *src, char *out, int cap);   /* path <- req */
long spnl_http_status(const unsigned char *src);   /* status <- resp */
long spnl_offcpu_offcpu_ns(const spnl_rec_offcpu_t *r);   /* offcpu_ns <- offcpu_ns clamped to duration_ns */
long spnl_offcpu_oncpu_ns(const spnl_rec_offcpu_t *r);   /* oncpu_ns <- duration_ns - min(offcpu_ns, duration_ns) */
void spnl_offcpu_wait_kind(const spnl_rec_offcpu_t *r, char *out, int cap);   /* wait_kind <- wait_stack -> kallsyms scan of the captured frames */
void spnl_offcpu_wait_stack(const spnl_rec_offcpu_t *r, char *out, int cap);   /* wait_stack_trace <- wait_stack -> the same frames wait_kind classifies, symbolised */

long spnl_rec_offcpu_pid(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? (long)r->pid : 0;   /* producer tgid (the request handler) */
}
const char *spnl_rec_offcpu_comm(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? r->comm : "";   /* bpf_get_current_comm -> process.executable.name */
}
long spnl_rec_offcpu_duration_ns(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? (long)r->duration_ns : 0;   /* whole request window (recv -> send), = parent span duration */
}
long spnl_rec_offcpu_cgid(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? (long)r->cgid : 0;   /* cgroup id -> k8s.* pod attribution */
}
const char *spnl_rec_offcpu_method(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    static char buf[SPNL_REC_DERIVED_OFFCPU_METHOD_CAP];
    if (!r) return "";
    spnl_http_method(r->req, buf, (int)sizeof buf);   /* derived: method */
    return buf;
}
const char *spnl_rec_offcpu_path(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    static char buf[SPNL_REC_DERIVED_OFFCPU_PATH_CAP];
    if (!r) return "";
    spnl_http_path(r->req, buf, (int)sizeof buf);   /* derived: path */
    return buf;
}
long spnl_rec_offcpu_status(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? (long)spnl_http_status(r->resp) : 0;   /* derived: status */
}
long spnl_rec_offcpu_offcpu_ns(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? (long)spnl_offcpu_offcpu_ns(r) : 0;   /* derived: offcpu_ns */
}
long spnl_rec_offcpu_oncpu_ns(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    return r ? (long)spnl_offcpu_oncpu_ns(r) : 0;   /* derived: oncpu_ns */
}
const char *spnl_rec_offcpu_wait_kind(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    static char buf[SPNL_REC_DERIVED_OFFCPU_WAIT_KIND_CAP];
    if (!r) return "";
    spnl_offcpu_wait_kind(r, buf, (int)sizeof buf);   /* derived: wait_kind */
    return buf;
}
const char *spnl_rec_offcpu_wait_stack_trace(int i) {
    const spnl_rec_offcpu_t *r = spnl_rec_offcpu_at(i);
    static char buf[SPNL_REC_DERIVED_OFFCPU_WAIT_STACK_TRACE_CAP];
    if (!r) return "";
    spnl_offcpu_wait_stack(r, buf, (int)sizeof buf);   /* derived: wait_stack_trace */
    return buf;
}
#endif /* SPNL_REC_CONSUME_IMPL */

/* ===================== channel "l7stream" =====================
 * record struct: <unit>_l7stream_event   ringbuf map: <unit>_l7stream_events (256 * 1024)
 * 4 fields, 160 bytes on the wire. */

enum {
    SPNL_REC_L7STREAM_OFF_HDR  =   0,   /* struct spnl_event_hdr, 16 B */
    SPNL_REC_L7STREAM_OFF_SOCK =  16,   /* __u64, 8 B */
    SPNL_REC_L7STREAM_OFF_LEN  =  24,   /* __u32, 4 B */
    SPNL_REC_L7STREAM_OFF_RAW  =  28,   /* char[128], 128 B */
    SPNL_REC_L7STREAM_SIZE     = 160,   /* whole record, incl. trailing pad */
    SPNL_REC_L7STREAM_MIN      = 160,   /* the whole record is required */
};

typedef struct spnl_rec_l7stream {
    struct spnl_event_hdr hdr;               /* @0    the 16-byte common event header (type/version/reserved/timestamp) */
    uint64_t sock;                           /* @16   sock pointer -- the reassembly key (one stream per connection) */
    uint32_t len;                            /* @24   valid bytes in raw (raw is length-bounded, NOT NUL-terminated) */
    char raw[128];                           /* @28   up to 128B of stream payload; the consumer reads exactly len bytes */
} spnl_rec_l7stream_t;

/* The mirror is a byte image of the wire record: these assertions fail the
 * build if the host layout ever drifts from the schema's computed offsets. */
_Static_assert(offsetof(spnl_rec_l7stream_t, hdr) == SPNL_REC_L7STREAM_OFF_HDR,
               "spnl_rec_l7stream_t.hdr moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7stream_t, sock) == SPNL_REC_L7STREAM_OFF_SOCK,
               "spnl_rec_l7stream_t.sock moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7stream_t, len) == SPNL_REC_L7STREAM_OFF_LEN,
               "spnl_rec_l7stream_t.len moved away from the schema offset");
_Static_assert(offsetof(spnl_rec_l7stream_t, raw) == SPNL_REC_L7STREAM_OFF_RAW,
               "spnl_rec_l7stream_t.raw moved away from the schema offset");
_Static_assert(sizeof(spnl_rec_l7stream_t) == SPNL_REC_L7STREAM_SIZE,
               "spnl_rec_l7stream_t size differs from the record contract");

/* Decode one ringbuf record into the mirror. Returns 0, or -1 when the
 * record is shorter than the contract (producer older than this header). */
static inline int spnl_rec_l7stream_unpack(const void *data, size_t size, spnl_rec_l7stream_t *out) {
    const unsigned char *p = (const unsigned char *)data;
    if (!data || !out || size < (size_t)SPNL_REC_L7STREAM_MIN) return -1;
    memcpy(&out->hdr, p + SPNL_REC_L7STREAM_OFF_HDR, sizeof out->hdr);
    memcpy(&out->sock, p + SPNL_REC_L7STREAM_OFF_SOCK, sizeof out->sock);
    memcpy(&out->len, p + SPNL_REC_L7STREAM_OFF_LEN, sizeof out->len);
    memcpy(out->raw, p + SPNL_REC_L7STREAM_OFF_RAW, sizeof out->raw);
    out->raw[sizeof out->raw - 1] = '\0';   /* char[] = C string */
    return 0;
}

/* ========================== metrics ==========================
 * Declared in record_schema.h; the bounds below are COMPUTED from those
 * declarations, so "how many time series can this binary ever produce" is a
 * compile-time constant rather than something a backend discovers.
 *
 * A label's bound comes from one of exactly two places: a permitted set declared
 * on the label (and enforced when the metric is emitted -- anything outside it is
 * emitted as the fallback), or a code_to_name value map whose unnamed rendering is
 * a literal, i.e. already closed. Nothing else compiles. */

typedef struct {
    const char        *key;        /* attribute key, verbatim */
    const char *const *values;     /* permitted set, or NULL when the property is closed */
    int                nvalues;
    const char        *fallback;   /* what a value outside the set is emitted as */
    int                bound;      /* distinct values this label can ever take */
} spnl_metric_label_t;

typedef struct {
    const char                *channel;
    const char                *id;
    const char                *name;       /* OTel metric name */
    const char                *unit;
    int                        is_hist;    /* 0 = monotonic Sum, 1 = explicit-bounds Histogram */
    const double              *bounds;
    int                        nbounds;
    const spnl_metric_label_t *labels;
    int                        nlabels;
    int                        series_bound;
} spnl_metric_desc_t;

#define SPNL_RECMETRIC_MAX_LABELS         2
#define SPNL_RECMETRIC_MAX_BOUNDS         31
#define SPNL_RECMETRIC_LABEL_VAL_MAX      16
#define SPNL_RECMETRIC_COUNT              2
#define SPNL_RECMETRIC_MAX_SERIES         256
/* The sum of every declared metric's series bound. The runtime sizes its
 * accumulator by SPNL_RECMETRIC_MAX_SERIES and this is proof it fits. */
#define SPNL_RECMETRIC_TOTAL_SERIES_BOUND 183
#define SPNL_RECMETRIC_CONN_COUNT 0
#define SPNL_RECMETRIC_HTTP_DURATION 1

#ifdef SPNL_RECMETRIC_IMPL
static const double spnl_bounds_otel_duration_s[SPNL_BOUNDS_OTEL_DURATION_S_N] = SPNL_BOUNDS_OTEL_DURATION_S_INIT;
static const double spnl_bounds_log2_ns_31[SPNL_BOUNDS_LOG2_NS_31_N] = SPNL_BOUNDS_LOG2_NS_31_INIT;
static const spnl_metric_label_t spnl_ml_conn_count[1] = {
    { "spnl.conn.direction", (const char *const *)0, 0, (const char *)0, 3 },
};

static const char *const spnl_mlv_http_duration_0[9] = {
    "CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT",
    "TRACE",
};

static const char *const spnl_mlv_http_duration_1[17] = {
    "200", "201", "202", "204", "301", "302", "304", "400",
    "401", "403", "404", "409", "429", "500", "502", "503",
    "504",
};
static const spnl_metric_label_t spnl_ml_http_duration[2] = {
    { "http.request.method", spnl_mlv_http_duration_0, 9, "_OTHER", 10 },
    { "http.response.status_code", spnl_mlv_http_duration_1, 17, "_OTHER", 18 },
};

static const spnl_metric_desc_t spnl_recmetrics[2] = {
    { "conn", "count", "spnl.conn.count", "{connection}", 0, (const double *)0, 0, spnl_ml_conn_count, 1, 3 },
    { "http", "duration", "spnl.http.client.request.duration", "s", 1, spnl_bounds_otel_duration_s, 15, spnl_ml_http_duration, 2, 180 },
};
#endif /* SPNL_RECMETRIC_IMPL */

#endif /* SPNL_RECORD_MIRROR_GEN_H */
#endif /* SPNL_RECORD_MIRROR_MACROS_ONLY */
