#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Embed src/codegen_c/templates/*.template.c into a committed C header
# (src/codegen_c/templates_gen.h) as `static const char tpl_<name>[]`. The
# codegen #includes the header and fills the @SIG@ slot at emit time. This keeps
# fixed hand-written BPF C helpers as pristine, reviewable C files (separate from
# the codegen logic, .c extension so editors syntax-highlight them) while the
# compiled binary stays self-contained — no runtime file dependency for either
# the host or the in-process build. (The `templates/` subdir is not on any build
# glob, so the .c-suffixed templates are never accidentally compiled.)
#
# Run after editing a template, then commit templates_gen.h (a derived artifact,
# like tests/golden/). `make -C src/codegen_c templates` regenerates it.
TPL_DIR = File.expand_path("../src/codegen_c/templates", __dir__)
OUT     = File.expand_path("../src/codegen_c/templates_gen.h", __dir__)

# C string-literal escape (per char; the templates are printable ASCII + spaces).
def cesc(s)
  s.each_char.map do |c|
    case c
    when "\\" then "\\\\"
    when '"'  then '\\"'
    when "\n" then '\\n'
    when "\t" then '\\t'
    else c
    end
  end.join
end

templates = Dir["#{TPL_DIR}/*.template.c"].sort
buf = +"/* GENERATED by tools/embed_templates.rb from the templates/ directory.\n"
buf << " * Do not edit by hand — edit the .template.c source and re-run the embedder\n"
buf << " * (make -C src/codegen_c templates), then commit this file. */\n"
buf << "#ifndef SPNL_TEMPLATES_GEN_H\n#define SPNL_TEMPLATES_GEN_H\n\n"
templates.each do |f|
  name = File.basename(f).sub(/\.template\.c\z/, "")
  buf << "static const char tpl_#{name}[] =\n"
  File.read(f).each_line { |line| buf << "    \"#{cesc(line)}\"\n" }
  buf << "    ;\n\n"
end
buf << "#endif /* SPNL_TEMPLATES_GEN_H */\n"
File.write(OUT, buf)
puts "wrote #{OUT} (#{templates.size} template(s))"
