/* gen_loader_contract.c -- derive the loader's half of the codegen seam.
 *
 *   cc -O2 -o gen_loader_contract tools/gen_loader_contract.c
 *   ./gen_loader_contract        > src/spinel_ebpf/loader_contract_gen.rb
 *   ./gen_loader_contract --json > src/spinel_ebpf/loader_contract_gen.json
 *
 * (make -C src/codegen_c loader-contract does both.)
 *
 * The Ruby module is what bin/spinel-ebpf interpolates into the glue heredoc, so
 * the loader has no map-name literal, no hand-typed strncmp length and no
 * hand-typed record width to get wrong. The JSON is what
 * tools/loader_gate.rb reads (it must not have to parse C, and it must not have
 * to load the Ruby it is checking).
 *
 * Same shape as tools/gen_record_mirror.c and tools/gen_probe_ctx.c: a single
 * translation unit that #includes the declaration and prints.
 */
#include <stdio.h>
#include <string.h>
#include "../src/codegen_c/loader_contract.h"

static const char *kind_name(LcKind k)
{
  switch (k) {
  case LC_MAP_NAME:      return "map_name";
  case LC_MAP_SUFFIX:    return "map_suffix";
  case LC_PROG_PREFIX:   return "prog_prefix";
  case LC_SEC_NAME:      return "sec_name";
  case LC_RODATA_PREFIX: return "rodata_prefix";
  case LC_PROG_SEPARATOR: return "prog_separator";
  }
  return "?";
}

static const char *auth_name(LcAuthority a)
{
  switch (a) {
  case LC_AUTH_GOLDEN:        return "golden";
  case LC_AUTH_RECORD_SCHEMA: return "record_schema";
  case LC_AUTH_ATTACH_KINDS:  return "attach_kinds";
  case LC_AUTH_CODEGEN_C:     return "codegen_c";
  case LC_AUTH_CODEGEN_RULE:  return "codegen_rule";
  case LC_AUTH_NONE:          return "none";
  }
  return "?";
}

/* JSON / Ruby string escaping (both accept the same backslash forms we emit). */
static void put_str(const char *s)
{
  if (!s) { fputs("null", stdout); return; }
  putchar('"');
  for (; *s; s++) {
    switch (*s) {
    case '"':  fputs("\\\"", stdout); break;
    case '\\': fputs("\\\\", stdout); break;
    case '\n': fputs("\\n", stdout);  break;
    default:   putchar(*s);
    }
  }
  putchar('"');
}

static void put_rb(const char *s) { if (!s) fputs("nil", stdout); else put_str(s); }

static void emit_ruby(void)
{
  puts("# frozen_string_literal: true");
  puts("#");
  puts("# GENERATED by tools/gen_loader_contract.c from src/codegen_c/loader_contract.h.");
  puts("# Do not edit by hand -- edit the declaration and re-run");
  puts("#   make -C src/codegen_c loader-contract");
  puts("# then commit this file. tools/loader_gate.rb fails when it is stale.");
  puts("#");
  puts("# These constants are the LOADER's half of the codegen seam. They exist");
  puts("# so that bin/spinel-ebpf's glue heredoc contains no map-name literal, no");
  puts("# hand-typed strncmp length and no hand-typed record width: the four drifts");
  puts("# measured against this seam are not writable through this interface.");
  puts("");
  puts("module SpinelEbpf");
  puts("  module LoaderContract");
  printf("    PROG_ARRAY_SLOT_BASE = %d\n", LC_PROG_ARRAY_SLOT_BASE);
  puts("");
  puts("    # token constants -- interpolated into the glue");
  for (int i = 0; i < LC_N_ENTRIES; i++) {
    const LcEntry *e = &lc_entries[i];
    printf("    %-22s = ", e->ruby_const);
    put_str(e->token);
    printf("\n");
  }
  puts("");
  puts("    # strncmp/strstr lengths, computed from the token so they cannot disagree");
  for (int i = 0; i < LC_N_ENTRIES; i++) {
    const LcEntry *e = &lc_entries[i];
    if (e->kind != LC_PROG_PREFIX && e->kind != LC_MAP_SUFFIX) continue;
    printf("    %s_LEN = %d\n", e->ruby_const, (int)strlen(e->token));
  }
  puts("");
  puts("    # widths the loader moves, in bytes (0 = it moves no fixed record)");
  for (int i = 0; i < LC_N_ENTRIES; i++) {
    const LcEntry *e = &lc_entries[i];
    if (e->value_bytes == 0) continue;
    printf("    %s_BYTES = %d\n", e->ruby_const, e->value_bytes);
  }
  puts("");
  puts("    # the whole table, for `describe` and for the unit tests");
  puts("    ENTRIES = [");
  for (int i = 0; i < LC_N_ENTRIES; i++) {
    const LcEntry *e = &lc_entries[i];
    fputs("      { token: ", stdout);            put_str(e->token);
    fputs(", const: ", stdout);                  put_str(e->ruby_const);
    printf(", kind: :%s", kind_name(e->kind));
    printf(", authority: :%s", auth_name(e->authority));
    fputs(", witness: ", stdout);                put_rb(e->witness);
    fputs(", map_type: ", stdout);               put_rb(e->map_type);
    fputs(", key_ctype: ", stdout);              put_rb(e->key_ctype);
    fputs(", value_ctype: ", stdout);            put_rb(e->value_ctype);
    printf(", value_bytes: %d", e->value_bytes);
    fputs(", alloc: ", stdout);                  put_rb(e->alloc);
    fputs(", encoding: ", stdout);               put_rb(e->encoding);
    fputs(", encoding_measured: ", stdout);      put_rb(e->encoding_measured);
    fputs(", note: ", stdout);                   put_rb(e->note);
    fputs(" }.freeze,\n", stdout);
  }
  puts("    ].freeze");
  puts("");
  puts("    def self.[](const_name)");
  puts("      ENTRIES.find { |e| e[:const] == const_name.to_s } or");
  puts("        raise KeyError, \"loader contract has no #{const_name}; declared: \" \\");
  puts("                        \"#{ENTRIES.map { |e| e[:const] }.join(' ')}\"");
  puts("    end");
  puts("  end");
  puts("end");
}

static void emit_json(void)
{
  printf("{\"schema\":\"spinel-ebpf/loader-contract/1\",");
  printf("\"generated_by\":\"tools/gen_loader_contract.c\",");
  printf("\"generated_from\":\"src/codegen_c/loader_contract.h\",");
  printf("\"prog_array_slot_base\":%d,", LC_PROG_ARRAY_SLOT_BASE);
  printf("\"entries\":[");
  for (int i = 0; i < LC_N_ENTRIES; i++) {
    const LcEntry *e = &lc_entries[i];
    if (i) putchar(',');
    printf("{\"token\":");        put_str(e->token);
    printf(",\"const\":");        put_str(e->ruby_const);
    printf(",\"kind\":\"%s\"",    kind_name(e->kind));
    printf(",\"authority\":\"%s\"", auth_name(e->authority));
    printf(",\"witness\":");      put_str(e->witness);
    printf(",\"map_type\":");     put_str(e->map_type);
    printf(",\"key_ctype\":");    put_str(e->key_ctype);
    printf(",\"value_ctype\":");  put_str(e->value_ctype);
    printf(",\"value_bytes\":%d", e->value_bytes);
    printf(",\"token_len\":%d",   (int)strlen(e->token));
    printf(",\"alloc\":");        put_str(e->alloc);
    printf(",\"encoding\":");     put_str(e->encoding);
    printf(",\"encoding_measured\":"); put_str(e->encoding_measured);
    printf(",\"note\":");         put_str(e->note);
    putchar('}');
  }
  printf("]}\n");
}

int main(int argc, char **argv)
{
  if (argc > 1 && !strcmp(argv[1], "--json")) emit_json();
  else                                        emit_ruby();
  return 0;
}
