/* gen_probe_ctx.c -- derive every consumer of the probe context contract
 * from src/codegen_c/probe_ctx_schema.h.
 *
 *   gen_probe_ctx           > src/runtime/amp/probe_ctx_gen.h
 *   gen_probe_ctx --json    > src/spinel_ebpf/probe_ctx_schema_gen.json
 *
 * The header carries, for the M-core and the Linux side both:
 *   - field ids, attach ids and slot states as enums (one numbering, not four)
 *   - the frame the dispatcher fills and ctx_field() reads
 *   - per-attach provided-field bitmaps, in the exact shape the capability
 *     table publishes, so the table cannot disagree with the schema
 *   - a static initialiser for the capability table itself
 *   - _Static_assert on every size the two sides must agree about
 *
 * The JSON carries the same contract for the Ruby affordance surface and for
 * the gate (tools/probe_ctx_gate.rb).
 *
 * Both are committed derived artifacts: nothing at build time runs this. Regen
 * with `make -C src/codegen_c probe-ctx` and commit the diff, exactly as with
 * the record mirror.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "../src/codegen_c/probe_ctx_schema.h"

#define NFIELDS   ((int)(sizeof pc_fields / sizeof pc_fields[0]))
#define NATTACH   ((int)(sizeof pc_attaches / sizeof pc_attaches[0]))
#define NSTATES   ((int)(sizeof pc_slot_states / sizeof pc_slot_states[0]))

/* The capability table publishes a fixed-width bitmap: a shared-memory struct
 * read by another core gets a fixed layout, never a flexible array member (the
 * discipline record_schema.h already established for cross-core records). */
#define BITMAP_WORDS 4
#define MAX_FIELDS   (BITMAP_WORDS * 64)

static void die(const char *msg, const char *what) {
  fprintf(stderr, "gen_probe_ctx: %s: %s\n", msg, what ? what : "(null)");
  exit(1);
}

/* "thread.current.id" -> "THREAD_CURRENT_ID" */
static void upcase_ident(const char *s, char *out, size_t cap) {
  size_t j = 0;
  for (size_t i = 0; s[i] && j + 1 < cap; i++) {
    char c = s[i];
    out[j++] = (c == '.' || c == '-') ? '_' : (char)toupper((unsigned char)c);
  }
  out[j] = 0;
}

static int field_index(const char *name) {
  for (int i = 0; i < NFIELDS; i++)
    if (!strcmp(pc_fields[i].name, name)) return i;
  return -1;
}

/* Field id is 1-based so that 0 stays available as "invalid". */
static int field_id(const char *name) { return field_index(name) + 1; }

static void check_schema(void) {
  if (NFIELDS > MAX_FIELDS) die("more fields than the capability bitmap holds", "widen BITMAP_WORDS");
  for (int i = 0; i < NFIELDS; i++) {
    const PcField *f = &pc_fields[i];
    if (!f->name || !*f->name) die("field with no name", NULL);
    if (f->size != 1 && f->size != 2 && f->size != 4 && f->size != 8)
      die("field size must be 1/2/4/8", f->name);
    if (f->expose && strcmp(f->expose, "int"))
      die("v0 exposes only \"int\" context fields", f->name);
    for (int j = 0; j < i; j++)
      if (!strcmp(pc_fields[j].name, f->name)) die("duplicate field name", f->name);
  }
  for (int a = 0; a < NATTACH; a++) {
    const PcAttach *at = &pc_attaches[a];
    if (!at->attach_id) die("attach id 0 is reserved for invalid", at->name);
    if (at->attach_id >= 0xF000u) die("attach id is in the experimental range; never publish it", at->name);
    if (strcmp(at->exec_class, "THREAD") && strcmp(at->exec_class, "SCHED_LOCKED") &&
        strcmp(at->exec_class, "ISR"))
      die("unknown exec_class", at->name);
    if (!at->fields || !at->fields[0]) die("attach point provides no fields", at->name);
    for (int b = 0; b < a; b++) {
      if (pc_attaches[b].attach_id == at->attach_id) die("duplicate attach id", at->name);
      if (!strcmp(pc_attaches[b].name, at->name)) die("duplicate attach name", at->name);
    }
    for (int k = 0; at->fields[k]; k++)
      if (field_index(at->fields[k]) < 0) die("attach point names an undeclared field", at->fields[k]);
  }
}

static void attach_bitmap(const PcAttach *at, unsigned long long w[BITMAP_WORDS]) {
  for (int i = 0; i < BITMAP_WORDS; i++) w[i] = 0;
  for (int k = 0; at->fields[k]; k++) {
    int id = field_id(at->fields[k]);
    w[id / 64] |= 1ULL << (id % 64);
  }
}

/* ------------------------------------------------------------------ header */

static void emit_header(void) {
  char up[128];

  puts("/* GENERATED by tools/gen_probe_ctx.c from src/codegen_c/probe_ctx_schema.h.");
  puts(" * Do not edit. Regenerate with `make -C src/codegen_c probe-ctx`.");
  puts(" *");
  puts(" * The probe context contract, in the one numbering every side uses: the");
  puts(" * M-core dispatcher that fills the frame, the runtime helper that reads it,");
  puts(" * the capability table that publishes it, and the Linux installer that");
  puts(" * checks a manifest against it. */");
  puts("#ifndef SPNL_PROBE_CTX_GEN_H");
  puts("#define SPNL_PROBE_CTX_GEN_H");
  puts("");
  puts("#include <stdint.h>");
  puts("");
  printf("#define PROBE_CTX_FORMAT_VERSION 1u\n");
  printf("#define PROBE_CTX_N_FIELDS %du\n", NFIELDS);
  printf("#define PROBE_CTX_N_ATTACH %du\n", NATTACH);
  printf("#define PROBE_CTX_BITMAP_WORDS %du\n", BITMAP_WORDS);
  puts("");

  /* --- field ids --- */
  puts("/* Field ids. 1-based: 0 is reserved for \"invalid\", which is what an");
  puts(" * out-of-range ctx_field() argument decays to. Burned into every blob that");
  puts(" * calls ctx_field, hence append-only. */");
  puts("enum probe_ctx_field {");
  puts("  PROBE_CTX_FIELD_INVALID = 0,");
  for (int i = 0; i < NFIELDS; i++) {
    upcase_ident(pc_fields[i].name, up, sizeof up);
    printf("  PROBE_CTX_FIELD_%-28s = %d,   /* %s */\n", up, i + 1, pc_fields[i].ctype);
  }
  puts("};");
  puts("");

  /* --- attach ids --- */
  puts("/* Attach ids. Ranges: 0x0001-0x0FFF RTOS-provided, 0x1000-0x1FFF");
  puts(" * application-declared, 0xF000+ experimental (never published). */");
  puts("enum probe_attach_id {");
  puts("  PROBE_ATTACH_INVALID = 0,");
  for (int a = 0; a < NATTACH; a++) {
    upcase_ident(pc_attaches[a].name, up, sizeof up);
    printf("  PROBE_ATTACH_%-28s = 0x%04Xu,\n", up, pc_attaches[a].attach_id);
  }
  puts("};");
  puts("");

  /* --- execution class --- */
  puts("/* Execution class of an attach point. Read by the cycle-budget policy and");
  puts(" * by the fault policy; not documentation. */");
  puts("enum probe_exec_class {");
  puts("  PROBE_EXEC_THREAD       = 0,  /* preemptible thread context */");
  puts("  PROBE_EXEC_SCHED_LOCKED = 1,  /* scheduler or irq lock held */");
  puts("  PROBE_EXEC_ISR          = 2,  /* interrupt context */");
  puts("};");
  puts("");

  /* --- slot states --- */
  puts("/* Slot lifecycle. */");
  puts("enum probe_slot_state {");
  for (int i = 0; i < NSTATES; i++) {
    upcase_ident(pc_slot_states[i].name, up, sizeof up);
    printf("  PROBE_SLOT_%-14s = %u,   /* %s */\n", up, pc_slot_states[i].value,
           pc_slot_states[i].note);
  }
  puts("};");
  puts("");

  /* --- drop classes --- */
  puts("/* Drop classes. One counter cannot be diagnosed: \"the consumer");
  puts(" * is slow\" and \"the probe re-entered\" call for opposite responses. */");
  puts("enum probe_drop_class {");
  puts("  PROBE_DROP_RING_FULL              = 0,");
  puts("  PROBE_DROP_REENTRANT              = 1,");
  puts("  PROBE_DROP_DISABLED_OR_FAULTED    = 2,");
  puts("  PROBE_DROP_CYCLE_ADMISSION_REJECT = 3,");
  puts("  PROBE_DROP_N                      = 4,");
  puts("};");
  puts("");

  /* --- the frame --- */
  puts("/* The frame the dispatcher fills and ctx_field() reads.");
  puts(" *");
  puts(" * Indexed by field id, so slot 0 is unused and reads of it are the invalid");
  puts(" * case. `provided` says which slots this event actually filled: a probe");
  puts(" * admitted against a capability cannot ask for anything else, so a miss");
  puts(" * here means a bug rather than a user error, and the runtime counts it");
  puts(" * instead of returning a silent zero. */");
  puts("struct probe_ctx_frame {");
  printf("  uint64_t v[PROBE_CTX_N_FIELDS + 1];\n");
  printf("  uint64_t provided[PROBE_CTX_BITMAP_WORDS];\n");
  puts("};");
  puts("");

  /* --- capability entry --- */
  puts("/* One published attach point. Fixed layout: another core reads this out of");
  puts(" * shared memory, so no flexible array members and no implicit padding");
  puts(" * assumptions -- the asserts below pin it. */");
  puts("struct probe_attach_capability {");
  puts("  uint32_t attach_id;");
  puts("  uint32_t exec_class;");
  puts("  uint32_t max_cycle_budget;");
  puts("  uint32_t field_bitmap_words;");
  puts("  uint64_t field_bitmap[PROBE_CTX_BITMAP_WORDS];");
  puts("};");
  puts("");
  puts("_Static_assert(sizeof(struct probe_attach_capability) == 16 + 8 * PROBE_CTX_BITMAP_WORDS,");
  puts("               \"probe_attach_capability has implicit padding; the two cores would disagree\");");
  puts("");

  /* --- per-attach bitmaps --- */
  puts("/* Per-attach provided-field bitmaps, generated from the schema so the");
  puts(" * published capability and the dispatcher's filler cannot drift apart. */");
  for (int a = 0; a < NATTACH; a++) {
    unsigned long long w[BITMAP_WORDS];
    attach_bitmap(&pc_attaches[a], w);
    upcase_ident(pc_attaches[a].name, up, sizeof up);
    printf("#define PROBE_ATTACH_%s_BITMAP { ", up);
    for (int i = 0; i < BITMAP_WORDS; i++)
      printf("0x%016llxULL%s", w[i], i + 1 < BITMAP_WORDS ? ", " : " ");
    printf("}\n");
  }
  puts("");

  /* --- capability table initialiser --- */
  puts("/* The table the firmware publishes. Gated per attach point by the Kconfig");
  puts(" * symbol the schema names: Zephyr's hook inventory is not this firmware's");
  puts(" * exported attach set, so a point that was not built");
  puts(" * in must not appear here. */");
  puts("#define PROBE_CAPABILITY_TABLE_INIT \\");
  for (int a = 0; a < NATTACH; a++) {
    const PcAttach *at = &pc_attaches[a];
    unsigned long long w[BITMAP_WORDS];
    attach_bitmap(at, w);
    upcase_ident(at->name, up, sizeof up);
    printf("  /* %s */ \\\n", at->name);
    printf("  IF_ENABLED(%s, ( \\\n", at->kconfig);
    printf("    { .attach_id = PROBE_ATTACH_%s, \\\n", up);
    printf("      .exec_class = PROBE_EXEC_%s, \\\n", at->exec_class);
    printf("      .max_cycle_budget = %uu, \\\n", at->max_cycle_budget);
    printf("      .field_bitmap_words = PROBE_CTX_BITMAP_WORDS, \\\n");
    printf("      .field_bitmap = PROBE_ATTACH_%s_BITMAP }, )) \\\n", up);
  }
  puts("");
  puts("");

  /* --- names, for diagnostics and for the Linux side --- */
  puts("/* Names. The M-core does not need these to run, but the installer's");
  puts(" * rejection message does, and a firmware built with diagnostics can say");
  puts(" * which field a probe asked for. */");
  puts("#ifdef PROBE_CTX_WANT_NAMES");
  puts("static const char *const probe_ctx_field_names[PROBE_CTX_N_FIELDS + 1] = {");
  puts("  \"(invalid)\",");
  for (int i = 0; i < NFIELDS; i++) printf("  \"%s\",\n", pc_fields[i].name);
  puts("};");
  puts("static const char *const probe_attach_names[PROBE_CTX_N_ATTACH] = {");
  for (int a = 0; a < NATTACH; a++) printf("  \"%s\",\n", pc_attaches[a].name);
  puts("};");
  puts("#endif /* PROBE_CTX_WANT_NAMES */");
  puts("");

  /* --- sizes both sides must agree about --- */
  puts("/* Sizes the dispatcher's filler and the reader must agree about. */");
  for (int i = 0; i < NFIELDS; i++) {
    upcase_ident(pc_fields[i].name, up, sizeof up);
    printf("#define PROBE_CTX_FIELD_%s_SIZE %du\n", up, pc_fields[i].size);
    printf("#define PROBE_CTX_FIELD_%s_SIGNED %du\n", up, pc_fields[i].is_signed ? 1 : 0);
  }
  puts("");
  puts("#endif /* SPNL_PROBE_CTX_GEN_H */");
}

/* -------------------------------------------------------------------- json */

static void json_str(const char *s) {
  putchar('"');
  for (const unsigned char *p = (const unsigned char *)(s ? s : ""); *p; p++) {
    if (*p == '"' || *p == '\\') printf("\\%c", *p);
    else if (*p == '\n') printf("\\n");
    else if (*p < 0x20) printf("\\u%04x", *p);
    else putchar(*p);
  }
  putchar('"');
}

static void emit_json(void) {
  printf("{\n");
  printf("  \"schema\": \"spinel-ebpf.probe-ctx-contract/1\",\n");
  printf("  \"format_version\": %u,\n", 1u);
  printf("  \"bitmap_words\": %d,\n", BITMAP_WORDS);

  printf("  \"fields\": [\n");
  for (int i = 0; i < NFIELDS; i++) {
    const PcField *f = &pc_fields[i];
    printf("    { \"id\": %d, \"name\": ", i + 1);
    json_str(f->name);
    printf(", \"ctype\": ");
    json_str(f->ctype);
    printf(", \"size\": %d, \"signed\": %d, \"expose\": ", f->size, f->is_signed ? 1 : 0);
    if (f->expose) json_str(f->expose); else printf("null");
    printf(", \"note\": ");
    json_str(f->note);
    printf(" }%s\n", i + 1 < NFIELDS ? "," : "");
  }
  printf("  ],\n");

  printf("  \"attaches\": [\n");
  for (int a = 0; a < NATTACH; a++) {
    const PcAttach *at = &pc_attaches[a];
    unsigned long long w[BITMAP_WORDS];
    attach_bitmap(at, w);
    printf("    { \"id\": %u, \"name\": ", at->attach_id);
    json_str(at->name);
    printf(", \"exec_class\": ");
    json_str(at->exec_class);
    printf(", \"max_cycle_budget\": %u, \"hook\": ", at->max_cycle_budget);
    json_str(at->hook);
    printf(", \"kconfig\": ");
    json_str(at->kconfig);
    printf(", \"fields\": [");
    for (int k = 0; at->fields[k]; k++) {
      if (k) printf(", ");
      json_str(at->fields[k]);
    }
    printf("], \"bitmap\": [");
    for (int i = 0; i < BITMAP_WORDS; i++) printf("%s%llu", i ? ", " : "", w[i]);
    printf("], \"note\": ");
    json_str(at->note);
    printf(" }%s\n", a + 1 < NATTACH ? "," : "");
  }
  printf("  ],\n");

  printf("  \"slot_states\": [\n");
  for (int i = 0; i < NSTATES; i++) {
    printf("    { \"name\": ");
    json_str(pc_slot_states[i].name);
    printf(", \"value\": %u, \"note\": ", pc_slot_states[i].value);
    json_str(pc_slot_states[i].note);
    printf(" }%s\n", i + 1 < NSTATES ? "," : "");
  }
  printf("  ]\n");
  printf("}\n");
}

int main(int argc, char **argv) {
  check_schema();
  if (argc > 1 && !strcmp(argv[1], "--json")) emit_json();
  else emit_header();
  return 0;
}
